- core/scss/components/button.scss
- core/scss/settings/buttons.scss
- core/scss/settings/colors.scss
Add new colors to Button : dark-gray, duck egg, violet
**After**:
> feat(buttons): add new colors to buttons - dark gray, duck egg, violet

- .github/ISSUE_TEMPLATE.md
ISSUE TEMPLATE typos fixes
I was about to create an issue, and while reading it, I saw these typos
**After**:
> doc(TEMPLATE): ISSUE TEMPLATE typos fixes

- core/scss/components/list-separator.scss
Changes color of line to $white-12 and text to white
fixes #30 
https://cisco.invisionapp.com/d/#/console/16410592/340302128/inspect
ran in on the playground locally
```
<div class="docs-container cui--dark" style="background-color: rgb(21, 21, 21);"><div class="cui-list-separator"><span class="cui-list-separator__container"><span class="cui-list-separator__text">1 Other Space to Join</span></span></div></div>
```
**After**:
> fix(list-separator): fix list separator color on dark backgrounds

- core/scss/settings/colors.scss
Hotfix of incorrect syntax in $colorList
Core will not build.
Tested with build script.
**After**:
> fix(colors): fix colorList in color settings file

- core/scss/components/button-group.scss
- react/src/lib/Button/index.js
- react/src/lib/ButtonGroup/index.js
- react/src/lib/Coachmark/index.js
- react/src/lib/Tooltip/index.js
Final changes required to allow ButtonGroup to contain components in the Virtual DOM other than the Button in the library.
Resolves #22 
**After**:
> Button group fix2

- react/src/lib/CallControl/index.js
Add 'camera' type to blue active list.
**After**:
> fix(CallControl): add camera to active blue list

- react/src/lib/ListItem/index.js
- react/src/lib/ListItem/index.spec.js
> fix(ListItem): remove error when given null value for child

- core/scss/components/components.scss
- core/scss/components/phonenumber.scss
- core/scss/ng/ng.scss
- core/scss/settings/phonenumber.scss
- core/scss/tools/mixins/list-item.scss
- Adding new phonenumber.scss file to components; creating cui-input-phonenumber classes
- Removing old phonenumber.scss from ng.scss file
- Adding cui-flag classes
- SPARK-29316
**After**:
> feat(phone-number): Updating cs-phone-number to new look/feel

- core/scss/settings/colors.scss
Added Indigo and organized colors file.
Add indigo to color palette. 
**After**:
> feat(colors): add indigo-base, organize colors

- core/scss/components/button.scss
- core/scss/components/close-wrapper.scss
- core/scss/components/components.scss
- core/scss/ng/side-panel.scss
- core/scss/settings/z-index.scss
- react/src/lib/CloseWrapper/__snapshots__/index.spec.js.snap
- react/src/lib/CloseWrapper/index.js
- react/src/lib/CloseWrapper/index.spec.js
- react/src/lib/index.js
- tools/release.sh
> feat(CloseWrapper): add CloseWrapper as a component

- core/scss/settings/settings.scss
> Missing phonenumber.scss import in settings.scss - SPARK29316

- core/package.json
- yarn.lock
Add visual regression testing to the Core library with Cypress.io and Percy.io
VR Testing will allow the Momentum team to be confident that changes only affect the components that are intended.
> Add Visual Regression Testing

- react/src/lib/EventOverlay/index.js
> feat(EventOverlay): add transform ancestor check for top direction

- core/scss/components/panel.scss
> fix(panel): adjust flex properties for ie11 footer

- core/scss/components/avatar.scss
- core/scss/settings/avatar.scss
Pending more documentation from design - this fix will change failure badge to use icon.  Sizing could be improved in a future PR with designs/specs for all size variations.
Resolves #72 
**After**:
> fix(avatar): change failure badge to icon

- react/src/lib/Lightbox/index.js
- react/src/lib/List/index.js
- react/src/lib/Menu/index.js
Query Selector wasn't working with strings.
**After**:
> fix(List): add double quotes to querySelector

- core/scss/components/panel.scss
- react/src/lib/Lightbox/index.js
- react/src/lib/List/index.js
- react/src/lib/Menu/index.js
> Footer f ix

- angular/CONTRIBUTING.md
- angular/src/lib/badge/badge.component.ts
- angular/src/lib/badge/examples/round.component.ts
- angular/src/lib/badge/tests/__snapshots__/badge.component.spec.ts.snap
- angular/src/lib/badge/tests/badge.component.spec.ts
- angular/tslint.json
Adding pattern for dynamically adding/removing classNames while maintaining custom class and `ngClass` functionality
This issue is present in several components. ex. #105
4 new unit tests and 2 snapshots added to cover className and ngClass
> fix: update className pattern to allow ngClass to work

- core/scss/components/light-box.scss
- core/scss/layouts/layout-grid.scss
- www/client/containers/Changelog/index.js
- www/client/containers/Icons/IconAnimationHelper.js
- www/client/services/motion/ashChart.js
- www/client/services/motion/ashSvg.js
- www/client/services/motion/index.js
- www/package.json
- yarn.lock
> docs: fix icon animation import

- core/scss/components/avatar/settings.scss
Update the in meeting presence type to align with the desktop client.
**After**:
> fix(avatar): update in meeting presence type

- core/scss/components/sidebar/sidebar.scss
- core/scss/components/space-list/space-list-item.scss
Support compact mode.
Override sass to support compact mode for space list item.
Override sass to support compact mode for space list item.
**After**:
> feat(space-list-item): add styles for compact mode

- core/scss/components/activity-button/activity-button.scss
- core/scss/components/activity-button/examples/size-56.html
- react/src/lib/ActivityButton/examples/Size56.js
- react/src/lib/ActivityButton/examples/index.js
- react/src/lib/ActivityButton/index.js
- react/src/lib/ActivityButton/tests/__snapshots__/index.spec.js.snap
- react/src/lib/ActivityButton/tests/index.spec.js
Adds a contact-card type
Removes `large` prop and adds a size prop
Need a new Activity Button Size
Playground
**After**:
> feat(ActivityButton): add contact-card activity and update size prop

- core/scss/components/activity-button/activity-button.scss
updating color for contact-card ActivityButton
**After**:
> fix(ActivityButton): update color for contact-card ActivityButton

- core/scss/components/list/mixins.scss
> fix(list-item): remove specificity from list item mixin

- angular/src/lib/breadcrumbs/breadcrumbs.component.ts
- angular/src/lib/breadcrumbs/breadcrumbs.module.ts
- angular/src/lib/breadcrumbs/examples/breadcrumbs-default.component.ts
- angular/src/lib/breadcrumbs/examples/breadcrumbs-examples.module.ts
- angular/src/lib/breadcrumbs/examples/index.ts
- angular/src/lib/breadcrumbs/index.ts
- angular/src/lib/breadcrumbs/tests/breadcrumbs.component.spec.ts
- angular/src/lib/examples.module.ts
- angular/src/lib/public_api.ts
add breadcrumbs component
**After**:
> feat(breadcrumbs):add breadcrumbs component

- angular/src/docs/app/playground/playground.component.ts
- angular/src/lib/examples.module.ts
- angular/src/lib/popover/examples/index.ts
- angular/src/lib/popover/examples/popover-default.component.ts
- angular/src/lib/popover/examples/popover-direction.component.ts
- angular/src/lib/popover/examples/popover-examples.module.ts
- angular/src/lib/popover/examples/popover-showarrow.component.ts
- angular/src/lib/popover/examples/popover-trigger.component.ts
- angular/src/lib/popover/index.ts
- angular/src/lib/popover/popover-container.component.ts
- angular/src/lib/popover/popover.component.ts
- angular/src/lib/popover/popover.directive.ts
- angular/src/lib/popover/popover.module.ts
- angular/src/lib/popover/tests/__snapshots__/popover.component.spec.ts.snap
- angular/src/lib/popover/tests/popover.component.spec.ts
- angular/src/lib/public_api.ts
- core/scss/components/popover/popover.scss
- core/scss/ng/popover.scss
Adding the Popover
Adding the popover 
adding new popover
**After**:
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.
> Add popover

- angular/src/lib/call-control/call-control.component.ts
- angular/src/lib/call-control/call-control.module.ts
- angular/src/lib/call-control/examples/active.component.ts
- angular/src/lib/call-control/examples/cancel.component.ts
- angular/src/lib/call-control/examples/default.component.ts
- angular/src/lib/call-control/examples/disable.component.ts
- angular/src/lib/call-control/examples/examples.module.ts
- angular/src/lib/call-control/examples/index.ts
- angular/src/lib/call-control/index.ts
- angular/src/lib/call-control/tests/__snapshots__/call-control.component.spec.ts.snap
- angular/src/lib/call-control/tests/call-control.component.spec.ts
- angular/src/lib/examples.module.ts
- angular/src/lib/public_api.ts
> feat(CallControl): add Angular CallControl component

- core/scss/components/button/mixins.scss
- core/scss/components/coachmark/coachmark.scss
- react/src/app/containers/EventOverlay/EventOverlayExamples.js
> fix(coachmark): update style to new cobalt color

- react/src/lib/Input/index.js
- react/src/lib/Input/tests/__snapshots__/index.spec.js.snap
- react/src/lib/Input/tests/index.spec.js
- react/src/lib/SearchInput/tests/__snapshots__/index.spec.js.snap
- react/src/lib/TimePicker/tests/__snapshots__/index.spec.js.snap
add ariaLabel and ariaDescribedBy props to ComboBox Input feild for accessibility
https://github.com/momentum-design/momentum-ui/issues/198
**After**:
> feat(ComboBox): add ariaLabel and ariaDescribedBy props for accessibility

- react/src/lib/Alert/examples/Default.js
- react/src/lib/Alert/examples/Error.js
- react/src/lib/Alert/examples/Success.js
- react/src/lib/Alert/examples/Warning.js
> chore(Alert): remove unused state

- react/src/lib/Button/index.js
> fix(Button): change handleClick function

- angular/src/lib/date-picker/date-picker.component.ts
- angular/src/lib/modal/modal.component.ts
- angular/src/lib/time-picker/time-picker.component.ts
Check backdropElement before remove it
**After**:
> fix(modal, timepick, datepicker): fix overlay close bug

- angular/src/lib/coachmark/coachmark.component.ts
- angular/src/lib/coachmark/coachmark.module.ts
- angular/src/lib/coachmark/coachmark.service.ts
- angular/src/lib/coachmark/examples/coachmark-arrow.component.ts
- angular/src/lib/coachmark/examples/coachmark-backdrop.component.ts
- angular/src/lib/coachmark/examples/coachmark-default.component.ts
- angular/src/lib/coachmark/examples/coachmark-delay.component.ts
- angular/src/lib/coachmark/examples/coachmark-examples.module.ts
- angular/src/lib/coachmark/examples/coachmark-open.component.ts
- angular/src/lib/coachmark/examples/index.ts
- angular/src/lib/coachmark/index.ts
- angular/src/lib/coachmark/test/__snapshots__/coachmark.component.spec.ts.snap
- angular/src/lib/coachmark/test/coachmark.component.spec.ts
- angular/src/lib/coachmark/test/coachmark.service.spec.ts
- angular/src/lib/examples.module.ts
- angular/src/lib/public_api.ts
create
**After**:
- [] I have updated the documentation accordingly.
> feat(coachmark):create

- angular/src/lib/date-picker/date-picker.service.ts
fix event when veiw month change
**After**:
> fix(date picker):fix event when veiw month change

- react/src/lib/ModalHeader/index.js
- react/src/lib/ModalHeader/tests/__snapshots__/index.spec.js.snap
- react/src/lib/ModalHeader/tests/index.spec.js
- react/src/lib/Radio/index.js
- react/src/lib/Radio/tests/__snapshots__/index.spec.js.snap
- react/src/lib/Radio/tests/index.spec.js
Issues referenced in: https://cisco.app.box.com/notes/458930461850?s=3jb9tz3or2a8jqtctpv9jv3knfjy8lu1
**After**:
> Aricent fixes

- core/scss/momentum-ui-ng.scss
- core/scss/ng/card.scss
- fix regression from scss refactor
https://github.com/momentum-design/momentum-ui/pull/240
local link
**After**:
> fix(card): fix angularjs card styles

- angular/src/lib/card/card.component.ts
- angular/src/lib/card/tests/__snapshots__/card.component.spec.ts.snap
- core/scss/components/card/card.scss
- core/scss/components/card/examples/content.html
- core/scss/components/card/examples/content2.html
- core/scss/components/card/examples/default.html
- core/scss/components/card/tests/card.cy.js
Adding 'v2' to new md-card class until ng conflict is resolved.
**After**:
> fix(card): add v2 class suffix until ng conflict resolution

- angular/src/docs/app/playground/playground.component.ts
- angular/src/lib/activity-button/activity-button.component.ts
- angular/src/lib/activity-button/activity-button.module.ts
- angular/src/lib/activity-button/examples/activity-button-default.component.ts
- angular/src/lib/activity-button/examples/activity-button-examples.module.ts
- angular/src/lib/activity-button/examples/index.ts
- angular/src/lib/activity-button/index.ts
- angular/src/lib/activity-button/test/activity-button.component.spec.ts
- angular/src/lib/examples.module.ts
> feat(activity-button):create

- angularjs/src/lib/components/sidenav/sidenav.admin.component.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-76819 <-- Need to add metrics to the left nav clicks.  In order to accomplish this I'm surfacing the 'clicks' from the left nav menu items
**After**:
> fix(sidepanel): surface clickItem event

- angular/src/lib/sidebar-nav/sidebar-nav.component.ts
- angular/src/lib/sidebar-nav/sidebar-nav.service.ts
- sidebar nav should react to nav item changes
- subscribe to navItemLists changes
- share latest state from SidebarNavService
**After**:
> fix(sidebar): should support changes to nav items

- angular/src/lib/card/card.component.ts
- angular/src/lib/card/tests/__snapshots__/card.component.spec.ts.snap
- angularjs/src/lib/components/cardmember/cardmember.component.ts
- angularjs/src/lib/components/cards/card.component.ts
- core/scss/components/card/card.scss
- core/scss/components/card/examples/content.html
- core/scss/components/card/examples/content2.html
- core/scss/components/card/examples/default.html
- core/scss/components/card/tests/card.cy.js
- core/scss/ng/card.scss
BREAKING CHANGE:
angularng cards will be broken
fix the core css to make sure cards css for angularng don't conflict
**After**:
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] Breaking change (fix or feature that would cause existing functionality to change)
- [ x] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes.
> fix(card): core, angularjs and angular fixes

- react/src/lib/Alert/index.js
- react/src/lib/Alert/tests/index.spec.js
- react/src/lib/AlertBanner/index.js
- react/src/lib/AlertBanner/tests/__snapshots__/index.spec.js.snap
- react/src/lib/AlertBanner/tests/index.spec.js
- react/src/lib/AlertCall/examples/Default.js
- react/src/lib/AlertCall/examples/Device.js
- react/src/lib/AlertCall/examples/DeviceList.js
- react/src/lib/AlertCall/examples/Number.js
- react/src/lib/AlertCall/index.js
- react/src/lib/AlertCall/tests/__snapshots__/index.spec.js.snap
- react/src/lib/AlertCall/tests/index.spec.js
- react/src/lib/AlertCallContainer/index.js
- react/src/lib/AlertCallContainer/tests/__snapshots__/index.spec.js.snap
- react/src/lib/AlertCallContainer/tests/index.spec.js
- react/src/lib/AlertContainer/index.js
- react/src/lib/AlertContainer/tests/index.spec.js
- react/src/lib/AlertMeeting/examples/Default.js
- react/src/lib/AlertMeeting/index.js
- react/src/lib/AlertMeeting/tests/__snapshots__/index.spec.js.snap
- react/src/lib/AlertMeeting/tests/index.spec.js
> Alert aricent updates

- angular/src/lib/card/card.component.ts
- angular/src/lib/card/examples/card-clickable.component.ts
- angular/src/lib/card/examples/card-examples.module.ts
- angular/src/lib/card/tests/__snapshots__/card.component.spec.ts.snap
- angular/src/lib/card/tests/card.component.spec.ts
- core/scss/components/card/card.scss
- core/scss/components/card/examples/clickable.html
**After**:
- [ x] New feature (non-breaking change which adds functionality)
- [x ] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes.
> feat(card): angular and core add states and click to cards

- core/scss/components/button/mixins.scss
- core/scss/components/card/card.scss
> fix(prepend & append): height auto was breaking the calc function

- vue/src/examples.js
- vue/src/index.js
- vue/src/lib/icon/examples/color.vue
- vue/src/lib/icon/examples/default.vue
- vue/src/lib/icon/examples/index.js
- vue/src/lib/icon/examples/white.vue
- vue/src/lib/icon/index.vue
- vue/src/lib/icon/tests/__snapshots__/icon.spec.js.snap
- vue/src/lib/icon/tests/icon.spec.js
- vue/tools/bin/new.js
> feat(Vue Icon): add Vue Icon component

- vue/src/examples.js
- vue/src/index.js
- vue/src/lib/button-group/examples/default.vue
- vue/src/lib/button-group/examples/highlight-false.vue
- vue/src/lib/button-group/examples/index.js
- vue/src/lib/button-group/examples/justified-false.vue
- vue/src/lib/button-group/examples/pill.vue
- vue/src/lib/button-group/index.vue
- vue/src/lib/button-group/tests/__snapshots__/button-group.spec.js.snap
- vue/src/lib/button-group/tests/button-group.spec.js
- vue/src/lib/button/index.vue
- vue/src/lib/button/tests/button.spec.js
- vue/src/lib/utils/cloneElement.js
> feat(Vue ButtonGroup): add ButtonGroup component

- chart/src/lib/arc/index.js
- chart/src/lib/area/index.js
- chart/src/lib/board/index.js
- chart/src/lib/index.js
- chart/src/lib/line/index.js
- chart/src/lib/link/index.js
- chart/src/lib/rect/index.js
- chart/src/lib/symbol/index.js
- chart/src/lib/text/index.js
- chart/tools/init/init.js
> fix(compress): add shapeName

- angularjs/src/lib/components/pageheader/pageheader.component.ts
Add transclude for placing the content in page header
**After**:
> feat(angularjs)-ng-transclude for page header right

- react/src/app/containers/KitchenSink/index.js
> chore(KitchenSink): change SearchInput to InputSearch

- angular/src/lib/modal/modal-ref.ts
- angular/src/lib/modal/modal.service.ts
changed data type to any to allow any value
**After**:
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have read the **CONTRIBUTING** document.
> fix (angular modal) changed data type

- angular/src/lib/toggle-switch/examples/toggle-switch-examples.module.ts
> chore(toggle-switch): correct import in example module

- angular/src/lib/data-table/data-table-checkbox.component.ts
- angular/src/lib/data-table/data-table.component.ts
- angular/src/lib/data-table/examples/data-table-multi-select.component.ts
- angular/src/lib/public_api.ts
- angular/src/lib/toggle-switch/examples/toggle-switch-default.component.ts
- core/scss/components/data-table/data-table.scss
1.  fixed export of data-table to include index path -->  export * from './data-table/index' 
2. Will now show selected checkboxes [] boolean value on page load
2. Added cursor pointer to checkbox
3. Update examples 
**After**:
> fix(data-table): table will show selected checkboxes on load

- angular/src/lib/popover/tests/__snapshots__/popover.component.spec.ts.snap
- angular/src/lib/tooltip/tests/__snapshots__/tooltip.component.spec.ts.snap
- angular/src/lib/tooltip/tooltip-container.component.ts
- angular/src/lib/tooltip/tooltip.component.ts
- angular/src/lib/tooltip/tooltip.directive.ts
> fix(angular): add max-width so that tooltips wrap at some point

- react/src/app/containers/KitchenSink/index.js
- react/src/lib/Checkbox/examples/KitchenSink.js
- react/src/lib/Checkbox/examples/index.js
- react/src/lib/Checkbox/tests/checkbox.cy.js
- react/src/lib/Radio/examples/KitchenSink.js
- react/src/lib/Radio/examples/index.js
- react/src/lib/Radio/tests/radio.cy.js
> chore(react): add checkbox and radio kitchen sinks

- angular/src/lib/modal/modal.module.ts
- angular/src/lib/popover/popover.module.ts
- angular/src/lib/tooltip/tooltip.module.ts
missing overlayModule imports was causing a static injection error
**After**:
> fix(angular): static injection error for cdk Overlay

- core/scss/components/select/select.scss
The select filter input now covering the width of the overlay container instead of just a portion.
fix:
**After**:
> fix(select): select filter search width to 100%

- angular/src/lib/input/index.ts
- angular/src/lib/input/input.module.ts
Refactor the input components to all be included through the InputModule, eliminating the need to import the individual modules.
> Input modules refactor

- core/scss/ng/settings/settings.scss
- core/scss/settings/core.scss
- core/scss/settings/settings.scss
- core/scss/tools/functions/core.scss
- core/scss/tools/placeholders/responsive-spacing.scss
- core/scss/typography/settings.scss
- icons/scss/mixins.scss
- icons/templates/mixins.scss.hbs
Remove !global scss variable declarations since they will be deprecated in Dart Sass v2
Fixes #339
> fix(globals): remove scss !globals

- angular/src/docs/app/kitchen-sink/kitchen-sink.component.ts
- angular/src/docs/app/playground/playground.component.ts
- angular/src/lib/alert/tests/__snapshots__/alert.service.spec.ts.snap
- angular/src/lib/call-control/tests/__snapshots__/call-control.component.spec.ts.snap
- angular/src/lib/combo-box/tests/__snapshots__/combo-box.component.spec.ts.snap
- angular/src/lib/drawer/tests/__snapshots__/drawer.component.spec.ts.snap
- angular/src/lib/icon/icon.component.ts
- angular/src/lib/icon/icon.module.ts
- angular/src/lib/icon/tests/icon.component.spec.ts
- angular/src/lib/input/examples/kitchen-sink.component.ts
- core/app/containers/KitchenSink/index.js
- core/app/containers/Playground/index.js
- core/scss/components/checkbox/checkbox.scss
- core/scss/components/icon/icon.scss
- core/scss/components/input/examples/kitchen-sink.html
- core/scss/components/input/input.scss
- core/scss/components/input/mixins.scss
- core/scss/components/radio/radio.scss
- react/src/app/containers/KitchenSink/index.js
- react/src/app/containers/Playground/index.js
- react/src/lib/Input/examples/KitchenSink.js
> fix(icon): center icons in icon container

- angularjs/src/lib/components/datepicker/datepicker.component.ts
- angularjs/src/lib/components/phoneNumber/phoneNumber.component.ts
- angularjs/src/lib/directives/timepicker/timepicker.directive.ts
- core/scss/components/input-phone-number/input-phone-number.scss
- core/scss/components/input/mixins.scss
- core/scss/components/panel/panel.scss
- fix `.md-input-container` classes targeted by other component/mixin rulesets
- fix some missing angularjs `error`/`warning` classes with `md-` prefix
**After**:
> Update input container and error/warning classes

- react/src/lib/Topbar/index.js
> Fix error from null children in Topbar

- core/scss/components/tooltip/settings.scss
- core/scss/components/tooltip/tooltip.scss
- core/scss/ng/settings/settings.scss
- core/scss/settings/settings.scss
Removed the fixed width of the tooltips text and replaced it with `min-width` and `max-width` specifications. Long continuous text (a really long word) would also overflow and not wrap/break onto a new line so also added in `word-break: break-word` to take care of that. 
Tooltips don't match the design specs and look huge. Has been fixed for angular and not react. 
Dev tools across multiple browsers.
Looking huge
Text overflow for long word
**After**:
> fix(tooltips): update tooltip stylings per design specs

- core/scss/components/button-group/button-group.scss
- react/src/lib/ActivityButton/tests/__snapshots__/index.spec.js.snap
- react/src/lib/ActivityButton/tests/index.spec.js
- react/src/lib/Alert/tests/__snapshots__/index.spec.js.snap
- react/src/lib/AlertCall/tests/__snapshots__/index.spec.js.snap
- react/src/lib/AlertMeeting/tests/__snapshots__/index.spec.js.snap
- react/src/lib/Button/index.js
- react/src/lib/Button/tests/__snapshots__/index.spec.js.snap
- react/src/lib/Button/tests/index.spec.js
- react/src/lib/ButtonGroup/index.js
- react/src/lib/ButtonGroup/tests/__snapshots__/index.spec.js.snap
- react/src/lib/ButtonGroup/tests/index.spec.js
- react/src/lib/ButtonGroupContext/index.js
- react/src/lib/CallControl/tests/__snapshots__/index.spec.js.snap
- react/src/lib/CallControl/tests/index.spec.js
- react/src/lib/CollapseButton/tests/__snapshots__/index.spec.js.snap
- react/src/lib/CollapseButton/tests/index.spec.js
- react/src/lib/ContentItem/examples/Default.js
- react/src/lib/ContentItem/examples/Gif.js
- react/src/lib/ContentItem/examples/KitchenSink.js
- react/src/lib/ContentItem/examples/index.js
- react/src/lib/DatePicker/DatePickerDay/tests/__snapshots__/index.spec.js.snap
- react/src/lib/Select/tests/__snapshots__/index.spec.js.snap
- react/src/lib/SelectableContext/index.js
- react/src/lib/TimePicker/examples/24Hour.js
- react/src/lib/TimePicker/examples/30MinuteStep.js
- react/src/lib/TimePicker/examples/Default.js
Resolves #331 
@aimeex3 
**After**:
> Update ButtonGroup to new context api

- react/src/lib/ActivityButton/tests/__snapshots__/index.spec.js.snap
- react/src/lib/Alert/tests/__snapshots__/index.spec.js.snap
- react/src/lib/AlertCall/tests/__snapshots__/index.spec.js.snap
- react/src/lib/AlertMeeting/tests/__snapshots__/index.spec.js.snap
- react/src/lib/CallControl/tests/__snapshots__/index.spec.js.snap
- react/src/lib/Chip/tests/__snapshots__/index.spec.js.snap
- react/src/lib/CloseWrapper/tests/__snapshots__/index.spec.js.snap
- react/src/lib/CollapseButton/tests/__snapshots__/index.spec.js.snap
- react/src/lib/Icon/index.js
- react/src/lib/Icon/tests/__snapshots__/index.spec.js.snap
- react/src/lib/Icon/tests/index.spec.js
- react/src/lib/InputSearch/tests/__snapshots__/index.spec.js.snap
- react/src/lib/Lightbox/tests/__snapshots__/index.spec.js.snap
- react/src/lib/Select/tests/__snapshots__/index.spec.js.snap
- react/src/lib/TopbarMobile/tests/__snapshots__/index.spec.js.snap
BREAKING CHANGE:
1. Icon
* Remove isAria prop and deprecation warning
@aimeex3 
**After**:
> fix(Icon): add title prop to icon element or button if onClick present

- core/scss/ng/page-header-admin.scss
- core/scss/tools/placeholders/page-layout.scss
changing backgrounds for control hub refresh
adding a class for control hub refresh color changes
**After**:
> feat(core): background updates for CH

- angular/src/lib/alert-banner/alert-banner.component.ts
fix on alert banner, no longer closing it when tabbed on.
**After**:
> fix(alert-banner) : tab not to close alert banner when open

- core/scss/layouts/layout-grid/examples/offsets.html
> docs(layouts): add offset example

- charts/src/lib/webComponents.js
- fixes ReferenceError seen in test environment
**After**:
> fix(charts): reference customElements on window

- angular/src/lib/tooltip/tooltip.directive.ts
Fix behaviors of allowHover event on tooltip. 
- Remove Object unsubscribed error. https://stackoverflow.com/questions/43447775/objectunsubscribederror-object-unsubscribed-error-when-i-am-using-ngx-progress/49989710
- Fix behavior that allowHover does not work on first attempt. 
- Fix behavior that it closes tooltip on hover again to tooltip target from tooltip content container. 
**After**:
> fix(angular): fix tooltip allowHover behavior

- angular/src/lib/tooltip/tooltip.directive.ts
It needs to have new subscription for each tooltips. 
**After**:
> fix(angular): tooltips when allowHover is true

- core/scss/tools/placeholders/page-layout.scss
> core(fix) undo background color added for refresh

- angular/src/lib/tooltip/tooltip.directive.ts
Tooltip usually does not have link. 
However, when using tooltip as pop over (that has interaction), we need to set the condition properly for closing the tooltip. 
**After**:
> fix(tooltip): close tooltip on destroy

- core/scss/components/input-phone-number/input-phone-number.scss
> fix(core): Provision 5317 fix phone number input alignment

- core/scss/ng/tokenfield.scss
- yarn.lock
adds left padding (12px) in token-input css class
adds left padding in token-input css class
The text in text-input touches the border. Needed some spacing...
Manually verified the fix.
**After**:
> fix(core): adds left padding in token-input css class

- angular/src/lib/select/select.component.ts
Fix errors on select component in Angular
**After**:
> fix(angular/select): NullInjectorError: No provider for TableService

- angularjs/src/lib/components/select/select.component.ts
- AngularJs search filter for the md-select was breaking due to the `this` reference being lost; should be using arrow function 
**After**:
> fix: 🐛 AngularJS: md-select error on search filters

- angularjs/src/lib/components/phoneNumber/phoneNumber.component.ts
Allow US region to validate numbers for the Bahamas as part of humanitarian efforts
**After**:
> fix: 🐛 phonenumber - allow 'us' region to validate bahamas nums

- angular/src/lib/select/examples/select-default.component.ts
- angular/src/lib/select/select.component.ts
- Adds Scroll to select overlay
- add scrollHeight prop
PROVISION-5742
**After**:
> feat(select): add scroll overflow and scrollHeight to overlay

- angular/src/lib/select/select.component.ts
- fix console errors
- list will now shrink dynamically, no fixed height 
- no horizontal scroll bar 
**After**:
> fix(select): dynamic filter height fix

- angular/src/lib/ng-package.json
- angular/src/lib/package.json
- angularjs/package.json
- core/package.json
- react/package.json
> fix: add @momentum-ui/icons to dependencies

- angular/src/lib/data-table/index.ts
Add table scroll component export. Needed for access in CH. 
**After**:
> fix(data-table): add data-table scroll component export

- angular/src/lib/sidebar-nav-item/sidebar-nav-item.component.ts
- put nav item title inside `md-list-item__header` element to support text overflow
- add `title` binding to `md-list-item` element for hover value
**After**:
> fix(sidebar): hide sidebar nav item text overflow

- angular/src/lib/select/select.component.ts
- angularjs/src/lib/components/select/examples/kitchen-sink.component.ts
- angularjs/src/lib/components/select/select.component.html
- angularjs/src/lib/components/select/select.component.ts
- angularjs/src/lib/directives/dropdown/dropdown.directive.ts
- angularjs/src/lib/directives/input/input.directive.ts
- core/scss/components/input/examples/kitchen-sink.html
- core/scss/components/select/select.scss
- core/scss/ng/dropdown.scss
- core/scss/ng/select.scss
> fix(select): add warn/error class logic

- core/scss/components/list-item/mixins.scss
- core/scss/components/sidebar/sidebar.scss
- sidebar: remove blue header color
- list-item: add more specific active/hover class for header/subheader
**After**:
> fix(sidebar): list item should honor active/hover colors

- charts/src/lib/index.js
- charts/src/lib/plugins/example/index.js
- charts/src/lib/plugins/index.js
- charts/tools/init/init.js
- www/client/components/CodePen/index.js
- www/client/containers/SideNav/index.js
enable add plugins in Charts library
**After**:
> feat(charts): add plugin management system

- angular/src/lib/topbar/tests/__snapshots__/topbar-brand.component.spec.ts.snap
- angular/src/lib/topbar/topbar-brand.component.ts
- core/scss/components/top-bar/examples/blue.html
- core/scss/components/top-bar/examples/default.html
- core/scss/components/top-bar/examples/light.html
- core/scss/components/top-bar/top-bar.scss
- react/src/lib/Button/index.js
- react/src/lib/ListSeparator/index.js
- react/src/lib/Topbar/examples/KitchenSink.js
- react/src/lib/Topbar/examples/NavFlexRight.js
- react/src/lib/Topbar/examples/index.js
- react/src/lib/Topbar/index.js
- react/src/lib/Topbar/tests/__snapshots__/index.spec.js.snap
- react/src/lib/TopbarNav/index.js
- react/src/lib/TopbarNav/tests/__snapshots__/index.spec.js.snap
Added alignment prop and access to ListProps to TopbarNav.
**After**:
> feat(TopbarNav): add alignment prop

- react/src/lib/EventOverlay/index.js
> fix(EventOverlay): fix absoluteParent logic

- core/scss/components/coachmark/coachmark.scss
> fix(coachmark): remove arrow filter

- core/scss/components/top-bar/top-bar.scss
> fix(top-bar): make avatar topbar styling more specific

- react/src/lib/MenuItem/index.js
- react/src/lib/SubMenu/index.js
> MenuItem/Submenu Props

- angularjs/src/lib/components/select/examples/kitchen-sink.component.ts
- angularjs/src/lib/components/select/select.component.ts
- angularjs/src/lib/directives/dropdown/dropdown.directive.ts
- core/scss/components/input/mixins.scss
Error styling was applying to filter input instead of just the select input.
**After**:
> fix(select): apply error styling to first input

- angular/src/lib/select/examples/select-custom-content.component.ts
- angular/src/lib/select/examples/select-default.component.ts
- angular/src/lib/select/select.component.ts
- Set scroll to active item when select overlay is open
- Able to pass in ngModel value to appear on page load selected placeholder
- Active item background color will go back to the selected Value if backdrop clicked
**After**:
> fix(select): set scroll to active item when overlay is opened

- .gitignore
- angular/src/docs/app/app-routing.module.ts
- angular/src/docs/app/kitchen-sink/kitchen-sink.component.ts
- angular/src/lib/ng-package.json
- angular/src/lib/select/examples/index.ts
- angular/src/lib/select/examples/select-forms.component.ts
- angular/src/lib/select/select.component.ts
- angular/src/lib/select/tests/select.component.spec.ts
- angular/tslint.json
- yarn.lock
Used with a formControl group, patchValue and setValue were not reflecting new values in the UI.  The root cause was using the `===` operator to compare objects (always returns false).  This was replaced with the lodash `isEqual` method which is functional when comparing objects.  The change was to `writeValue` and the underlying `find/selectUpdatedItem` methods.  I consolidated the functionality for pressing `enter` with an item selected, with that of `writeValue` as well.
Additionally, I added the select-forms.component to the kitchen sink as a route and added some additional controls that could be used to manually test the component in action.
Lastly, when I ran the project it install, it updated the yarn.lock file, so that's in there as well.
**After**:
> fix(select): writeValue working for formControl

- angular/src/lib/input/input.directive.ts
https://jira-eng-sjc10.cisco.com/jira/browse/PROVISION-5760
css prop not adding to text-area fix
**After**:
> fix(input): css prop class gets added to existing classes

- angularjs/src/lib/components/select/select.component.ts
- angularjs/src/lib/directives/dropdown/dropdown.directive.ts
> fix(select): angularjs fix spaces in filter and keyboard

- angularjs/src/lib/components/select/select.component.html
- angularjs/src/lib/components/select/select.component.ts
- angularjs/src/lib/directives/dropdown/dropdown.directive.ts
fix key navigation on nested selects
**After**:
> fix(select): angularjs when multiple selects warnings show

- angular/src/lib/select/select.component.ts
emitter now uses this._selection in toggleRowWithCheckbox
PROVISION-5776
**After**:
> fix(select): use _selection for emitter instead of selection

- angular/src/lib/combo-box/combo-box.component.ts
- angular/src/lib/combo-box/examples/default.component.ts
> feat(combo-box): add emitter on input change

- angular/src/lib/menu/menu.component.ts
Need scroll on long list menu
- without Overflow (cannot scroll down to menu)
- with Overflow (can scroll down to menu)
**After**:
> fix(anuglar): overflow on long list menu

- angular/src/lib/input-container/input-container.component.ts
> fix(input-container): add handleClear emitter

- angular/src/lib/combo-box/combo-box.component.ts
- angular/src/lib/combo-box/combo-box.module.ts
- angular/src/lib/combo-box/examples/errors.component.ts
- angular/src/lib/combo-box/examples/examples.module.ts
- angular/src/lib/combo-box/examples/index.ts
- angular/src/lib/data-table/index.ts
- core/scss/components/input/input.scss
Add example to show error message form validators for combo-box
**After**:
> feat(combo-box): add error messages

- core/scss/components/input-phone-number/input-phone-number.scss
> fix(core): Phone number input has extra padding

- angular/src/lib/combo-box/combo-box.component.ts
> fix(ComboBox): options do not update on some cases

- angular/src/lib/combo-box/combo-box.component.ts
> fix(ComboBox): watch options change

- commitlint.config.js
- package.json
- yarn.lock
Adds commitlint to commit messages.
**After**:
> chore: add commitlint

- angular/src/lib/combo-box/combo-box.component.ts
> feat(ComboBox): add scrollHeight

- angular/src/lib/select/examples/select-default.component.ts
- angular/src/lib/select/select.component.ts
> feat(select): add disabled state to select item

- angular/src/lib/menu/menu-trigger.directive.ts
- core/scss/components/coachmark/coachmark.scss
- core/scss/components/overlay/event-overlay.scss
- core/scss/components/tooltip/tooltip.scss
Add another arrow on `::after` for the menu's arrow, so it can overlap with main element, this way creates the border effect without overlapping the items.
https://github.com/momentum-design/momentum-ui/issues/571
Update menu's arrow structure to not overlap menu's items.
Since the changes were made on core and targets only styling, I tested the arrow from all directions in the playground.
**After**:
> style(event-overlay): update overlay arrow

- angular/src/lib/date-picker/date-picker-day.component.ts
- angular/src/lib/date-picker/date-picker.component.ts
- angular/src/lib/date-picker/date-picker.service.ts
- angular/src/lib/date-picker/examples/default.component.ts
**After**:
- [ x] Bug fix (non-breaking change which fixes an issue)
> fix(date-picker):fix @input

- angular/src/lib/menu/examples/default.component.ts
- angular/src/lib/menu/menu-item.component.ts
- angular/src/lib/menu/menu-trigger.directive.ts
Add disabled property as input to menu item, to disable click on menu
items and inherit style from list item since menu items use list items.
[583](https://github.com/momentum-design/momentum-ui/issues/583)
Trying to dynamically disable the menu's items was not possible without adding local changes.
Those changes affect only the Angular library, so I tested only the Angular menu.
- yarn build, as per contributing guide
- manual tested to inherit the disabled style from list item
- manual tested to not be able to click a disabled item
- manual tested to not be able to focus with keyboard or mouse a disabled item
- manual tested to not be able to open a submenu if the item is disabled
**After**:
> feat(menu): add disabled state for menu item

- react/src/lib/DeviceListCall/tests/__snapshots__/index.spec.js.snap
- react/src/lib/List/index.js
- react/src/lib/List/tests/__snapshots__/index.spec.js.snap
- react/src/lib/List/tests/index.spec.js
- react/src/lib/ListItem/index.js
- react/src/lib/Menu/index.js
- react/src/lib/SidebarNav/tests/__snapshots__/index.spec.js.snap
- react/src/lib/TopbarNav/tests/__snapshots__/index.spec.js.snap
Some of the accessibility specifications require removal of `aria-current` tag in lists.
This tag is displayed on the currently focused `<ListItem>`'s.
For this, I am suggesting an `ariaConfig` prop which may contain a JSON value for tweaking accessibility properties. 
Here:   
``` 
const ariaConfiguration = {disableAriaCurrent : true};
<List ariaConfig={ariaConfiguration }> 
```
Can be used to stop the population of `aria-current = true` tag.
**TODOs**
- Write tests
- Update Snapshots
**After**:
> feat(accessibility): optionally disable aria-current tag

- package.json
- utils/package.json
Make @momentum-ui/tokens a dependency, not a dev-dependency
This will ensure that getColorValue can find the colors.json within the tokens library.
React doesn't start up correctly without this. Same goes for Web-components
**After**:
> fix(utils): add tokens dependency & build:tokens in bootstrap script

- utils/src/index.js
> fix(utils): alpha utils/src/index.js

- react/src/lib/Modal/index.js
clear timeout on hide
Memory leak and address a warning from React when we setState on an unmounted component.
> fix(modal): clear hide timeout onclose

- tokens/src/core/button.js
> fix(tokens): fix the secondary text color and add few more color tokens

- tokens/src/core/button.js
- tokens/src/core/colors.js
> feat(tokens): adding token variable names to color's token JS object

- tokens/src/core/badge.js
- tokens/tools/tokens-build.js
> feat(tokens): new badge tokens for light/dark mode

- web-components/README.md
adding Web Component folder
**After**:
> adding readme

- www/client/components/App.js
- www/client/components2020/AppFooter/AppFooter.scss
- www/client/components2020/AppFooter/index.js
- www/client/components2020/AppHeader/AppHeader.scss
- www/client/components2020/AppHeader/index.js
- www/client/containers2020/Color/index.js
- www/client/containers2020/ComponentOverview/index.js
- www/client/containers2020/Elevation/index.js
- www/client/containers2020/Icons/index.js
- www/client/containers2020/Personality/index.js
- www/client/containers2020/Personality/locale.js
- www/client/containers2020/SideNav/SideNav.scss
- www/client/containers2020/SideNav/index.js
- www/client/containers2020/Space/index.js
- www/client/containers2020/System/index.js
- www/client/containers2020/Typography/index.js
> Fix image paths, make menu and footer responsive

- web-components/package.json
- web-components/src/[sandbox]/examples/menu-overlay.ts
- web-components/src/[sandbox]/examples/modal.ts
- web-components/src/[sandbox]/examples/tabs.ts
- web-components/src/[sandbox]/sandbox.ts
- web-components/src/components/checkbox/Checkbox.ts
- web-components/src/components/floating-modal/FloatingModal.ts
- web-components/src/components/input/Input.ts
- web-components/src/components/menu-overlay/MenuOverlay.test.ts
- web-components/src/components/menu-overlay/MenuOverlay.ts
- web-components/src/components/modal/Modal.test.ts
- web-components/src/components/modal/Modal.ts
- web-components/src/components/radio/Radio.ts
- web-components/src/components/radio/tokens/md-radio-tokens.js
- web-components/src/components/slider/Slider.stories.ts
- web-components/src/components/slider/Slider.ts
- web-components/src/components/slider/scss/slider.scss
- web-components/src/components/slider/tokens/lm-slider-token.js
- web-components/src/components/tabs/Tab.ts
- web-components/src/components/tabs/Tabs.test.ts
- web-components/src/components/tabs/Tabs.ts
- web-components/src/mixins/FocusMixin.test.ts
- web-components/src/mixins/FocusMixin.ts
- web-components/src/mixins/FocusTrapMixin.test.ts
- web-components/src/mixins/FocusTrapMixin.ts
This change is bringing in the latest from internal WC momentum ui 
**After**:
> Bringing in the latest from internal momentum - one last time

- .circleci/config.yml
> Updating docker image for cypress

- www/client/components/App.js
- www/client/components2020/AppFooter/AppFooter.scss
- www/client/components2020/AppFooter/index.js
- www/client/components2020/NotFound/NotFound.scss
- www/client/components2020/NotFound/index.js
- www/client/containers2020/Component/Component.scss
- www/client/containers2020/Component/index.js
- www/client/containers2020/Routes/RouteContainer.js
- www/client/containers2020/Routes/index.js
- www/client/styles/styles2020.scss
- www/package.json
Update 404 page, momentum-ui core version,  and the component not found page copy
> Site updates

- web-components/src/components/tabs/Tab.ts
- web-components/src/components/tabs/Tabs.ts
Support Shift + Tab keydown to focus back from More tab to last visible tab
**After**:
> manro/Support Shift + Tab keydown to focus back from More tab to last visible tab

- web-components/src/components/editable-textfield/scss/editable-textfield.scss
Update cursor for editable textfield while disabled.
**After**:
> fix(Editable-textfield): Update disabled editable textfield cursor

- web-components/src/[sandbox]/examples/chat-message.ts
- web-components/src/[sandbox]/examples/index.ts
- web-components/src/[sandbox]/sandbox.ts
- web-components/src/components/chat-message/ChatMessage.stories.ts
- web-components/src/components/chat-message/ChatMessage.test.ts
- web-components/src/components/chat-message/ChatMessage.ts
- web-components/src/components/chat-message/scss/chat-message.scss
- web-components/src/components/chat-message/scss/mixins.scss
- web-components/src/components/chat-message/scss/module.scss
- web-components/src/components/chat-message/scss/settings.scss
- web-components/src/components/chat-message/tokens/lm-chat-message-tokens.js
- web-components/src/components/chat-message/tokens/md-chat-message-tokens.js
> feat(chat message): create chat message component

- web-components/src/components/alert/Alert.ts
- web-components/src/components/list/ListItem.ts
Remove aria-hidden from listItem. This way, scree reader can read the content inside.
Pairs with a wc-based PR:
CBABU/agentx-mfe-wc-based#328
removing `aria-hidden` so the screen can read inside content
https://jira-eng-sjc12.cisco.com/jira/browse/CAX-766
Improve accessibility - screen reading
**After**:
> fix(ListItem): remove aria-hidden and add roles to alert text [CAX-766]

- web-components/src/components/tabs/scss/tab.scss
> fix(tab): fix background for disabled tab

- web-components/src/components/editable-textfield/scss/editable-textfield.scss
Remove an unnecessary flexbox setting that was causing visual bug in Firefox. 
RE: https://jira-eng-sjc12.cisco.com/jira/browse/CAX-803
**After**:
> fix(Editable Textfield): remove flexbox settings

- web-components/src/components/slider/scss/settings.scss
- web-components/src/components/slider/scss/slider.scss
- web-components/src/components/toggle-switch/scss/toggle-switch.scss
> fix(components): bugfix high contrast

- web-components/src/[sandbox]/examples/menu-overlay.ts
- web-components/src/components/theme/Theme.test.ts
- web-components/src/components/theme/Theme.ts
- web-components/src/components/tooltip/Tooltip.test.ts
- web-components/src/components/tooltip/Tooltip.ts
- web-components/src/components/tooltip/scss/tooltip.scss
The popper now initially visible in case when parent boundary element has overflow: hidden
Due to the Popper [limitation](https://github.com/popperjs/popper-core/issues/112) it will be cut off at the limits of the innermost element with overflow: hidden; To resolve this issue, Popper.js instance need to be setting up in the md-theme, because this element guarantee will not contain overflow property with hidden value.
Before this fix, Popper cut off when target element is inside element with overflow: hidden
Manually, UI tests
**After**:
> fix(tooltip): tooltip will be cut off at the limits of the innermost element with hidden overflow

- web-components/src/components/menu-overlay/MenuOverlay.ts
- web-components/src/components/tabs/scss/settings.scss
- web-components/src/components/tabs/scss/tabs.scss
- yarn.lock
> feat(component): fixed indent for tabs according task CAX-806

- web-components/src/[sandbox]/examples/floating.ts
- web-components/src/[sandbox]/examples/table.ts
- web-components/src/components/floating-modal/FloatingModal.ts
- web-components/src/components/floating-modal/scss/floating.scss
- web-components/src/components/table/Table.ts
- web-components/src/components/table/scss/table.scss
- web-components/src/components/table/tokens/lm-table-tokens.js
- web-components/src/components/table/tokens/md-table-tokens.js
> feat(Component): Small fixes for responsive table and modal - CAX-815

- web-components/src/components/tooltip/scss/tooltip.scss
> fix(tooltip): fixed tooltip display - (CAX-833)

- web-components/src/components/modal/Modal.test.ts
- web-components/src/components/modal/Modal.ts
> fix(components): fixed close/open modal function - CAX-829

- .circleci/config.yml
- package.json
- web-components/package.json
> Adding UTs to WC CI

- web-components/src/components/tooltip/scss/tooltip.scss
> fix(tooltip): fixed inline flex for tooltip component (CAX-848)

- react/src/lib/Tooltip/index.js
> fix(tooltip): convert tooltip prop type from string to object

- www/client/containers2020/Home/home.scss
- www/client/containers2020/SideNav/index.js
> refactor(www): fix mobile header links, force personality home bg color

- web-components/src/[sandbox]/examples/combobox.ts
- web-components/src/[sandbox]/examples/slider.ts
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/slider/Slider.stories.ts
- web-components/src/components/slider/Slider.ts
- web-components/src/components/slider/scss/settings.scss
- web-components/src/components/slider/scss/slider.scss
Small modifications to Slider and Combobox Components
I was reached out for a few requests, I added:
- hideValue property to slider component.
- noClearIcon property to combobox (more like a select component)
- noticed slider wasn't truly disabled: now tabIndex is -1 and can't adjust slider.
**After**:
> feat(slider, combobox): slider hideValue, combobox noClearIcon

- web-components/src/[sandbox]/examples/floating-modal.ts
- web-components/src/components/floating-modal/FloatingModal.ts
Fix bug related to floating modal repositioning
During floating modal collapse/expand change, transform should be calculated related to previous modal position
**After**:
> fix(floating-modal): fix bug with modal repositioning

- web-components/src/[sandbox]/examples/floating-modal.ts
- web-components/src/components/floating-modal/FloatingModal.ts
Fix issue with floating modal expand/collapse position
> fix(floating-modal): fix floating modal expand/collapse position

- web-components/src/[sandbox]/examples/badge.ts
- web-components/src/[sandbox]/examples/chip.ts
- web-components/src/components/badge/scss/badge.scss
- web-components/src/components/badge/tokens/lm-badge-tokens.js
- web-components/src/components/badge/tokens/md-badge-tokens.js
- web-components/src/components/chip/scss/chip.scss
**After**:
- [x My code follows the code style of this project.
> CAX-865 - Add new color to badge and chips component

- web-components/src/components/link/Link.ts
This adds part="link" to the <md-link> component for more styling access.
**After**:
> feat(link): add part to md-link

- web-components/src/components/floating-modal/FloatingModal.ts
Fix position of floating-modal that was applied outside.
> fix(floating-modal): fix start position

- web-components/src/components/combobox/ComboBox.ts
I added conditions so that logic for multi select comboboxes only happen when the `isMulti` property is true.
Now for single select comboboxes, the performance is faster when you clear the selection (especially if there are a lot of options).
While working on a custom widget, I realized that when you press the clear button in combobox, it can take a really long time. I looked into it and realized that for even a single select combobox, it is filtering through every single option and unchecking it. This is unnecessary for single select.
- I added if statement to make sure the combobox has the property `isMulti`, for multi-select type logic.
**After**:
> fix(combobox): improve performance for non-multi select

- web-components/src/components/label/Label.ts
- web-components/src/components/label/scss/label.scss
- web-components/src/components/label/scss/mixins.scss
- web-components/src/components/label/scss/module.scss
- web-components/src/components/label/scss/settings.scss
Fix component according to [Requirements](https://jira-eng-sjc12.cisco.com/jira/browse/CAX-883)
**After**:
> fix(secondary label): fix secondary label position

- web-components/src/[sandbox]/examples/date-time-picker.ts
- web-components/src/[sandbox]/examples/datepicker.ts
- web-components/src/components/date-time-picker/DateTimePicker.stories.ts
- web-components/src/components/date-time-picker/DateTimePicker.ts
- web-components/src/components/datepicker/DatePicker.stories.ts
- web-components/src/components/datepicker/DatePicker.ts
Adds `disabled` attribute to DatePicker and DateTimePicker
Added attribute, pass-through attributes, Sandbox examples and Storybook examples
RE: https://jira-eng-sjc12.cisco.com/jira/browse/CAX-888
**After**:
> feat(datepicker): add disabled attribute

- web-components/src/[sandbox]/examples/form.ts
- web-components/src/components/combobox/ComboBox.stories.ts
- web-components/src/components/form/Form.stories.ts
- web-components/src/components/form/Form.test.ts
- web-components/src/components/form/Form.ts
- web-components/src/index.ts
- web-components/src/mixins/CustomElementCheck.ts
- web-components/src/mixins/index.ts
- web-components/webpack.config.ts
Form sandbox and storybook documents improvement.
> refactor(form): update form

- web-components/src/components/favorite/Favorite.ts
- web-components/webpack.config.ts
> fix(favorite): fix component declaration

- web-components/src/wc_scss/themes/global--dark.scss
- web-components/src/wc_scss/themes/global--light.scss
added another secondary background color to match the latest design.
Also, swapping secondary-bg-color with secondary-one-bg-color so we don't have a breaking change. 
**After**:
> global background colors update

- web-components/package.json
- web-components/src/[sandbox]/examples/button.ts
- web-components/src/components/button/Button.test.ts
- web-components/src/components/button/scss/button.scss
- web-components/src/components/button/scss/mixins.scss
- web-components/src/components/button/scss/settings.scss
> Outline button style for all color schemes

- web-components/src/components/table-advanced/scss/settings.scss
- web-components/src/components/table-advanced/scss/table-advanced.scss
**After**:
- [ x] Bug fix (non-breaking change which fixes an issue)
> fix(table-advanced): update styles for filter icon in firefox

- web-components/src/components/dropdown/Dropdown.stories.ts
> fix: dropdown storybook

- web-components/src/components/table-advanced/TableAdvanced.ts
- web-components/src/components/table-advanced/scss/table-advanced.scss
> fix(table-advanced): fix sorting button in header

- web-components/src/[sandbox]/sandbox.ts
- web-components/src/components/table-advanced/TableAdvanced.mdx
Provide additional documentation to Advance Table
> docs(table-advance): provide additional documentation

- web-components/src/[sandbox]/examples/combobox.ts
- web-components/src/[sandbox]/sandbox.mock.ts
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/combobox/scss/combobox.scss
<For Jira tasks:
https://jira-eng-sjc12.cisco.com/jira/browse/CAX-919
https://jira-eng-sjc12.cisco.com/jira/browse/CAX-920
>
**After**:
> fix(combobox): add text overflow for placeholder and options

- web-components/src/components/table-advanced/TableAdvanced.ts
- web-components/src/components/table-advanced/scss/settings.scss
- web-components/src/components/table-advanced/scss/table-advanced.scss
Resolving tasks:
https://jira-eng-sjc12.cisco.com/jira/browse/CAX-924
https://jira-eng-sjc12.cisco.com/jira/browse/CAX-923
**After**:
> fix(table-advanced): fix text color, add title attribute

- web-components/src/[sandbox]/examples/menu-overlay.ts
- web-components/src/components/input/Input.test.ts
- web-components/src/components/input/Input.ts
- web-components/src/components/input/scss/input.scss
- web-components/src/components/modal/Modal.test.ts
- web-components/src/components/modal/Modal.ts
- web-components/src/mixins/FocusTrapMixin.ts
Close multiple issues that related to md-input component
1. Two tabs are required to navigate to cross button inside input field when some search text is present-this is intermittent, sometimes it is not even going to cross button, directly going to list.
2. Pressing space on clear button, clears the text field and adds an extra space to the input due to which the list again gets filtered with space, although it should show unfiltered list with empty search text.
3. Long text in search field crosses over the cross button.
Fix wrong design and development implementation
1. Manually
2. Unit Tests
**After**:
> fix(input): prevent default action on input close button

- web-components/src/[sandbox]/examples/modal.ts
- web-components/src/components/button/scss/button.scss
Refactor example to provide more descriptive usage
In case when some components part rendered dynamically, FocusTrapMixin should recalculate all focusable elements. And its important to mark, that "focus-visible" event should be dispatching from potentially [focusable element](https://allyjs.io/data-tables/focusable.html).
> docs(input): provide more descriptive example

- web-components/src/components/button/Button.mdx
- web-components/src/components/button/Button.stories.ts
- web-components/src/components/button/README.md
Adding Button README, storybook doc .mdx file, and storybook cleanup.
**After**:
> docs(web-components): button readme, storybook docs and improvements

- web-components/src/wc_scss/themes/global--dark.scss
- web-components/src/wc_scss/themes/global--light.scss
> feat(web): two new color token pairs - tab-nav

- web-components/src/[sandbox]/examples/combobox.ts
- web-components/src/components/combobox/scss/combobox.scss
- web-components/src/components/combobox/scss/settings.scss
> Updates for combobox

- web-components/package.json
- web-components/webpack.config.ts
remove the chance of jsonpFunction and chunk collisions with other webpack bundles.
**After**:
> feat(web): webpack build for widgets w/ common

- web-components/package.json
- web-components/src/components/badge/scss/badge.scss
Safari gives the `::slotted()` selector a different weight than other browsers, and this causes the Icons within badges style to fail. This simply adds a, `!important` flag to nudge specificity up and correct the styling bug.
**After**:
> fix(badge): badge with icon style safari

- web-components/src/components/table-advanced/TableAdvanced.test.ts
- web-components/src/components/table-advanced/TableAdvanced.ts
Advance table component was missing updated function due to which if new data was sent to the component, the component was not rendering it.
**After**:
> #CAX-935: Putting updated method in advance table component

- web-components/src/[sandbox]/examples/dropdown.ts
- web-components/src/[sandbox]/sandbox.scss
- web-components/src/components/dropdown/Dropdown.ts
> fix(dropdown): added part selector for dropdown header

- web-components/package.json
- web-components/src/components/menu-overlay/MenuOverlay.ts
Bump to latest the versions used of Core, Icons, Tokens and Utils
**After**:
> chore(web-components): update peer dependencies

- react/src/lib/ContentItem/examples/Size.js
> test(content item): replace dead image link

- illustrations/svg/misc/illustration-search.svg
> feat(illustrations): add misc/illustration-search.svg

- icons/tools/icons-build.js
> fix(icons): resize icons when generating font file to render better

- web-components/package.json
the lit scss loader released a new version which is causing builds to fail. Pin the version to what it was before to avoid this
**After**:
> fix(webcomponents): fix scss loader

- animations/package.json
- illustrations/package.json
> build: fix publish for animations and illustrations

- icons-rebrand/package.json
- icons/package.json
- tools/icons/replaceURLs.js
> fix(build): fix replaceURLs script

- core/scss/components/alert-banner/alert-banner.scss
Add theming to close alert button inside banner.
> fix(banner): add close btn color theming

- tools/icons/replaceURLs.js
> Fix icons replaceurls

- core/scss/components/alert-banner/alert-banner.scss
Theming changes for alert-banner
> feat(theming): add theming to alert-banner

- icons-rebrand/templates/MomentumIconType.swift.hbs
> fix(icons): remove extra { in MomentumIconType.swift for icons-rebrand

- web-components/src/components/combobox/ComboBox.ts
Adding check for the condition when no custom options are coming.
[CAX-1100: Custom options for combobox not working after clearing options](https://jira-eng-sjc12.cisco.com/jira/browse/CAX-1100)
[CAX-1100: Custom options for combobox not working after clearing options](https://jira-eng-sjc12.cisco.com/jira/browse/CAX-1100)
**After**:
> fix(md-combobox): empty options array if no custom content is passed

- illustrations/svg/journey-start-320-cobalt-lime.svg
> feat(illustrations): add illustrations

- icons-rebrand/svg/generic-device-video-filled.svg
- icons-rebrand/svg/phone-filled.svg
filled versions for:
generic-device-video
phone
**After**:
> feat(icon): add new icons

- tools/icons/uploadSvgs.js
> fix(icons): fix upload script to correctly use environment variables

- web-components/package.json
> momentum-ui/core: 19.15.8

- react/src/lib/Icon/index.js
- tools/icons/generators.js
- tools/icons/icons-build.js
> build(icons): couple more fixes for changing file names

- react/src/lib/Breadcrumbs/examples/Default.js
- react/src/lib/Breadcrumbs/index.js
> feat(react): update to update package.json

- web-components/package.json
- web-components/src/components/tabs/TabPanel.ts
> added focusablePanel attribute

- web-components/src/components/editable-textfield/scss/editable-textfield.scss
> Editable Textfield disabled color fix

- icons-rebrand/svg/active-presence-small-filled.svg
active-presence-small-filled.svg
Icon is needed for right to left scenario as the current one is causing issues
**After**:
> Special case icon for RTL

- web-components/src/components/tabs/scss/tabs.scss
> Added Overflow x hidden for more dropdown box

- web-components/package.json
> chore(web-components): version bump to 2.5.4

- react/src/lib/Accordion/index.js
- react/src/lib/Accordion/tests/__snapshots__/index.spec.js.snap
Added a prop called initialActiveFocus that will allow a user to turn off the focusing that happens when initialActive opens accordions on load. 
In the project I'm working on its forcing the page to load 2/3 of the way down which is an awful user experience. Currently its being "fixed" by a timeout but that's not ideal so I'd like to make this an option. 
building the project and making sure it doesn't fail any tests.
> feat: added prop to Accordion to conditionally disallow focusing on initialActive

- react/src/lib/Accordion/index.js
- react/src/lib/Accordion/tests/__snapshots__/index.spec.js.snap
Updating to allow previously added property to not let the component focus when it mounts. 
In the project I'm working on its forcing the page to load 2/3 of the way down which is an awful user experience. Currently its being "fixed" by a timeout but that's not ideal so I'd like to make this an option. 
building the project and making sure it doesn't fail any tests.
> feat: updated Accordion component so focus on mount is optional

- web-components/src/components/phone-input/PhoneInput.test.ts
- web-components/src/components/phone-input/PhoneInput.ts
> fix(cx-8151): not showing error on empty text box

- web-components/src/components/checkbox/scss/checkbox.scss
> CX-8236 : Checbox text centrally aligned across all brosers

- web-components/src/components/menu-overlay/MenuOverlay.ts
> 8250: agent wrap up drop down value is not displayed on minimise window.

- web-components/package.json
> version upgrade

- web-components/package.json
> Updated Package

- web-components/package.json
- web-components/src/components/button/scss/button.scss
- web-components/src/components/button/tokens/lm-button-tokens.js
- web-components/src/components/modal/scss/mixins.scss
- web-components/src/components/modal/scss/modal.scss
#CX-8495 : Incorrect colour of info icon in station login and in profile settings in dark mode
**After**:
> #CX-8495 : Incorrect colour of info icon in station login and in profile settings in dark mode

- web-components/package.json
> Web component version upgrade

- web-components/package.json
> #CX-8537 : version changes

- web-components/src/[sandbox]/examples/toggle-switch.ts
- web-components/src/components/label/scss/label.scss
- web-components/src/components/toggle-switch/ToggleSwitch.stories.ts
- web-components/src/components/toggle-switch/ToggleSwitch.test.ts
- web-components/src/components/toggle-switch/ToggleSwitch.ts
- web-components/src/components/toggle-switch/scss/toggle-switch.scss
This PR includes:
- Fix for Label alignment ( left / right ) for Toggle Switch.
- Fix for Label and switch vertical alignment center. ( currently its not center aligned )
**After**:
> Add Label alignment for Toggle Switch

- .circleci/config.yml
- package.json
- web-components/package.json
> refactor: remove node-downloader to fix pipeline

- README.md
> refactor: added file change to trigger

- web-components/package.json
- web-components/src/components/combobox/ComboBox.ts
> fix for update issue in Combobox input

- web-components/package.json
> version update

- web-components/package.json
- web-components/src/components/avatar/scss/settings.scss
> Added Avatar Idle Ring

- web-components/src/components/combobox/ComboBox.test.ts
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/dropdown/scss/dropdown.scss
1. Increase the z-index value to "99" for md-combox and md-dropdown.
2. Multi-select Combobox title issue fixed.
**After**:
> md-dropdown,md-combobox: Improve the z-index and fix the input field title value

- web-components/package.json
> Removed Caret From country-codes-list

- web-components/src/components/combobox/ComboBox.test.ts
- web-components/src/components/combobox/ComboBox.ts
> Removed focus from chevron icon and added action on space bar key press

- web-components/package.json
- web-components/src/utils/dateUtils.ts
> #CX-9856 : Date Range Picker 'next month' arrow is not working

- web-components/src/components/combobox/scss/combobox.scss
- web-components/src/components/tabs/Tabs.ts
Fixing multiple scroll while virtual scrolling
**After**:
> #CX-9873 : Agent Desktop became unresponsive

- web-components/package.json
- web-components/src/components/combobox/ComboBox.ts
> #CX-9935 : ESD-Homepage for default layout we see the tick mark visible in dark mode .

- web-components/package.json
- web-components/src/components/radio/RadioGroup.ts
> #CX-9965 :  First checked value not updating on checked property update

- web-components/package.json
- web-components/src/components/combobox/ComboBox.test.ts
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/radio/RadioGroup.ts
Change the height of lit virtualizer element
**After**:
> #CX-9987 : ESD - HomePage : Managed Teams Dropdown | not able to scroll to the last team in the list

- web-components/package.json
- web-components/src/components/combobox/scss/combobox.scss
The format earlier used not works everytime in firefox. Therefore using other format
**After**:
> #CX-9987 : Scrollbar issues in firefox

- web-components/package.json
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/combobox/scss/combobox.scss
Firefox does not support has() selector therefore removing it
**After**:
> #CX-9987 : Multiple scroll fix in firefox

- web-components/package.json
- web-components/src/components/menu-overlay/MenuOverlay.test.ts
- web-components/src/components/menu-overlay/MenuOverlay.ts
> Menu overlay Component : Prevent Keydown event if slot-element is md-input field 

- web-components/package.json
- web-components/src/[sandbox]/examples/combobox.ts
- web-components/src/[sandbox]/examples/modal.ts
- web-components/src/components/combobox/ComboBox.test.ts
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/combobox/scss/combobox.scss
- web-components/src/components/dropdown/Dropdown.ts
- web-components/src/components/phone-input/PhoneInput.ts
- web-components/src/components/tooltip/Tooltip.test.ts
- web-components/src/components/tooltip/Tooltip.ts
- web-components/src/mixins/FocusTrapMixin.test.ts
- web-components/src/mixins/FocusTrapMixin.ts
> #CX-9966: Accessibility issue fixes

- web-components/src/components/combobox/ComboBox.ts
- Trimming the space on input
- Toggle the combobox dropdown on space bar key press
**After**:
> md-combobox : Not getting the "combobox-input" callback event when the input value is empty

- web-components/package.json
- web-components/src/components/tabs/Tabs.stories.ts
- web-components/src/components/tabs/Tabs.ts
> Typo Fix for Tab property 

- utils/package.json
Fixes fast-glob vulnerability
Takes forward #1193
https://github.com/momentum-design/momentum-ui/issues/1162
While running yarn audit, it will throw a security vulnerability with Severity as high.
Not Tested
**After**:
> fix: fast-glob vulnerability

- react/src/lib/Footer/tests/index.spec.js
- react/src/lib/Sidebar/tests/index.spec.js
- react/src/lib/SidebarBody/tests/index.spec.js
- react/src/lib/SidebarFooter/tests/index.spec.js
- react/src/lib/SidebarHeader/tests/index.spec.js
- react/src/lib/SidebarNav/tests/index.spec.js
- react/src/lib/SidebarNavItem/tests/index.spec.js
- web-components/package.json
- web-components/src/[sandbox]/examples/card.ts
- web-components/src/components/card/Card.stories.ts
> #CX-9533 : Changes in momentum github repo

- web-components/package.json
- web-components/src/[sandbox]/examples/phone-input.ts
- web-components/src/components/phone-input/PhoneInput.ts
- web-components/src/components/radio/Radio.ts
> #CX-10642 : ESD Accessibility Issues -ADR 1.3.1 Info and Relationships	

- web-components/package.json
- web-components/src/components/radio/RadioGroup.test.ts
- web-components/src/components/radio/RadioGroup.ts
- web-components/src/components/radio/scss/radiogroup.scss
> #CX-11067 : Add disabled feature in radio group

- web-components/package.json
- web-components/src/components/combobox/ComboBox.test.ts
- web-components/src/components/combobox/ComboBox.ts
CX-11306
Added onKeyDown.ArrowLeft and onKeyDown.ArrowRight for Combobox.ts 
https://jira-eng-sjc12.cisco.com/jira/browse/CX-11306
In the Outdial Popover the cursor navigation of the using the left/right arrow keys propagates to the md-Tabs above 
Manually tested 
**After**:
> #CX-11306 : Navigation of cursor in combobox propagates to tab above

- web-components/src/[sandbox]/examples/audio-player.ts
- web-components/src/[sandbox]/examples/index.ts
- web-components/src/[sandbox]/examples/tooltip.ts
- web-components/src/[sandbox]/sandbox.ts
- web-components/src/components/accordion/Accordion.stories.ts
- web-components/src/components/alert-banner/AlertBanner.stories.ts
- web-components/src/components/audio-player/AudioPlayer.stories.ts
- web-components/src/components/audio-player/AudioPlayer.test.ts
- web-components/src/components/audio-player/AudioPlayer.ts
- web-components/src/components/audio-player/scss/audio-player.scss
- web-components/src/components/audio-player/scss/module.scss
- web-components/src/components/audio-player/scss/settings.scss
- web-components/src/components/audio-player/tokens/lm-audio-player-token.js
- web-components/src/components/audio-player/tokens/md-audio-player-token.js
- web-components/src/components/chat-message/ChatMessage.ts
- web-components/src/components/slider/Slider.stories.ts
- web-components/src/index.ts
- web-components/webpack.config.ts
Introduce Audio Player component as part of recording manager efforts
Added audioPlayer web component to momentum library, along with sandbox, testing, scss modules etc
https://jira-eng-sjc12.cisco.com/jira/browse/CX-11010
It is required for the recording manager feature in WXCC agent
Unit testing, manual testing
**After**:
> CX-11010: Introduce audio component

- web-components/package.json
> #CX-11373 : upgrade momentum wc version

- web-components/package.json
- web-components/src/components/alert-banner/AlertBanner.ts
- web-components/src/components/alert/Alert.ts
> #CX-11790 : Adding role=alert for md-banner-alert

- web-components/package.json
- web-components/src/components/alert/Alert.ts
> #CX-11806 : alert screen reader fix for desktop notification

- web-components/package.json
- web-components/src/mixins/FocusTrapMixin.ts
> #CX-11353 : Memory issue Fix

- web-components/package.json
- web-components/src/components/input/Input.ts
> #CX-12051 : In outdial, addressBook tab the cursor is not movable

- web-components/package.json
- web-components/src/components/input/Input.ts
> CX-12192 : Removal of event.stopPropogation from keydown event in Input component

- web-components/package.json
- web-components/src/components/menu-overlay/MenuOverlay.ts
- web-components/src/mixins/FocusTrapMixin.ts
> CX-12023 : Revert Trouble shooting Memeory leak PR

- web-components/package.json
Package.json version update for https://github.com/momentum-design/momentum-ui/pull/1482
**After**:
> fix: package version update for active tab color contrast issue

- web-components/package.json
- web-components/src/[sandbox]/examples/phone-input.ts
- web-components/src/components/phone-input/PhoneInput.test.ts
- web-components/src/components/phone-input/PhoneInput.ts
> CX-12698 : Strip when Phone number starts with selected Country Code

- icons-rebrand/svg/text-box-cursor-bold.svg
- icons-rebrand/svg/text-box-cursor-light.svg
Feature jira: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-450580
UX: https://www.figma.com/file/fz4puT8q3x4jQrBrxL8i9Y/Text-tool-for-annotation?type=design&node-id=1353-10412&mode=design&t=cuv5YnoF25ViDgxR-4
**After**:
> Add text tool feature icon: text-box-cursor-light and text-box-cursor-bold

- web-components/src/components/list/List.ts
- web-components/src/components/list/ListItem.ts
> #CX-12962: updated default role as listbox for List and option for ListItema

- web-components/src/components/modal/Modal.ts
- web-components/src/components/theme/Theme.ts
Adding a part attribute to the theme-wrapper div of md-theme component & adding part attribute to a div in Modal compoennt.
I need to to be able to add custom styling in my CJDS Widget instance for finesse. Currently, the widget is unable to fully expand with a height of 100%. The part attribute will allow me to do so in the finesse JDS widget implementation.
**After**:
> chore(theme): add part html tag to md-theme

- web-components/src/components/tabs/Tabs.ts
Updated the arai-controls and aria-labelledby properties of tab and tab panel
Continuation with PR: https://github.com/momentum-design/momentum-ui/pull/1536/files
Story: https://jira-eng-sjc12.cisco.com/jira/browse/CX-10177
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls
**After**:
https://github.com/momentum-design/momentum-ui/assets/41052645/8cbb9ea0-8ec9-4904-85ca-778997e025dd
> #CX-10177: fix: updated tab panel id to be unique

- web-components/src/components/phone-input/PhoneInput.ts
PhoneInput internally uses Input component which expects clearAriaLabel as optional parameter while PhoneInput doesn't have any parameter for it due to which we were not able to pass our localized label to it hence resulting in accessibility issue. We added clearArialabel as a parameter to PhoneInput and passed it to Input component.
**After**:
> fix: add property for clearAriaLabel in phoneInput

- web-components/.vscode/settings.json
- web-components/src/components/phone-input/PhoneInput.ts
We have added clearAriaLabel to our phoneInput component and passed it combobox element for getting the localized message or label from the target source.
**After**:
> fix: add property of clearAriaLabel in phoneInput for combobox

- web-components/src/components/combobox/ComboBox.ts
> Fix the keyboard selection on combobox when virtual-scroll is enabled

- web-components/package.json
- web-components/src/components/taskitem/TaskItem.ts
> #CX-12586 : GBM is handled on Agent Desktop

- web-components/src/components/modal/Modal.ts
CX-10282
Profile: Screen Readers: Visual headings are not implemented or announced as headings
Agent profile panel - Sign out button - Sign out confirmation dialog - Sign out confirmation text- Visual headings are not announced as headings.
Expected Result: Text elements that are styled as headings and function as headings should be announced as headings. The 'Sign out confirmation' heading in the Sign out confirmation dialog should be implemented and announced as a heading, so the screen reader user can understand its purpose and can navigate the page by headings.
- Screen reader should announce 'Sign out confirmation, Heading level 2'
Actual Result: The 'Sign out confirmation' is a visually appearing heading text but it is implemented and announced as plain text. …
> CX-10282:  Fix(accessibilty) -Screen Readers: Visual headings are not implemented or announced as headings

- web-components/src/[sandbox]/sandbox.mock.ts
- web-components/src/components/table-advanced/TableAdvanced.md
- web-components/src/components/table-advanced/TableAdvanced.mdx
- web-components/src/components/table-advanced/TableAdvanced.test.ts
- web-components/src/components/table-advanced/TableAdvanced.ts
sortable table button state announcement
done
**After**:
> #CX-10248: Sortable Table Button Announcement Fix

- web-components/package.json
- web-components/src/components/combobox/ComboBox.ts
> #CX-10432 : Removed aria-expanded from ComboBox clear-input button.

- web-components/package.json
- web-components/src/[sandbox]/examples/combobox.ts
- web-components/src/components/combobox/ComboBox.stories.ts
- web-components/src/components/combobox/ComboBox.test.ts
- web-components/src/components/combobox/ComboBox.ts
> #CX-10274: Passing List Items Count To The Parent Fix

- web-components/package.json
- web-components/src/components/toggle-switch/ToggleSwitch.ts
> #CX-10281:Added role switch to toggle switch

- web-components/package.json
- web-components/src/components/button/Button.ts
**After**:
Screenshots after fix 
VidCast Link - 
JAWS - https://app.vidcast.io/share/7ded7fbe-ddcf-4eda-8e65-34e6e9ae8963
https://app.vidcast.io/share/293a41e1-6370-4f7f-9472-6928a37daae3
> #CX-12138 : fix(accessibility): toggle buttons incorrectly announce as menu buttons

- web-components/package.json
- web-components/src/components/tabs/Tab.ts
> #CX-10499 : Updated ariaLabel property in Tab

- web-components/package.json
- web-components/src/components/combobox/ComboBox.test.ts
- web-components/src/components/tabs/Tab.ts
- web-components/src/components/tabs/Tabs.ts
> #CX-10499 : Updated Initial Tab Selected State

- web-components/src/components/modal/Modal.ts
> #CX-13382: passing ariaLabel to button element from md-modal

- web-components/package.json
> Upgraded Web component Version 2.9.6

- web-components/src/[sandbox]/examples/menu-overlay.ts
- web-components/src/[sandbox]/sandbox.scss
- web-components/src/components/menu-overlay/MenuOverlay.test.ts
- web-components/src/components/menu-overlay/MenuOverlay.ts
> #CX-14006 :  Supporting focus and accessibility for nested menu overlays

- web-components/package.json
- web-components/src/components/floating-modal/FloatingModal.ts
CX-13306
Vidcast Link - https://app.vidcast.io/share/a12d14db-9e4a-4a07-889f-808661221713
**After**:
> CX-13306 : fix(accessibility): updated ariaLabel for button

- web-components/package.json
- web-components/src/components/button/Button.ts
**After**:
Vidcast Link  Voiceover - https://app.vidcast.io/share/c4ae17a6-8c52-4f91-80a8-ba830b096e13
JAWS -  https://app.vidcast.io/share/0cd737c0-773d-46fd-952e-5c46489ed213
> CX-12138 : Toggle buttons incorrectly announce as menu buttons

- web-components/package.json
- web-components/src/components/tabs/scss/tabs.scss
https://jira-eng-sjc12.cisco.com/jira/browse/CX-14053
**After**:
> #CX:14053-Extra Padding found in Consult Request Modal, Dial Number

- web-components/package.json
> Upgraded Web Component Version to 2.9.9

- web-components/src/components/modal/Modal.ts
https://jira-eng-sjc12.cisco.com/jira/browse/CX-10562
**After**:
> #CX-10562 : dialog is not properly associated with the label and the text

- web-components/package.json
> Upgraded Web Component Version to 2.9.10

- web-components/package.json
> Upgraded Web Component Version to 2.9.11

- web-components/src/components/modal/Modal.ts
CX-10203 
**After**:
Vidcast - https://app.vidcast.io/share/5c705a08-46e8-45d6-a423-d84de553a3b3
> #CX-10203 - fix(accessibilty): updated aria-attributes in modal

- web-components/src/components/audio-player/scss/audio-player.scss
> #CX-14200:  audio seeker overlapping issue fix

- web-components/package.json
> Upgraded Web Component Version to 2.9.12

- web-components/package.json
- web-components/src/components/combobox/ComboBox.test.ts
- web-components/src/components/combobox/ComboBox.ts
> #CX-14188 : Combobox item getting deselected when reopening

- web-components/package.json
> Upgraded Momentum Web component Version to 2.9.14

- web-components/src/components/combobox/scss/combobox.scss
- web-components/src/components/combobox/tokens/lm-combobox-tokens.js
- web-components/src/components/combobox/tokens/md-combobox-tokens.js
> fix(cx-10454): Outdial Call: Color Contrast: Light grey placeholder text on white fails contrast

- web-components/src/[sandbox]/examples/table-advanced.ts
- web-components/src/components/table-advanced/TableAdvanced.ts
Added a property called "isRowFocusable" in the advanced table component, which when "true" will make the rows focusable via tab. If false, the rows will be skipped while tabbing.
**After**:
> #CX-10241 : Keyboard Shortcuts: Keyboard Navigation: Each row in table is tab focusable.

- web-components/src/components/taskitem/tokens/lm-taskitem-tokens.js
- web-components/src/components/taskitem/tokens/md-taskitem-tokens.js
> #CX-14786 : Added color css for popover timer.

- web-components/package.json
> 2.10.3 Web component Version

- web-components/src/components/dropdown/tokens/lm-dropdown-tokens.js
- web-components/src/components/dropdown/tokens/md-dropdown-tokens.js
Story - CX-13386
**After**:
Figma Link - 
https://www.figma.com/proto/Wffl1e8djqrhezli6n1kYU/Accessibility-for-Desktop?page-id=4007%3A85143&type=design&node-id=4007-85287&viewport=-203%2C287%2C0.07&t=qVqi2s0nvB08zOpx-1&scaling=scale-down-width&starting-point-node-id=4007%3A85533
> fix: added new color bg for md-dropdown (color contrast)

- web-components/src/[sandbox]/examples/date-time-picker.ts
- web-components/src/[sandbox]/examples/datepicker.ts
- web-components/src/[sandbox]/examples/editable-field.ts
- web-components/src/[sandbox]/examples/toggle-switch.ts
- web-components/src/components/date-time-picker/DateTimePicker.test.ts
- web-components/src/components/date-time-picker/DateTimePicker.ts
- web-components/src/components/editable-textfield/EditableTextfield.ts
CX-14781
**After**:
https://app.vidcast.io/share/2b64d53b-4a9d-497b-8cc2-63a31d664413
> Removed aria-label attribute and added examples for aria label

- web-components/src/components/combobox/scss/combobox.scss
> #CX-14849 : Checkbox contrast on high contrast mode

- web-components/src/components/tabs/tokens/lm-tabs-tokens.js
- web-components/src/components/tabs/tokens/md-tabs-tokens.js
**After**:
Figma Link: https://www.figma.com/design/Wffl1e8djqrhezli6n1kYU/Accessibility-for-Desktop?node-id=2-6&t=9yD51tp3ixNUiNEC-0
> CX-10593, CX-10594 : Fix for color contrast issue in selected tabs

- web-components/package.json
> 2.10.4 Version Upgrade Web component

- web-components/src/components/toggle-switch/tokens/lm-toggle-tokens.js
- web-components/src/components/toggle-switch/tokens/md-toggle-tokens.js
Updated the color code so as to pass the color contrast ratio
**After**:
> #CX-10257 : Profile: Color Contrast: Toggle buttons fail color contrast requirements.

- web-components/src/components/radio/tokens/lm-radio-tokens.js
- web-components/src/components/radio/tokens/md-radio-tokens.js
> #CX-10549 : Radio button border fails contrast requirements

- web-components/src/components/menu-overlay/MenuOverlay.ts
> #CX-14872 : Fix menu overlay focus on close

- web-components/src/components/menu-overlay/MenuOverlay.ts
- web-components/src/mixins/FocusTrapMixin.ts
CX-10262
**After**:
Vidcast link - https://app.vidcast.io/share/17c14fb0-e313-4da9-9af6-2541ee799ea3
> fix: focus is not contained in the profile modal

- web-components/src/components/input/scss/input.scss
- web-components/src/components/input/tokens/lm-input-tokens.js
- web-components/src/components/input/tokens/md-input-tokens.js
> #CX-10215 : fix-color contrast for placeholder input

- web-components/src/[sandbox]/examples/chip.ts
- web-components/src/components/chip/Chip.test.ts
- web-components/src/components/chip/Chip.ts
[CX-13316](https://jira-eng-sjc12.cisco.com/jira/browse/CX-13316)
**After**:
> fix: Added new tooltip text property

- web-components/src/components/modal/Modal.ts
> #CX-13430 :  modal title screen reader fix

- web-components/package.json
> Increased Webcomponent Version to 2.10.6

- web-components/src/components/icon/Icon.ts
- web-components/src/components/input/Input.ts
Implement the aria-hidden attribute on icon element
**After**:
> #CX-10244 : Implement the aria-hidden attribute on icon element

- web-components/package.json
- web-components/src/components/chip/Chip.ts
> Version Upgrade Web component 2.10.7

- web-components/src/components/tabs/Tab.ts
- web-components/src/components/tabs/Tabs.ts
> #CX-14005 : Performance statistics: Screen Readers: Incorrect role announced for More tabs button

- web-components/package.json
> Updated Web component version

- web-components/src/[sandbox]/examples/combobox.ts
- web-components/src/components/combobox/ComboBox.test.ts
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/combobox/scss/combobox.scss
> CX-14213 :  ESD: VoiceOver: Listboxes are not navigable using VoiceOver.

- web-components/package.json
> updated web component 2.10.9

- web-components/src/components/button/scss/button.scss
button should have only outline on focus - in high contrast mode
**After**:
> #cx-13373 : fix: (button should have only outline on focus - HC)

- web-components/src/components/checkbox/tokens/lm-checkbox-tokens.js
- web-components/src/components/checkbox/tokens/md-checkbox-tokens.js
- web-components/src/components/combobox/scss/combobox.scss
- web-components/src/components/combobox/scss/settings.scss
- web-components/src/components/combobox/tokens/lm-combobox-tokens.js
- web-components/src/components/combobox/tokens/md-combobox-tokens.js
- web-components/src/components/radio/tokens/lm-radio-tokens.js
- web-components/src/components/radio/tokens/md-radio-tokens.js
> #CX-14840 : Change the radio and checkbox border color for dark & light mode

- web-components/package.json
> Version Update to 2.10.10

- web-components/package.json
- web-components/src/components/tabs/Tabs.test.ts
- web-components/src/components/tabs/Tabs.ts
> CX-10399 : updated tab component to be focused on active tab

- web-components/src/components/taskitem/TaskItem.test.ts
- web-components/src/components/taskitem/TaskItem.ts
> #CX-14795: Made timer announcement with more context by adding hours, minutes and seconds if any timer text found

- web-components/src/components/list/List.ts
> #CX-14797 : Updated List.ts to update aria-label on label update.

- web-components/package.json
> Version Update to 2.10.11

- web-components/src/components/slider/scss/slider.scss
- web-components/src/components/slider/tokens/mdv2-slider-token.js
Add momentum V2 compatibility for slider
**After**:
> style: update slider for MDV2

- web-components/src/components/button-group/scss/button-group.scss
- web-components/src/components/button-group/scss/settings.scss
- web-components/src/components/button-group/tokens/mdv2-button-group-tokens.js
- web-components/src/components/button/tokens/mdv2-button-tokens.js
- web-components/src/components/favorite/scss/favorite.scss
Update component colors for mdv2
updated components:
favorite
button-group
**After**:
> Web components mdv2

- web-components/src/components/tabs/scss/tab.scss
- web-components/src/components/tabs/tokens/mdv2-tabs-tokens.js
> Set momentum V2 colours for tabs

- web-components/package.json
- web-components/src/[sandbox]/examples/button.ts
- web-components/src/[sandbox]/sandbox.ts
- web-components/src/components/button/Button.test.ts
- web-components/src/components/button/Button.ts
- web-components/src/components/button/scss/button.scss
- web-components/src/components/button/tokens/mdv2-button-tokens.js
- web-components/src/components/dropdown/scss/dropdown.scss
- web-components/src/components/dropdown/tokens/mdv2-dropdown-tokens.js
- web-components/src/components/modal/tokens/mdv2-modal-tokens.js
- web-components/src/components/pagination/tokens/mdv2-pagination-tokens.js
- web-components/src/components/taskitem/tokens/mdv2-taskitem-tokens.js
- web-components/src/utils/generateScssFromTokens.js
Update more components for mdv2
Buttons
Dropdown
[CX-15170](https://jira-eng-sjc12.cisco.com/jira/browse/CX-15170)
[CX-15179](https://jira-eng-sjc12.cisco.com/jira/browse/CX-15179)
> Web component mdv2 update 3

- web-components/src/[sandbox]/examples/alert-banner.ts
- web-components/src/[sandbox]/examples/alert.ts
- web-components/src/[sandbox]/examples/button.ts
- web-components/src/[sandbox]/examples/tooltip.ts
- web-components/src/[sandbox]/sandbox.scss
- web-components/src/components/chat-message/tokens/mdv2-chat-message-tokens.js
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/combobox/scss/combobox.scss
- web-components/src/components/combobox/tokens/md-combobox-tokens.js
- web-components/src/components/combobox/tokens/mdv2-combobox-tokens.js
- web-components/src/components/datepicker/datepicker-calendar/DatePickerCalendar.ts
- web-components/src/components/dropdown/Dropdown.test.ts
- web-components/src/components/menu-overlay/scss/menu-overlay.scss
- web-components/src/wc_scss/themes/global--mdv2.scss
Update combobox
Override global color tokens for MDV2
[CX-15169](https://jira-eng-sjc12.cisco.com/jira/browse/CX-15169)
> Mdv2 combobox

- web-components/src/[sandbox]/examples/alert.ts
- web-components/src/components/alert/Alert.test.ts
- web-components/src/components/alert/Alert.ts
- web-components/src/components/alert/scss/alert.scss
- web-components/src/components/alert/scss/settings.scss
- web-components/src/components/alert/tokens/mdv2-alert-tokens.js
- web-components/src/components/list/scss/listitem.scss
- web-components/src/components/list/tokens/mdv2-list-tokens.js
- web-components/src/wc_scss/themes/global--mdv2.scss
Update alert component
Add rounding for list items
> Alert update

- web-components/src/[sandbox]/examples/button.ts
- web-components/src/components/button/scss/button.scss
- web-components/src/components/button/scss/mixins.scss
- web-components/src/components/button/scss/settings.scss
- web-components/src/components/button/tokens/mdv2-button-tokens.js
Update button alignment so when font size is increased letters are not cut off
currently mdv2 button text is configured to match lumos but will be updated when all components are aligned to same size
> chore: fix button alignment issues

- web-components/src/components/tooltip/scss/tooltip.scss
- web-components/src/components/tooltip/tokens/mdv2-tooltip-tokens.js
> style: add momentum style to tooltips

- web-components/src/[sandbox]/examples/list.ts
- web-components/src/components/list/List.stories.ts
- web-components/src/components/list/List.ts
- web-components/src/components/list/ListItem.test.ts
- web-components/src/components/list/ListItem.ts
- web-components/src/components/list/scss/listitem.scss
Allow for list item shape configuration between pill and rounded in momentum design V2
> List item shape

- web-components/src/components/datepicker/scss/datepicker.scss
> style: fix hover contrast on datepicker

- web-components/package.json
- web-components/src/[sandbox]/examples/badge.ts
- web-components/src/[sandbox]/examples/date-time-picker.ts
- web-components/src/[sandbox]/examples/form.ts
- web-components/src/[sandbox]/examples/tabs.ts
- web-components/src/components/badge/Badge.ts
- web-components/src/components/badge/scss/badge.scss
- web-components/src/components/badge/tokens/lm-badge-tokens.js
- web-components/src/components/badge/tokens/md-badge-tokens.js
- web-components/src/components/badge/tokens/mdv2-badge-tokens.js
- web-components/src/components/datepicker/datepicker-calendar/DatePickerCalendar.test.ts
- web-components/src/components/tabs/Tabs.ts
- web-components/src/components/tabs/scss/tabs.scss
- web-components/src/components/timepicker/scss/settings.scss
- web-components/src/wc_scss/themes/global--mdv2.scss
- web-components/webpack.config.ts
* Add unread count badge
* Fix vertical tabs not working in Safari and Firefox
* Add missing unit tests for code coverage
> Unreadcount badge

- web-components/src/[sandbox]/examples/button.ts
- web-components/src/[sandbox]/sandbox.scss
- web-components/src/[sandbox]/sandbox.ts
- web-components/src/components/button/scss/button.scss
- web-components/src/components/progress-bar/ProgressBar.test.ts
- web-components/src/components/progress-bar/ProgressBar.ts
- web-components/src/wc_scss/themes/global--mdv2.scss
* Add missing test case to progressbar for code coverage
* Update sandbox to select container background colours based on css variables
> chore: add background color dropdown sandbox. Add tests

- web-components/src/components/date-time-picker/DateTimePicker.ts
- web-components/src/components/meeting-alert/MeetingAlert.test.ts
- web-components/src/components/meeting-alert/MeetingAlert.ts
- web-components/src/components/meeting-alert/scss/alert.scss
- web-components/src/components/meeting-alert/scss/settings.scss
- web-components/src/components/meeting-alert/tokens/lm-meeting-alert-tokens.js
- web-components/src/components/meeting-alert/tokens/md-meeting-alert-tokens.js
- web-components/src/components/meeting-alert/tokens/mdv2-meeting-alert-tokens.js
- web-components/src/components/radio/Radio.test.ts
* Add meeting alert tokens
* Add unit tests
**After**:
> chore: update for meeting alert

- core/package.json
- web-components/package.json
Update core package version and publish for Inter.var.woff2 font
**After**:
> chore: update core dependency

- web-components/src/components/avatar/scss/avatar.scss
- web-components/src/components/badge/scss/badge.scss
- web-components/src/components/button/scss/mixins.scss
- web-components/src/components/button/tokens/mdv2-button-tokens.js
- web-components/src/components/meeting-alert/scss/alert.scss
- web-components/src/components/tabs/scss/tabs.scss
* Updating font family gives different result to just updating font-weight
**After**:
> chore: update font family for components in mdv2

- web-components/src/[sandbox]/examples/button.ts
- web-components/src/components/avatar/scss/avatar.scss
- web-components/src/components/badge/scss/badge.scss
- web-components/src/components/button/Button.test.ts
- web-components/src/components/button/Button.ts
- web-components/src/components/button/scss/button.scss
- web-components/src/components/button/scss/mixins.scss
- web-components/src/components/button/tokens/lm-button-tokens.js
- web-components/src/components/button/tokens/mdv2-button-tokens.js
- web-components/src/components/tabs/scss/tabs.scss
- web-components/src/components/timepicker/TimePicker.ts
- web-components/src/components/timepicker/scss/settings.scss
- web-components/src/components/timepicker/scss/timepicker.scss
- web-components/src/wc_scss/themes/global--mdv2.scss
* Add isActive state to button. When toggled to is active some buttons will have a different normal hover active and disabled state
* add tab button style
**After**:
> Tab button

- web-components/src/wc_scss/typography/settings.scss
> refactor: fix warnings

- web-components/src/components/tabs/Tab.ts
- web-components/src/wc_scss/themes/global--dark.scss
- web-components/src/wc_scss/themes/global--light.scss
- web-components/src/wc_scss/themes/global--mdv2.scss
New colour tokens are needed so that momentum v2 can achieve a gradient style
**After**:
> Add new colour tokens to allow for gradient style in momentum v2 theme

- web-components/package.json
- web-components/src/[sandbox]/examples/button.ts
- web-components/src/components/button/scss/mixins.scss
* Allow button children to grow
**After**:
> Flex button stretch

- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/datepicker/DatePicker.ts
- web-components/src/components/menu-overlay/MenuOverlay.ts
- web-components/src/components/timepicker/TimePicker.ts
- web-components/src/components/timepicker/scss/settings.scss
- web-components/src/components/timepicker/scss/timepicker.scss
I set the AmPmComboBox as absolute to let the option box will popover outside container and I create an empty div in generateAmPmComboBox, set the width to AmPmComboBox width to ensure the justify content center will work perfect. Then using transform to translate the amPm combo box - width back to its position. 
The popover of am-pm-combo-box in date-time-picker not appear outside the date-time popover
Yarn build not show error.
**After**:
> fix(timepicker): resolve combobox display issue

- web-components/src/[sandbox]/examples/badge.ts
- web-components/src/components/button/scss/button.scss
- web-components/src/components/button/tokens/mdv2-button-tokens.js
Update engage state variant buttons
**After**:
> Button color updates

- core/scss/components/badge/module.scss
- core/scss/components/chip/module.scss
- core/scss/components/close-wrapper/module.scss
- core/scss/components/drawer/module.scss
- core/scss/components/link/module.scss
- core/scss/components/pagination/module.scss
- core/scss/components/panel/module.scss
- core/scss/components/stepper/module.scss
Fix errors in core css:build:components
**After**:
> fix: css:build:components errors

- web-components/package.json
- web-components/src/[sandbox]/examples/menu-overlay.ts
- web-components/src/components/alert/Alert.test.ts
- web-components/src/components/button-group/ButtonGroup.ts
- web-components/src/components/button/Button.test.ts
- web-components/src/components/coachmark/Coachmark.test.ts
- web-components/src/components/editable-textfield/EditableTextfield.test.ts
- web-components/src/components/icon/Icon.test.ts
- web-components/src/components/list/ListItem.test.ts
- web-components/src/components/menu-overlay/MenuOverlay.ts
- web-components/src/components/menu/Menu.test.ts
- web-components/src/components/radio/RadioGroup.ts
- web-components/src/components/table-advanced/TableAdvanced.test.ts
- web-components/src/components/table/Table.test.ts
- web-components/src/wc_scss/themes/global--dark.scss
- web-components/src/wc_scss/themes/global--light.scss
- web-components/src/wc_scss/themes/global--mdv2.scss
* Update stylelint
* Update tests check for class list. If we upgrade to lit 3 classmap adds extra whitespaces which will cause tests to fail
* Add extra css vars for background colours
* Fix sandbox errors
**After**:
> Test cleanup

- web-components/src/components/modal/scss/mixins.scss
- web-components/src/components/modal/scss/modal.scss
> refactor: remove warning from scss config

- web-components/src/[sandbox]/examples/avatar.ts
- web-components/src/components/avatar/Avatar.constants.ts
- web-components/src/components/avatar/Avatar.stories.ts
- web-components/src/components/avatar/Avatar.test.ts
- web-components/src/components/avatar/Avatar.ts
- web-components/src/components/avatar/CompositeAvatar.ts
- web-components/src/components/avatar/Presence.test.ts
- web-components/src/components/avatar/Presence.ts
- web-components/src/components/avatar/Presence.utils.ts
- web-components/src/components/avatar/scss/module.scss
- web-components/src/components/avatar/scss/presence.scss
- web-components/src/components/avatar/scss/settings.scss
- web-components/src/components/avatar/tokens/lm-avatar-tokens.js
- web-components/src/components/avatar/tokens/mdv2-avatar-tokens.js
- web-components/src/components/icon/Icon.ts
Update new presence in MomentumV2.
https://jira-eng-sjc12.cisco.com/jira/browse/CX-15515
New presence
**After**:
> style(presence): update new presence

- web-components/src/[sandbox]/examples/tabs.ts
- web-components/src/components/tabs/scss/tabs.scss
* Remove host context scss as its only supported on chromium browsers after dependency updates this does not work correctly. It is better to have consistent css between browsers
**After**:
> chore: fix tabs css issue in chrome

- web-components/src/components/alert-banner/scss/alert-banner.scss
- web-components/src/components/badge/tokens/mdv2-badge-tokens.js
- web-components/src/wc_scss/themes/global--mdv2.scss
Update alert banner font family and weight
In mdv2 revert badge colours to lumos defaults until input from UX
**After**:
> Badge update to lumos style

- web-components/src/components/menu-overlay/MenuOverlay.test.ts
- web-components/src/components/menu-overlay/MenuOverlay.ts
* fix accessibility issue in menu overlay
The ariaexpanded attribute should not be applied to <div> tags without having any valid role.
**After**:
> chore: fix menu overlay accessibility issue

- web-components/package.json
- web-components/src/components/avatar/Avatar.ts
- web-components/src/components/grabber/Grabber.test.ts
- web-components/src/components/grabber/Grabber.ts
- web-components/src/components/grabber/scss/grabber.scss
- web-components/src/components/grabber/tokens/lm-grabber-tokens.js
- web-components/src/components/grabber/tokens/md-grabber-tokens.js
* Update icons to 0.0.64
* Update avatar to use design icons if momentum design enabled
* Update grabber for high contrast, momentum design icon and lumos size
**After**:
> Grabber update for icon

- web-components/src/[sandbox]/examples/grabber.ts
- web-components/src/components/grabber/Grabber.ts
- web-components/src/components/grabber/scss/grabber.scss
- web-components/src/components/grabber/scss/module.scss
* When the grabber is focused if it gets focused it should also be visible.
* Add focus ring to container div other wise the focus is cut off
* Update high contrast focus
**After**:
> Grabber focus

- web-components/package.json
- web-components/src/components/icon/Icon.ts
- yarn.lock
> chore: update yarn lock file and update version

- web-components/src/components/avatar/Avatar.test.ts
- web-components/src/components/avatar/Avatar.ts
Fix internal property warning
**After**:
> fix(presence): fix internal property warning

- web-components/package.json
- web-components/src/components/combobox/scss/combobox.scss
- web-components/src/components/combobox/tokens/lm-combobox-tokens.js
- web-components/src/components/combobox/tokens/md-combobox-tokens.js
- web-components/src/components/combobox/tokens/mdv2-combobox-tokens.js
- web-components/src/components/datepicker/DatePicker.ts
- web-components/src/components/input/Input.ts
- web-components/src/components/radio/Radio.ts
- yarn.lock
* combobox colour fixes
* accessibility fixes
**After**:
> Accessibility updates

- web-components/package.json
- web-components/src/[sandbox]/examples/grabber.ts
- web-components/src/components/combobox/ComboBox.ts
- yarn.lock
* Update colour token package
* fix md-span to span md-span does not exit
* update yarn lock file
**After**:
> chore: update the colour tokens to version 0.66

- web-components/package.json
- web-components/src/[sandbox]/sandbox.scss
- web-components/src/components/favorite/Favorite.test.ts
- yarn.lock
* update momentum-design tokens to version 0.67
**After**:
> chore(deps): update momentum design to version 0.0.67

- web-components/src/components/alert/Alert.ts
- web-components/src/components/chip/Chip.ts
- web-components/src/components/icon/Icon.ts
- web-components/src/components/input/Input.ts
- web-components/src/components/tooltip/Tooltip.ts
Fix the accessibility issue that showing in storybook 
**After**:
> fix(accessibility): fix aria issue in storybook

- web-components/package.json
- web-components/src/components/list/List.test.ts
- web-components/src/components/list/List.ts
> #CX-14797 : Agent Email: Screen Readers: Label of the listbox is not descriptive enough.

- web-components/package.json
- web-components/webpack.config.ts
* dependency updates
**After**:
> chore(deps): update momentum design dependencies

- web-components/src/[sandbox]/examples/avatar.ts
- web-components/src/components/alert-banner/AlertBanner.ts
- web-components/src/components/avatar/Avatar.constants.ts
- web-components/src/components/avatar/Avatar.test.ts
- web-components/src/components/avatar/Avatar.ts
- web-components/src/components/avatar/scss/avatar.scss
- web-components/src/components/button/Button.ts
- web-components/src/utils/keyboard.ts
Avatar able to support click event and tooltip text
**After**:
> style(avatar): support click event and tooltip text

- web-components/package.json
- web-components/src/[sandbox]/examples/icon.ts
* update to latest dependencies
**After**:
> chore(deps): update dependencies for momentum

- web-components/src/wc_scss/generic/global.scss
- web-components/src/wc_scss/reset.scss
- web-components/src/wc_scss/themes/global--dark.scss
- web-components/src/wc_scss/themes/global--light.scss
- web-components/src/wc_scss/themes/global--mdv2.scss
- web-components/src/wc_scss/tools/mixins/scrollbar.scss
Add New Scrollbar Style to all components
**After**:
> style(scrollbar): add scrollbar style to all components

- react/src/lib/AlertCall/tests/__snapshots__/index.spec.js.snap
- react/src/lib/ButtonGroup/tests/__snapshots__/index.spec.js.snap
- react/src/lib/DeviceListCall/tests/__snapshots__/index.spec.js.snap
- react/src/lib/Sidebar/tests/__snapshots__/index.spec.js.snap
* Fix react test failing causing pipeline build to fail
https://app.circleci.com/pipelines/github/momentum-design/momentum-ui/12773/workflows/5190782b-be73-4419-a84d-faf743e000e9/jobs/54417
**After**:
> fix: react test failure

- web-components/package.json
- web-components/src/[sandbox]/examples/card.ts
- web-components/src/[sandbox]/examples/grabber.ts
- web-components/src/[sandbox]/examples/modal.ts
- web-components/src/components/alert-banner/AlertBanner.test.ts
- web-components/src/components/audio-player/AudioPlayer.ts
- web-components/src/components/avatar/Avatar.ts
- web-components/src/components/chip/Chip.ts
- web-components/src/components/datepicker/datepicker-day/DatePickerDay.ts
- web-components/src/components/datepicker/tokens/mdv2-datepicker-tokens.js
- web-components/src/components/floating-modal/FloatingModal.ts
- web-components/src/components/grabber/Grabber.ts
- web-components/src/components/icon/Icon.ts
- web-components/src/components/tabs/Tabs.test.ts
- web-components/src/components/tabs/Tabs.ts
- web-components/src/components/timepicker/TimePicker.ts
- web-components/src/components/toggle-switch/tokens/mdv2-toggle-tokens.js
- web-components/src/components/tooltip/tokens/mdv2-tooltip-tokens.js
- web-components/src/tokens/Tokens.test.ts
- web-components/src/wc_scss/colors/tests/colors.cy.js
- web-components/src/wc_scss/typography/tests/typography.cy.js
update errors running linter
**After**:
> Linter errors

- web-components/package.json
- web-components/src/[sandbox]/examples/button.ts
- web-components/src/[sandbox]/examples/icon.ts
- web-components/src/components/button/scss/mixins.scss
- web-components/src/components/combobox/ComboBox.test.ts
- web-components/src/components/draggable/Draggable.test.ts
- web-components/src/components/icon/Icon.ts
- web-components/src/components/input/Input.test.ts
- web-components/src/components/label/Label.test.ts
- web-components/src/components/label/Label.ts
- web-components/src/components/table/Table.stories.ts
- web-components/src/components/tabs/Tab.test.ts
- web-components/src/utils/helpers.ts
* Add documentation for icon properties
* fix eslint errors
**After**:
> docs: add icon documentation

- web-components/src/[sandbox]/examples/icon.ts
- web-components/src/[sandbox]/examples/tabs.ts
- web-components/src/[sandbox]/sandbox.ts
- web-components/src/components/icon/Icon.ts
- web-components/src/components/input/Input.ts
- web-components/src/components/tabs/Tab.ts
- web-components/src/components/tabs/Tabs.ts
- web-components/src/components/tabs/scss/mixins.scss
- web-components/src/components/tabs/scss/tab.scss
- web-components/src/components/tabs/scss/tabs.scss
- yarn.lock
* Fix alignment of tabs. Text and icons are not aligned correctly and on moving to the new icon set it looks even worse
Legacy font Icons
momentum design svg icons
**After**:
Legacy font Icons
momentum design svg icons
> Tab icon updates

- web-components/.eslintrc.js
- web-components/src/[sandbox]/examples/alert.ts
- web-components/src/[sandbox]/examples/button-group.ts
- web-components/src/[sandbox]/examples/draggable.ts
- web-components/src/[sandbox]/examples/floating-modal.ts
- web-components/src/[sandbox]/examples/menu-item.ts
- web-components/src/[sandbox]/examples/menu-overlay.ts
- web-components/src/[sandbox]/examples/modal.ts
- web-components/src/[sandbox]/examples/tabs.ts
- web-components/src/components/alert/Alert.mdx
- web-components/src/components/button-group/ButtonGroup.stories.ts
- web-components/src/components/button/Button.ts
- web-components/src/components/date-range-picker/DateRangePicker.ts
- web-components/src/components/draggable/DraggableItem.test.ts
- web-components/src/components/draggable/DraggableItem.ts
- web-components/src/components/floating-modal/FloatingMinimizedModal.ts
- web-components/src/components/grabber/Grabber.ts
- web-components/src/components/loading/Loading.stories.ts
- web-components/src/components/menu/Menu.stories.ts
- web-components/src/components/menu/Menu.test.ts
- web-components/src/components/table-advanced/TableAdvanced.test.ts
- web-components/src/components/table-advanced/TableAdvanced.ts
- web-components/src/components/table-advanced/scss/table-advanced.scss
- web-components/src/components/table-advanced/src/decorators.ts
- web-components/src/components/tabs/Tabs.stories.ts
- web-components/src/utils/generateScssFromTokens.js
- web-components/src/wc_scss/themes/global--dark.scss
- web-components/src/wc_scss/themes/global--light.scss
- web-components/src/wc_scss/themes/global--mdv2.scss
* Update icons to use momentum design icon set
* Fix linter error
* allow access to momentum-design scss tokens in all themes
**After**:
> chore: icon updates

- web-components/src/[sandbox]/examples/input.ts
- web-components/src/components/help-text/HelpText.test.ts
- web-components/src/components/help-text/HelpText.ts
- web-components/src/components/help-text/scss/help-text.scss
- web-components/src/components/input/Input.ts
- web-components/src/components/input/scss/input.scss
- web-components/src/components/input/tokens/mdv2-input-tokens.js
- web-components/src/components/label/scss/label.scss
- web-components/src/wc_scss/tools/mixins/input.scss
New design for Text Field
**After**:
> style(input): new design for text field

- web-components/package.json
* Update icon dependency
**After**:
> chore: update icon dependencies

- web-components/src/[sandbox]/examples/badge.ts
- web-components/src/components/avatar/Avatar.ts
- web-components/src/components/avatar/Presence.test.ts
- web-components/src/components/avatar/Presence.utils.ts
- web-components/src/components/avatar/scss/presence.scss
- web-components/src/components/button/scss/button.scss
- web-components/src/components/button/tokens/mdv2-button-tokens.js
- web-components/src/components/input/Input.ts
- web-components/src/components/input/scss/input.scss
- web-components/src/components/phone-input/scss/settings.scss
- web-components/src/wc_scss/settings/input.scss
* update input padding and search sizes
* update selector variant border radius 
**After**:
> chore: update input and selector variants

- web-components/package.json
- web-components/src/[sandbox]/examples/icon.ts
- web-components/src/components/avatar/scss/presence.scss
- web-components/src/components/button/scss/button.scss
* focus ring for selector variants
**After**:
> Agent selector focus ring

- web-components/package.json
- web-components/src/[sandbox]/examples/avatar.ts
- web-components/src/components/avatar/Avatar.constants.ts
- web-components/src/components/avatar/Avatar.ts
- web-components/src/components/avatar/Presence.ts
- web-components/src/components/avatar/Presence.utils.ts
- web-components/src/components/avatar/scss/avatar.scss
- web-components/src/components/avatar/scss/settings.scss
- web-components/src/components/avatar/tokens/lm-avatar-tokens.js
- web-components/src/components/avatar/tokens/md-avatar-tokens.js
- web-components/src/components/avatar/tokens/mdv2-avatar-tokens.js
* Allow newMomentum to display bot badge
* Update momentumV2 icon avatar background colour
* update presence icon to always return a size so inbetween sizes still have an icon
* update inactive avatar background to not have opacity set
**After**:
> Avatar icon updates

- web-components/src/[sandbox]/examples/avatar.ts
- web-components/src/[sandbox]/examples/button.ts
- web-components/src/components/avatar/Presence.test.ts
- web-components/src/components/avatar/Presence.ts
- web-components/src/components/avatar/Presence.utils.ts
- web-components/src/components/avatar/scss/presence.scss
- web-components/src/components/avatar/tokens/lm-avatar-tokens.js
- web-components/src/components/avatar/tokens/md-avatar-tokens.js
- web-components/src/components/avatar/tokens/mdv2-avatar-tokens.js
- web-components/src/components/button/scss/button.scss
- web-components/src/components/button/tokens/mdv2-button-tokens.js
* update presence icons for design
> chore: update presence icons for spec update

- web-components/package.json
- web-components/src/[sandbox]/examples/button.ts
- web-components/src/components/avatar/tokens/lm-avatar-tokens.js
- web-components/src/components/avatar/tokens/md-avatar-tokens.js
- web-components/src/components/button/tokens/mdv2-button-tokens.js
* update momentum-design icon and token dependency
* update unavailable mdv2 tokens
**After**:
> chore: update momentum dependencies

- web-components/src/[sandbox]/examples/combobox.ts
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/combobox/scss/combobox.scss
- web-components/src/components/combobox/scss/settings.scss
- web-components/src/components/combobox/tokens/mdv2-combobox-tokens.js
New Design for combobox
**After**:
> style(combobox): update new design for combobox

- web-components/src/components/list/scss/settings.scss
* update list padding to 12 from 16
**After**:
> chore: update list padding

- web-components/package.json
- web-components/src/[sandbox]/examples/button.ts
- web-components/src/components/avatar/tokens/lm-avatar-tokens.js
- web-components/src/components/avatar/tokens/md-avatar-tokens.js
* dependency updates
* lumos newMomentum presence colours
**After**:
> chore: dependency updates

- web-components/src/[sandbox]/examples/combobox.ts
- web-components/src/components/combobox/ComboBox.stories.ts
- web-components/src/components/combobox/ComboBox.test.ts
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/combobox/scss/combobox.scss
Fix the arrow button align to centre. Update the new design of ComboBox
**After**:
> style(combobox): center the arrow and update combobox design

- web-components/src/[sandbox]/examples/dropdown.ts
- web-components/src/components/dropdown/Dropdown.stories.ts
- web-components/src/components/dropdown/Dropdown.test.ts
- web-components/src/components/dropdown/Dropdown.ts
- web-components/src/components/dropdown/scss/dropdown.scss
- web-components/src/components/dropdown/tokens/mdv2-dropdown-tokens.js
Rebrand Dropdown to new design, support search function and left icon in the text field
**After**:
> style(dropdown): update new design of dropdown

- web-components/src/[sandbox]/examples/alert.ts
- web-components/src/components/alert/Alert.test.ts
- web-components/src/components/alert/Alert.ts
- web-components/src/components/alert/scss/alert.scss
- web-components/src/components/alert/scss/settings.scss
- web-components/src/components/alert/tokens/mdv2-alert-tokens.js
Update New Alert Design
**After**:
> style(alert): update alert design

- web-components/package.json
- web-components/src/[sandbox]/examples/input.ts
- web-components/src/components/chip/Chip.stories.ts
- web-components/src/components/combobox/tokens/mdv2-combobox-tokens.js
- web-components/src/components/input/tokens/mdv2-input-tokens.js
- web-components/src/components/meeting-alert/MeetingAlert.stories.ts
- web-components/src/components/table-advanced/TableAdvanced.ts
- web-components/src/utils/enums.ts
- yarn.lock
* update package version
* fix some lint errors
* update storybook chips
**After**:
> chore: update version number

- web-components/package.json
- web-components/src/components/chip/scss/chip.scss
* update padding of sentiment chip so no scrollbar should appear
> fix: update sentiment chip padding to remove scrollbar

- web-components/package.json
- web-components/src/components/slider/Slider.stories.ts
- web-components/src/components/slider/Slider.test.ts
- web-components/src/components/slider/Slider.ts
> chore: add slider changing event with old and new value

- web-components/.eslintrc.js
- web-components/src/components/avatar/Presence.test.ts
- web-components/src/components/button/tokens/lm-button-tokens.js
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/date-time-picker/DateTimePicker.test.ts
- web-components/src/components/datepicker/DatePicker.test.ts
- web-components/src/components/draggable/Draggable.stories.ts
- web-components/src/components/grabber/Grabber.test.ts
- web-components/src/components/grabber/Grabber.ts
- web-components/src/components/tooltip/Tooltip.ts
- yarn.lock
* update eslint unused var rule to allow underscore
* Fix some eslint warnings and errors
* Add missing test cases to improve coverage
* Update yarn lock file
**After**:
> chore: add missing test cases and fix linter issues

- web-components/.vscode/settings.json
- web-components/src/[sandbox]/examples/card.ts
- web-components/src/[sandbox]/examples/tabs.ts
- web-components/src/components/date-range-picker/DateRangePicker.ts
- web-components/src/components/datepicker/DatePicker.ts
- web-components/src/components/datepicker/datepicker-calendar/DatePickerCalendar.ts
- web-components/src/components/draggable/Draggable.test.ts
- web-components/src/components/editable-textfield/EditableTextfield.stories.ts
- web-components/src/components/input-file/InputFile.ts
- web-components/src/components/meeting-alert/MeetingAlert.stories.ts
- web-components/src/components/menu/Menu.ts
- web-components/src/components/progress-bar/ProgressBar.stories.ts
- web-components/src/components/radio/RadioGroup.stories.ts
- web-components/src/components/table-advanced/src/decorators.ts
- web-components/src/components/table/Table.ts
- web-components/src/components/tabs/scss/tabs.scss
- web-components/src/components/theme/Theme.ts
- web-components/src/internal-components/color-table/ColorTable.ts
- web-components/src/utils/dateUtils.ts
- web-components/src/utils/helpers.ts
- web-components/src/wc_scss/themes/global--lm.scss
- web-components/src/wc_scss/themes/global--md.scss
- web-components/src/wc_scss/themes/global--mdv2.scss
* Fix more tabs turncated in momentumV2
* Update selected more tab state
* Fix remaining eslint errors
* Add more tabs to more tabs
> chore: update more tabs selected state and truncation width

- web-components/src/components/tabs/Tabs.test.ts
- web-components/src/components/tabs/Tabs.ts
- web-components/src/wc_scss/themes/global--dark.scss
- web-components/src/wc_scss/themes/global--light.scss
- web-components/src/wc_scss/themes/global--mdv2.scss
- Add ScrollIntoView for focus tab to make sure the list will scroll down when key down in the more tabs.
-  Add color tokens required for TPWTable in wxcc-desktop
**After**:
> style(tabs): More tabs list not scroll down when using key down

- web-components/package.json
Update to new version 2.14.2
**After**:
> chore: update to new version

- web-components/package.json
- web-components/src/components/tabs/Tabs.ts
Fix hidden tab focus issue
**After**:
> style(tabs): fix hidden tab focus issue

- web-components/package.json
- web-components/src/components/button/scss/button.scss
- web-components/src/components/button/scss/settings.scss
* dependency updates
* lumos stateselector padding
**After**:
> chore: update dependencies, state selector padding

- web-components/src/[sandbox]/examples/table.ts
- web-components/src/[sandbox]/sandbox.ts
- web-components/src/components/table-advanced/TableAdvanced.ts
- web-components/src/components/table-advanced/scss/table-advanced.scss
- web-components/src/components/table/Table.ts
- web-components/src/components/table/scss/table.scss
> chore: update table sort icons

- web-components/src/[sandbox]/examples/checkbox.ts
- web-components/src/[sandbox]/examples/menu-overlay.ts
- web-components/src/[sandbox]/examples/radio-group.ts
- web-components/src/components/alert-banner/scss/alert-banner.scss
- web-components/src/components/alert-banner/scss/module.scss
- web-components/src/components/button/scss/mixins.scss
- web-components/src/components/checkbox/scss/checkbox.scss
- web-components/src/components/checkbox/scss/settings.scss
- web-components/src/components/combobox/scss/combobox.scss
- web-components/src/components/combobox/scss/settings.scss
- web-components/src/components/dropdown/scss/dropdown.scss
- web-components/src/components/radio/scss/radio.scss
- web-components/src/components/radio/scss/settings.scss
- web-components/src/components/tabs/scss/tab.scss
- web-components/src/components/tabs/scss/tabs.scss
- web-components/src/components/tooltip/scss/tooltip.scss
- web-components/src/wc_scss/themes/global--mdv2.scss
* update font sizes
* update tooltip
**After**:
> chore: update: tooltip and font sizes

- web-components/.vscode/settings.json
- web-components/src/[sandbox]/examples/alert.ts
- web-components/src/[sandbox]/examples/button.ts
- web-components/src/assets/styles/fonts.css
- web-components/src/components/alert/scss/alert.scss
- web-components/src/components/avatar/Presence.test.ts
- web-components/src/components/avatar/Presence.utils.ts
- web-components/src/utils/generateScssFromTokens.js
- web-components/src/wc_scss/themes/global--lm.scss
- web-components/src/wc_scss/themes/global--md.scss
- web-components/src/wc_scss/themes/global--mdv2.scss
* update presence icon for rona (back to dnd)
* update alert shadow (gets cut off)
> Rona presence and alert

- web-components/package.json
- web-components/webpack.config.ts
- yarn.lock
* Remove sass implementation in sass loader to fix legacy API deprecated warning
* Update yarn lock file
**After**:
> Fix sass deprecation warning

- web-components/src/components/menu-overlay/MenuOverlay.stories.ts
- web-components/src/components/menu-overlay/MenuOverlay.test.ts
- web-components/src/components/menu-overlay/MenuOverlay.ts
- yarn.lock
Adding a blur event handler so that I can hook onto a click inside an iframe while the menu is open.
The expected behaviour of the open menu in this case would be to close.
It can be difficult to track any interaction with an embedded iframe from the parent app, but using the window's blur event will let us know when focus has moved away from the current application, and into another app or an iframe in this case.
CX-16357 - When opening the filter dropdown in the Agent Performance Statistics page, the horizontal header tab are not closing
This will allow open menus to close on outside click when the click is inside an iframe. Prior to this change, the menu would remain open as the iframe would not register a click event within the parent app.
To test this change I recreated the bug …
> fix: CX-16357 Adding blur event handler so the menu closes if iframe is clicked

- web-components/package.json
- web-components/src/[sandbox]/examples/alert.ts
- web-components/src/[sandbox]/examples/icon.ts
- web-components/src/components/alert/Alert.test.ts
- web-components/src/components/card-ai/CardAi.ts
- web-components/src/components/icon/Icon.ts
- web-components/webpack.config.ts
The Momentum team are moving true logos away from the icon library. This facilitates that migration.
> CX-16489 Logo migration from Icon Library to Brand Visuals Library

- web-components/.storybook/main.ts
- web-components/package.json
- web-components/src/[sandbox]/examples/grabber.ts
- web-components/src/[sandbox]/sandbox.ts
- web-components/src/wc_scss/generic/normalize.scss
- web-components/webpack.config.dev.server.ts
- yarn.lock
* update dependencies
* save theme on reload on sandbox
**After**:
> Dep updates

- web-components/src/components/menu-overlay/MenuOverlay.test.ts
- web-components/src/components/menu-overlay/MenuOverlay.ts
Removing the specific check for an iframe. I found an edge case when running the initial fix using yarn start as opposed to yarn storybook:local. It looks like there is no guarantee that the activeElement.tagName will be 'IFRAME' even if the iframe is what caused the window to lose focus.
I am happy to remove this check as it was only in there to make this specific to iframes  as this was the bug scenario, but it makes sense to remove as this will fix the iframe scenario, and also any other scenarios where the window loses focus for whatever reason while the menu is open.
CX-16357
I spotted that in some instances, when an iframe is clicked on, the tagName is not IFRAME, causing the menu not to close when it should have. Removing the check for IFRAME allows menu to close whenever the …
> fix: removing element iframe check

- web-components/package.json
Bump web-components version for publishing
**After**:
> Bump web-components version for publishing

- web-components/package.json
- web-components/src/components/theme/Theme.test.ts
- web-components/src/components/theme/Theme.ts
This fixes a bug in Theme.ts which leads to `md-tooltip` components showing the wrong tooltip. 
The issue can be observed in several ways but one example is:
- have an md-audio-player component
- immediately upon displaying, hover mouse over Play button
- observe the correct "Play" tooltip
- wait for the audio src to load (displays audio file duration)
- once audio src is loaded the tooltip for the Play button changes to "Volume level 75%"
To reproduce the issue easier, I've added a delay (during development testing) in `AudioPlayer.ts` inside the `firstUpdated` so that the audio source is updated with a delay. This is to allow enough time for the original tooltip to display, before the audio is loaded.
Then followed the steps described above.
**After**:
> Fix virtual tooltip changeMessge handler not checking reference

- web-components/src/[sandbox]/examples/tabs.ts
- web-components/src/components/tabs/Tab.ts
- web-components/src/components/tabs/Tabs.ts
- web-components/src/components/tabs/scss/tab.scss
- web-components/src/components/tabs/scss/tabs.scss
update to add new tab type for primary style
add new justify style that hugs button and has even space between
**After**:
> chore: tab style updates

- web-components/package.json
- web-components/src/[sandbox]/examples/alert.ts
- web-components/src/components/alert/Alert.test.ts
- web-components/src/components/alert/Alert.ts
- web-components/src/components/alert/scss/alert.scss
- web-components/src/components/alert/scss/module.scss
- web-components/src/components/alert/scss/settings.scss
- web-components/src/components/alert/tokens/lm-alert-tokens.js
- web-components/src/components/alert/tokens/md-alert-tokens.js
- web-components/src/components/alert/tokens/mdv2-alert-tokens.js
- web-components/src/components/loading/scss/loading.scss
- web-components/src/components/loading/scss/module.scss
- web-components/src/components/progress-bar/scss/settings.scss
- web-components/src/components/radio/scss/radio.scss
- web-components/src/components/taskitem/scss/settings.scss
- web-components/src/components/theme/Theme.ts
- web-components/src/wc_scss/colors/settings-transparencies.scss
- web-components/src/wc_scss/icon/settings.scss
- web-components/src/wc_scss/settings/core.scss
- web-components/src/wc_scss/tools/functions/core.scss
- web-components/src/wc_scss/tools/mixins/spacing.scss
- web-components/src/wc_scss/typography/settings.scss
- web-components/src/wc_scss/typography/typography.scss
Update alert padding and fix sass warnings
**After**:
> chore: update alert and fix sass warnings

- web-components/package.json
- web-components/src/[sandbox]/examples/button.ts
- web-components/src/[sandbox]/examples/input.ts
- web-components/src/components/button/Button.ts
- web-components/src/components/button/scss/button.scss
- web-components/src/components/button/scss/settings.scss
- web-components/src/components/input/Input.ts
- web-components/src/components/input/scss/input.scss
- web-components/src/wc_scss/settings/button-settings.scss
- web-components/src/wc_scss/settings/input.scss
Add compact style for new momentum input
new momentum input now respects pill param
add rounded parm to button
**After**:
> chore: update input styles

- web-components/src/components/alert/Alert.ts
- web-components/src/components/alert/scss/alert.scss
- yarn.lock
update footer slot change handling
**After**:
> chore: update alert slot handling for footer

- web-components/src/[sandbox]/examples/combobox.ts
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/combobox/scss/combobox.scss
- web-components/src/components/combobox/scss/settings.scss
- web-components/src/components/label/scss/settings.scss
- web-components/src/components/popover/scss/module.scss
Add a compact version of new momentum combobox with size 28px
Add a filter combobox
**After**:
> chore: compact combo and filter

- web-components/src/components/avatar/Avatar.test.ts
- web-components/src/components/avatar/Avatar.ts
- web-components/src/components/avatar/Presence.test.ts
- web-components/src/components/avatar/Presence.ts
- web-components/src/components/avatar/Presence.utils.ts
- web-components/src/components/avatar/scss/avatar.scss
- web-components/src/components/avatar/scss/module.scss
- web-components/src/components/avatar/scss/presence.scss
- web-components/src/components/avatar/scss/settings.scss
- web-components/src/wc_scss/settings/avatar.scss
Update presence size and failure icon
Fix presence right to the place on Avatar
Update all presence icon to circular 
**After**:
> style(avatar): update presence size and fix layout issue

- web-components/src/[sandbox]/examples/tabs.ts
- web-components/src/components/alert-banner/scss/alert-banner.scss
- web-components/src/components/alert-banner/scss/module.scss
- web-components/src/components/alert-banner/scss/settings.scss
- web-components/src/components/tabs/Tab.ts
- web-components/src/components/tabs/scss/tab.scss
Update alert font size for new momentum
Update tab primary line 
**After**:
> chore: alert font and tab line primary

- web-components/src/components/date-range-picker/DateRangePicker.test.ts
- web-components/src/components/date-range-picker/DateRangePicker.ts
Current selection logic:
1. is different from standard design followed in most apps with such pickers (e.g. skyscanner, booking.com, airbnb etc)
2. is less intuitive than above designs
3. often requires far more clicks to set same date range (e.g. changing range from 1st-31st to 30th-31st takes about 6 or 7 clicks as opposed to 2)
So I'm changing the logic to be more inline with conventional design.
**After**:
> Modify range selection logic for md-date-range-picker

- web-components/package.json
- web-components/src/components/advance-list/AdvanceList.ts
> updated web component to 2.14.18

- web-components/src/[sandbox]/examples/task-item.ts
- web-components/src/components/taskitem/TaskItem.test.ts
- web-components/src/components/taskitem/TaskItem.ts
This will allow users to optionally avoid the browser generated tooltip from title.
This will allow users to optionally avoid the browser generated tooltip from title. By providing a new variable to use instead of title as the display text. If title is only used. Then the legacy functionalty will reamin and it will be used as display text.
Prevent multiple tooltips in the case where a tooltip has been added to a task-item.
Will not affect anything external to the component, or any pre-exsisting functionality on the component.
Run and verified in the web-component sandbox.
Run against the suite of tests exisiting for the component, with tests added to cover my change.
Functionality is preserved in this case. This changes allows any consumer the ability to remove …
> fix(release): decouple title from rendered text in TextItem (CX-16559)

- web-components/package.json
- web-components/src/components/dropdown/scss/settings.scss
- web-components/src/components/dropdown/tokens/lm-dropdown-tokens.js
- web-components/src/components/link/tokens/mdv2-link-tokens.js
dropdown border colour does not match the combobox. More noticable in mdv2
**After**:
> chore: update dropdown border to match combobox

- web-components/package.json
- web-components/src/[sandbox]/examples/tooltip.ts
- web-components/src/components/taskitem/TaskItem.stories.ts
- web-components/src/components/theme/Theme.ts
- web-components/src/components/tooltip/Tooltip.ts
- web-components/src/components/tooltip/scss/module.scss
- web-components/src/components/tooltip/scss/settings.scss
- web-components/src/components/tooltip/scss/tooltip.scss
- web-components/src/components/tooltip/tokens/mdv2-tooltip-tokens.js
- web-components/src/wc_scss/themes/global--mdv2.scss
Update arrow off centre for small tooltips
Update from using polygon clip-path to border. Fixes tearing bugs where arrow meets container
Update rem-base to 14
**After**:
> chore: update tooltip arrow position and style

- web-components/package.json
- web-components/src/[sandbox]/examples/button.ts
- web-components/src/components/button/Button.ts
- web-components/src/components/button/scss/button.scss
- web-components/src/components/button/tokens/lm-button-tokens.js
- web-components/src/components/button/tokens/mdv2-button-tokens.js
- web-components/src/components/dropdown/scss/dropdown.scss
- web-components/src/components/dropdown/tokens/mdv2-dropdown-tokens.js
> chore: add dropdown button variant

- web-components/package.json
- web-components/src/[sandbox]/examples/phone-input.ts
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/phone-input/PhoneInput.ts
- web-components/src/components/phone-input/scss/phoneInput.scss
Phone input support new momentum style
**After**:
> chore: update phone input styles

- web-components/src/[sandbox]/examples/input.ts
- web-components/src/components/input/scss/input.scss
- web-components/src/components/input/tokens/lm-input-tokens.js
- web-components/src/components/input/tokens/md-input-tokens.js
Add colour tokens to new momentum style input for lumos theme
This will help with transition to new theme
**After**:
> chore: add lumos colour for new momentum style input

- web-components/package.json
- web-components/src/[sandbox]/examples/combobox.ts
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/combobox/scss/combobox.scss
- web-components/src/components/dropdown/Dropdown.ts
- web-components/src/components/dropdown/scss/dropdown.scss
- web-components/src/components/dropdown/scss/settings.scss
- web-components/src/components/dropdown/tokens/lm-dropdown-tokens.js
- web-components/src/components/dropdown/tokens/md-dropdown-tokens.js
- web-components/src/components/dropdown/tokens/mdv2-dropdown-tokens.js
- web-components/src/components/input/scss/input.scss
- web-components/src/components/input/tokens/mdv2-input-tokens.js
Updates for dropdown in new momentum style
**After**:
> chore: update dropdown new momentum sizings

- web-components/src/components/advance-list/scss/AdvanceList.scss
Add item spacing to list
**After**:
> chore: add spacing to list items

- web-components/package.json
- web-components/src/[sandbox]/examples/avatar.ts
- web-components/src/components/avatar/Avatar.ts
- web-components/src/components/list/List.ts
Fix: Toggling on newMomentum while presence is idle results in presence cut out with no presence shown
**After**:
> chore: update avatar presence on newMomentum property change

- web-components/src/components/input/Input.ts
> #CX-17126 : stop propagation on input clear

- web-components/package.json
> #CX-17126 : Updating momentum version

- web-components/package.json
- web-components/src/[sandbox]/examples/tabs.ts
- web-components/src/[sandbox]/sandbox.scss
- web-components/src/[sandbox]/sandbox.ts
- web-components/src/components/button/Button.ts
- web-components/src/components/icon/Icon.ts
- web-components/src/components/tabs/Tabs.ts
- web-components/src/components/theme/Theme.ts
- web-components/src/wc_scss/themes/global--dark.scss
- web-components/src/wc_scss/themes/global--light.scss
- web-components/src/wc_scss/themes/global--mdv2.scss
- web-components/webpack.config.ts
Add glass tokens
Add visual rebrand images to sandbox
minor code refactor
**After**:
> Add glass token

- web-components/src/wc_scss/themes/global--dark.scss
- web-components/src/wc_scss/themes/global--light.scss
- web-components/src/wc_scss/themes/global--mdv2.scss
reenable mdv2 table colour tokens
**After**:
> chore: mdv2 table color tokens

- web-components/package.json
- web-components/src/[sandbox]/examples/link.ts
- web-components/src/components/alert/scss/alert.scss
- web-components/src/components/alert/scss/settings.scss
- web-components/src/components/badge/scss/settings.scss
- web-components/src/components/grabber/Grabber.ts
- web-components/src/components/grabber/scss/grabber.scss
- web-components/src/components/help-text/scss/settings.scss
- web-components/src/components/label/scss/settings.scss
- web-components/src/components/link/Link.ts
- web-components/src/components/link/scss/link.scss
- web-components/src/components/link/scss/mixins.scss
- web-components/src/components/link/tokens/lm-link-tokens.js
- web-components/src/components/link/tokens/md-link-tokens.js
- web-components/src/components/link/tokens/mdv2-link-tokens.js
- web-components/src/components/meeting-alert/scss/settings.scss
- web-components/src/components/tabs/scss/settings.scss
- web-components/src/wc_scss/themes/global--dark.scss
- web-components/src/wc_scss/themes/global--light.scss
- web-components/src/wc_scss/themes/global--mdv2.scss
* Update focus ring on grabber to match shape
* Add size property to link for small midsize and large
* Add inverted colour to link
**After**:
> chore: update grabber focus and link style

- web-components/.storybook/themeDecorator.js
- web-components/package.json
- web-components/src/[sandbox]/examples/link.ts
- web-components/src/[sandbox]/examples/modal.ts
- web-components/src/components/accordion/scss/settings.scss
- web-components/src/components/link/Link.ts
- web-components/src/components/link/scss/mixins.scss
- web-components/src/components/menu-overlay/scss/menu-overlay.scss
- web-components/src/components/modal/Modal.stories.ts
- web-components/src/components/modal/Modal.ts
- web-components/src/components/modal/scss/modal.scss
- web-components/src/components/modal/scss/settings.scss
- web-components/src/components/modal/tokens/lm-modal-tokens.js
- web-components/src/components/modal/tokens/md-modal-tokens.js
- web-components/src/components/modal/tokens/mdv2-modal-tokens.js
- web-components/src/components/table-advanced/TableAdvanced.ts
- web-components/src/components/table/Table.ts
- web-components/src/components/table/scss/settings.scss
- web-components/src/components/table/scss/table.scss
- web-components/src/components/table/tokens/lm-table-tokens.js
- web-components/src/components/table/tokens/md-table-tokens.js
- web-components/src/components/table/tokens/mdv2-table-tokens.js
- web-components/src/utils/generateScssFromTokens.js
- web-components/src/wc_scss/themes/global--dark.scss
- web-components/src/wc_scss/themes/global--light.scss
- web-components/src/wc_scss/themes/global--mdv2.scss
* Add alignment property for modal and default to left in momentum v2
* Update storybook to thememanager properties on theme change
* Add inline link style to allow for default link colour while inline
* Update table style for mdv2
* Set accordion item font size to midsize mdv2
* Modal sandbox extra modals and restyling
* Change sort up and down icon
* Fix menu overlay arrow colour not matching background of menuoverlay
**After**:
> Link modal sort

- web-components/package.json
- web-components/src/[sandbox]/sandbox.ts
- web-components/src/components/datepicker/DatePicker.ts
- web-components/src/components/input/Input.ts
- web-components/src/components/input/scss/input.scss
- web-components/src/components/table-advanced/scss/module.scss
- web-components/src/components/table-advanced/scss/settings.scss
- web-components/src/components/table-advanced/scss/table-advanced.scss
- web-components/src/components/table/scss/module.scss
- web-components/src/wc_scss/themes/global--dark.scss
- web-components/src/wc_scss/themes/global--light.scss
* Datepicker allow newMomentum style on the input
* Add a check for has right icon in input field so that clipping doesn't happen too early for date picker
* Remove light mode fallbacks for table advanced
* Update pinned background colour lumos
**After**:
> chore: allow new momentum style for datepicker input

- web-components/.storybook/main.ts
- web-components/package.json
- web-components/src/[sandbox]/examples/datepicker.ts
- web-components/src/components/datepicker/DatePicker.stories.ts
- web-components/src/components/datepicker/DatePicker.ts
- web-components/src/components/table-advanced/TableAdvanced.ts
- web-components/src/components/table-advanced/scss/table-advanced.scss
Date picker compact input
**After**:
> chore: compact input date picker

- web-components/src/[sandbox]/examples/alert-banner.ts
- web-components/src/[sandbox]/examples/button.ts
- web-components/src/components/alert-banner/AlertBanner.stories.ts
- web-components/src/components/alert-banner/AlertBanner.ts
- web-components/src/components/alert-banner/scss/alert-banner.scss
- web-components/src/components/alert-banner/scss/settings.scss
- web-components/src/components/button/Button.ts
- web-components/src/components/button/scss/button.scss
Needed to update banner to be closer to current banner spec:
https://www.figma.com/design/eZ2EDjOOK2w0Wyx4aOfYZL/%F0%9F%A7%A9-CX-Design%3A-Component-Library-Toolkit?m=auto&node-id=0-1&t=DxMnZnELsSyesLXB-1
Added ghostInheritTextColor variant for button. 
Useful for when we want the transparent BG property of a ghost button while keeping the text colour of the context.
Added sandbox example usage for refresh button (ghostInheritTextColor on right):
vs when banner type set to "warning":
**After**:
> Bring alert banner closer to new momentum spec 

- web-components/.storybook/themeDecorator.js
- web-components/package.json
- web-components/src/components/datepicker/DatePicker.ts
- web-components/src/components/input/Input.test.ts
- web-components/src/components/input/Input.ts
- web-components/src/components/menu-overlay/MenuOverlay.ts
- web-components/src/components/modal/scss/modal.scss
Fix focus trap on input clear button bug introduced by https://github.com/momentum-design/momentum-ui/pull/1848
stopping all propgation of events from the clear button caused tabbing from the button to not work
**After**:
> fix: input clear button focus trap

- web-components/src/[sandbox]/examples/chat-message.ts
- web-components/src/components/chat-message/ChatMessage.stories.ts
- web-components/src/components/chat-message/ChatMessage.ts
- web-components/src/components/chat-message/scss/chat-message.scss
> feat: add status property to chat message component and updated examples

- web-components/package.json
- web-components/src/[sandbox]/examples/date-range-picker.ts
- web-components/src/[sandbox]/examples/tabs.ts
- web-components/src/components/datepicker/DatePicker.ts
- web-components/src/components/tabs/Tabs.ts
If overflow text too long show tooltip
Date picker error with no error text hide icon
> chore: add tooltip if more tab overflow too long

- web-components/package.json
- web-components/src/[sandbox]/examples/AdvanceList/components/ErrorLoader/ErrorLoader.ts
- web-components/src/[sandbox]/examples/AdvanceList/components/ParentComponentError.ts
- web-components/src/[sandbox]/examples/AdvanceList/components/ParentComponentGeneric.ts
- web-components/src/[sandbox]/examples/AdvanceList/components/ParentComponentPreSelect.ts
- web-components/src/[sandbox]/examples/AdvanceList/components/ParentComponentWithMdOverlay.ts
- web-components/src/components/advance-list/AdvanceList.test.ts
- web-components/src/components/advance-list/AdvanceList.ts
- web-components/src/components/modal/scss/settings.scss
- web-components/src/wc_scss/themes/global--mdv2.scss
- yarn.lock
Large Modal header size change for mdv2
eslint formatting of list advanced
update yarn lock file
**After**:
> chore: update modal header large mdv2

- web-components/package.json
- web-components/src/components/dropdown/scss/dropdown.scss
- web-components/src/components/dropdown/scss/module.scss
- web-components/src/components/dropdown/scss/settings.scss
- web-components/src/components/modal/scss/mixins.scss
- web-components/src/components/modal/scss/modal.scss
- web-components/src/components/modal/scss/settings.scss
- web-components/src/components/tabs/scss/tabs.scss
Set min height to be much smaller for large modals and keep height the same. This will allow it to shrink if there is not enough vertical space
Fix dropdown placholder text not being set correctly in forced color mode
Fix line tabs color in forced color mode
**After**:
> chore: update large modal min size so it can shrink

- web-components/package.json
- web-components/src/[sandbox]/examples/radio-group.ts
- web-components/src/components/button/scss/button.scss
- web-components/src/components/button/tokens/md-button-tokens.js
- web-components/src/components/radio/RadioGroup.ts
- web-components/src/utils/generateScssFromTokens.js
Method to clear selection on the radio group
Radio group stop propagation of events if handled
Handling of color tokens for legacy momentum
**After**:
> chore: radiogroup clear selection

- web-components/src/[sandbox]/examples/chat-message.ts
- web-components/src/components/chat-message/ChatMessage.stories.ts
- web-components/src/components/chat-message/ChatMessage.ts
- web-components/src/components/chat-message/scss/chat-message.scss
> feat: enhance chat message component with custom content and status updates in the header section

- web-components/src/components/advance-list/AdvanceList.stories.ts
- web-components/src/components/advance-list/AdvanceList.ts
> #CX-17689 : Advance List added in storybook

- web-components/package.json
- web-components/src/[sandbox]/examples/button.ts
- web-components/src/[sandbox]/examples/grabber.ts
- web-components/src/components/button/Button.ts
- web-components/src/components/button/scss/button.scss
- web-components/src/components/button/tokens/lm-button-tokens.js
- web-components/src/components/button/tokens/md-button-tokens.js
- web-components/src/components/button/tokens/mdv2-button-tokens.js
- web-components/src/components/grabber/Grabber.stories.ts
- web-components/src/components/grabber/Grabber.ts
- web-components/src/components/grabber/scss/grabber.scss
- web-components/src/components/grabber/tokens/lm-grabber-tokens.js
- web-components/src/components/grabber/tokens/md-grabber-tokens.js
- web-components/src/components/grabber/tokens/mdv2-grabber-tokens.js
Add button variants
secondary negative, positive and accent
Add grabber shadow prop
**After**:
> chore: add new button variants

- web-components/package.json
- web-components/src/components/advance-list/AdvanceList.ts
> #CX-17689 : fix overlapping issue in advance list

- web-components/package.json
- web-components/src/components/advance-list/AdvanceList.ts
- web-components/src/components/theme/Theme.ts
- web-components/src/components/tooltip/scss/tooltip.scss
> #CX-18099 : Event Listener in Momentum webcomponents

- web-components/src/[sandbox]/examples/button.ts
- web-components/src/[sandbox]/examples/form.ts
- web-components/src/components/code-editor/scss/code-editor.scss
- web-components/src/components/loading/Loading.ts
- web-components/src/components/loading/scss/loading.scss
- web-components/src/components/menu-overlay/MenuOverlay.ts
- web-components/src/components/slider/scss/slider.scss
- web-components/src/components/spinner/Spinner.ts
- web-components/src/components/spinner/scss/spinner.scss
- web-components/src/components/tabs/scss/tab.scss
- web-components/src/components/toggle-switch/scss/toggle-switch.scss
- web-components/src/components/tooltip/scss/tooltip.scss
css key frame animation in spinner and loading causing detached nodes on disconnect
Reimplement animation in javascript to avoid this problem as they are simple animations
**After**:
> Spinner loader memory leak

- web-components/package.json
- web-components/src/[sandbox]/examples/badge.ts
- web-components/src/[sandbox]/examples/chip.ts
- web-components/src/[sandbox]/sandbox.ts
- web-components/src/components/badge/Badge.ts
- web-components/src/components/badge/scss/badge.scss
- web-components/src/components/badge/scss/mixins.scss
- web-components/src/components/badge/tokens/lm-badge-tokens.js
- web-components/src/components/badge/tokens/md-badge-tokens.js
- web-components/src/components/badge/tokens/mdv2-badge-tokens.js
- web-components/src/components/chip/Chip.ts
- web-components/src/components/chip/scss/chip.scss
- web-components/src/components/chip/scss/mixins.scss
- web-components/src/components/tabs/Tabs.ts
- web-components/src/wc_scss/themes/global--mdv2.scss
> chore: add status badge

- web-components/package.json
- web-components/src/[sandbox]/examples/chat-message.ts
- web-components/src/components/avatar/Avatar.stories.ts
- web-components/src/components/chat-message/ChatMessage.stories.ts
- web-components/src/components/chat-message/ChatMessage.test.ts
- web-components/src/components/chat-message/ChatMessage.ts
- web-components/src/utils/enums.ts
CX-18358: Enhanced chat message
> chore: CX-18358: Enhanced chat message

- web-components/webpack.config.ts
Fix glob pattern causing build issues on windows
**After**:
> chore: fix windows build

- web-components/package.json
- web-components/src/[sandbox]/examples/datepicker.ts
- web-components/src/components/datepicker/DatePicker.ts
- web-components/src/components/datepicker/scss/datepicker.scss
- yarn.lock
when days were beside each other range rendered incorrectly
**After**:
> Date range fix

- web-components/jest.config.js
- web-components/package.json
- web-components/src/[sandbox]/examples/tabs.ts
- web-components/src/components/accordion/AccordionItem.ts
- web-components/src/components/menu/Menu.ts
- web-components/src/components/menu/MenuItem.test.ts
- web-components/src/components/tabs/Tab.test.ts
- web-components/src/components/tabs/Tabs.ts
- web-components/src/utils/uniqueId.ts
- web-components/webpack.config.ts
Remove dependency on nanoid so node:crypto not needed
**After**:
> chore: remove nanoid dependency

- web-components/src/[sandbox]/examples/card-v2.ts
- web-components/src/[sandbox]/examples/index.ts
- web-components/src/[sandbox]/sandbox.ts
- web-components/src/components/card-v2/CardV2.stories.ts
- web-components/src/components/card-v2/CardV2.test.ts
- web-components/src/components/card-v2/CardV2.ts
- web-components/src/components/card-v2/scss/card-v2.scss
- web-components/src/components/card-v2/scss/module.scss
- web-components/src/components/card-v2/scss/settings.scss
> #CX-17617 Add Card component

- web-components/package.json
- web-components/src/components/accordion/AccordionItem.test.ts
- web-components/src/components/avatar/Avatar.constants.ts
- web-components/src/components/badge/Badge.test.ts
- web-components/src/components/card-v2/CardV2.stories.ts
- web-components/src/components/card-v2/CardV2.test.ts
- web-components/src/components/card-v2/CardV2.ts
- web-components/src/components/date-time-picker/DateTimePicker.ts
- web-components/src/components/datepicker/DatePicker.ts
- web-components/src/components/dropdown/Dropdown.test.ts
- web-components/src/components/input-file/InputFile.test.ts
- web-components/src/components/table-advanced/TableAdvanced.test.ts
- web-components/src/components/table-advanced/TableAdvanced.ts
- web-components/src/components/tabs/Tabs.test.ts
- web-components/src/components/tabs/Tabs.ts
- web-components/src/components/theme/Theme.test.ts
- web-components/src/index.ts
- web-components/src/mixins/FocusMixin.test.ts
- web-components/src/utils/dateUtils.ts
mock out console error and warning in tests 
**After**:
> Test warnings

- web-components/src/components/dropdown/scss/dropdown.scss
> Dark theme issue for dropdown fixed

- web-components/package.json
- web-components/src/components/card-v2/CardV2.ts
- web-components/src/components/card-v2/scss/card-v2.scss
* Support double length strings
* Fix typo
**After**:
> #CX-17617 Card component updates

- web-components/package.json
> #CX-18683 : Momentum version upgrade

- web-components/package.json
- web-components/src/managers/ThemeManager.ts
update mobx version
make momentum-design/tokens a dev dependency
**After**:
> chore: update mobx

- web-components/package.json
- web-components/src/managers/ThemeManager.ts
> chore: move to mobx 6

- web-components/src/components/floating-modal/scss/floating.scss
> CX-18551 : give capability to provide custom width and height.

- web-components/package.json
- web-components/src/[sandbox]/examples/avatar.ts
- web-components/src/components/avatar/Avatar.constants.ts
- web-components/src/components/avatar/Avatar.test.ts
- web-components/src/components/avatar/Avatar.ts
- web-components/src/components/taskitem/TaskItem.ts
update icon size for avatars. it is currently too small
**After**:
> chore: update avatar icon size

- web-components/src/components/tabs/Tabs.stories.ts
- web-components/src/components/tabs/Tabs.test.ts
- web-components/src/components/tabs/Tabs.ts
Add aria label for arrow buttons and fix page resize arrow button not show issue.
Add test for scroll arrow method.
**After**:
> test: add accessibility for scroll-arrow button and test

- web-components/package.json
- web-components/src/components/taskitem/TaskItem.ts
> #CX-17789 : changes in task item

- web-components/src/components/taskitem/TaskItem.stories.ts
- web-components/src/components/taskitem/TaskItem.ts
minor update to task item style
**After**:
> chore: update task item style

- web-components/package.json
- web-components/src/components/floating-modal/FloatingMinimizedModal.test.ts
- web-components/src/components/floating-modal/FloatingMinimizedModal.ts
- web-components/src/components/floating-modal/FloatingModal.stories.ts
- web-components/src/components/floating-modal/FloatingModal.test.ts
- web-components/src/components/floating-modal/FloatingModal.ts
This PR introduces two key improvements to the Floating Modal component:
**1. Optional control over maximize/restore functionality**
1.1. Added maximizable attribute (defaults to true) to allow disabling the maximize/restore functionality when content is small
1.2 Added resizable attribute (defaults to true) to control whether users can resize the modal
**Enhanced accessibility for minimized modals**
**2. Added an explicit maximize button to the minimized floating modal pill**
Previously, users had to click on the entire minimized pill to maximize the modal, which presented accessibility issues
The new dedicated maximize button improves discoverability and aligns with accessibility best practices
**Example Usage**
<md-floating-modal maximizable="false"></md-floating-modal> …
> #CX-18657: make resize, maximize configurable. add maximize button for minimized floating modal

- web-components/src/[sandbox]/examples/popover.ts
- web-components/src/components/checkbox/scss/checkbox.scss
- web-components/src/components/checkbox/scss/checkboxgroup.scss
- web-components/src/components/checkbox/scss/settings.scss
- web-components/src/components/checkbox/tokens/mdv2-checkbox-tokens.js
- web-components/src/components/coachmark-popover/CoachmarkPopover.ts
- web-components/src/components/menu-overlay/MenuOverlay.ts
- web-components/src/components/popover/Popover.ts
- web-components/src/components/popover/scss/popover.scss
- web-components/src/components/popover/tokens/mdv2-popover-tokens.js
- web-components/src/components/radio/scss/radio.scss
- web-components/src/components/radio/scss/radiogroup.scss
- web-components/src/components/radio/scss/settings.scss
- web-components/src/components/radio/tokens/lm-radio-tokens.js
- web-components/src/components/radio/tokens/mdv2-radio-tokens.js
- web-components/src/components/slider/tokens/mdv2-slider-token.js
add property for popover positioning strategy
update radio button style
update checkbox style
**After**:
> chore: popover stragegy and radio/checkbox style

- web-components/package.json
- web-components/src/[sandbox]/examples/popover.ts
- web-components/src/components/tooltip/Tooltip.ts
If disabled property of toolitp changes to false while showing hide the tooltip
**After**:
> chore: hide tooltip on show if disabled changes

- web-components/src/components/floating-modal/FloatingMinimizedModal.ts
Closing minimized modal was not happening with Enter/Space key.
**After**:
> fix close issue in floating minimized modal

- web-components/package.json
- web-components/src/components/chip/Chip.ts
- web-components/src/components/chip/scss/chip.scss
- web-components/src/components/chip/scss/mixins.scss
- web-components/src/components/chip/scss/settings.scss
allow for proper centering of icons in chips with no label
**After**:
> Chip update

- web-components/src/[sandbox]/examples/chat-message.ts
- web-components/src/components/chat-message/ChatMessage.test.ts
- web-components/src/components/chat-message/ChatMessage.ts
Adding a clickable timestamp for the chat message.
Adding a clickable timestamp for the chat message.
https://jira-eng-sjc12.cisco.com/jira/browse/CX-19024
all of em
Maunual and Automated testing
**After**:
> feat(release): add clickable timestamp to chat message

- web-components/src/components/badge/Badge.stories.ts
- web-components/src/components/chip/Chip.stories.ts
add badge and chip stories
**After**:
> chore: add new sotries for badge and chips

- web-components/src/[sandbox]/examples/badge.ts
- web-components/src/components/avatar/Avatar.constants.ts
- web-components/src/components/avatar/Avatar.stories.ts
- web-components/src/components/avatar/Avatar.ts
- web-components/src/components/badge/Badge.stories.ts
- web-components/src/components/badge/Badge.ts
- web-components/src/components/badge/badge.constant.ts
- web-components/src/components/badge/scss/badge.scss
- web-components/src/components/taskitem/TaskItem.constants.ts
- web-components/src/components/taskitem/TaskItem.test.ts
- web-components/src/components/taskitem/TaskItem.ts
- web-components/src/components/taskitem/TaskItem.utils.test.ts
- web-components/src/components/taskitem/TaskItem.utils.ts
- Support avatar circle sizes for badge
- Add testing for taskitem utils
- Update taskitem mediatype
**After**:
> style: addon badge sizes and add testing for taskitem utils

- web-components/src/components/date-range-picker/DateRangePicker.ts
- web-components/src/components/datepicker/scss/datepicker.scss
> #CX-19117: date range picker styling fixes

- web-components/package.json
- web-components/src/[sandbox]/examples/alert-banner.ts
- web-components/src/components/alert-banner/AlertBanner.stories.ts
- web-components/src/components/alert-banner/AlertBanner.test.ts
- web-components/src/components/alert-banner/AlertBanner.ts
- web-components/src/components/alert-banner/scss/alert-banner.scss
- web-components/src/components/alert-banner/scss/mixins.scss
- web-components/src/components/alert-banner/scss/settings.scss
- web-components/src/components/alert-banner/tokens/lm-alertbanner-tokens.js
- web-components/src/components/alert-banner/tokens/mdv2-alertbanner-tokens.js
- yarn.lock
Updating various aspects of the alert-banner UI component, while also maintaining support for the existing alert-banner instances that are in use. Once those instances are brought up to use the latest spec, we can simplify some of this logic.
Existing alert-banner usages:
Spec:
Actual:
Storybook:
> CX-19021 [MomentumUI] Update alert-banner component to latest spec

- web-components/package.json
- web-components/src/components/date-range-picker/DateRangePicker.test.ts
- web-components/src/components/date-range-picker/DateRangePicker.ts
- web-components/src/components/date-time-picker/DateTimePicker.ts
- web-components/src/components/datepicker/DatePicker.test.ts
- web-components/src/components/datepicker/DatePicker.ts
- web-components/src/utils/dateUtils.test.ts
- web-components/src/utils/dateUtils.ts
Remove a function which performed string manipulation on date values which represented the value of the DatePicker, DateTimePicker, and DateRangePicker components.
https://jira-eng-sjc12.cisco.com/jira/browse/CX-19136
#1907 previously added code to the components which would force them to use slashes (`/`) instead of dashes (`-`) when displaying their current values. This caused issues as in some use-cases the component were displaying entire ISO8601 (strictly in the format: `YYYY-MM-DDTHH:MM:SS+000Z`) dates as their value. The forced change from dashes to slashes in these values broke luxon's ability to parse the dates at all, and it returned invalid date objects. 
Tested the component manually in the sandbox, and updated unit tests to expect the changed behaviour
**Before** (If …
> #CX-19136: Remove invalid ISO date formatting

- web-components/package.json
Bump patch version in package.json
To publish the changes included in #1943, a fix for a customer-reported issue
N/a
N/a
**After**:
N/a
> Bump patch version for new 2.22.14 release

- web-components/src/[sandbox]/examples/task-item.ts
- web-components/src/components/taskitem/TaskItem.stories.ts
- web-components/src/components/taskitem/TaskItem.test.ts
- web-components/src/components/taskitem/TaskItem.ts
- web-components/src/components/taskitem/TaskItem.utils.test.ts
- web-components/src/components/taskitem/TaskItem.utils.ts
- web-components/src/components/taskitem/scss/settings.scss
- web-components/src/components/taskitem/scss/task-item.scss
- web-components/src/components/tooltip/Tooltip.ts
- web-components/src/components/tooltip/scss/tooltip.scss
- handle truncated words in taskitem with tooltip
**After**:
> fix: handle truncated words in taskitem with tooltip

- web-components/package.json
- web-components/src/components/button/scss/button.scss
fix incorrect secondary active bg color
**After**:
> fix: secondary active background colour

- web-components/src/[sandbox]/examples/floating-modal.ts
- web-components/src/components/floating-modal/FloatingModal.stories.ts
- web-components/src/components/floating-modal/FloatingModal.ts
> fix(floating-modal): new changes

- web-components/package.json
- web-components/src/[sandbox]/examples/icon.ts
- web-components/src/[sandbox]/examples/popover.ts
- web-components/src/components/coachmark-popover/CoachmarkPopover.ts
- web-components/src/components/coachmark-popover/scss/coachmark-popover.scss
- web-components/src/components/popover/Popover.constants.ts
- web-components/src/components/popover/Popover.events.ts
- web-components/src/components/popover/Popover.stack.ts
- web-components/src/components/popover/Popover.ts
- web-components/src/components/popover/Popover.types.ts
- web-components/src/components/popover/Popover.utils.ts
- web-components/src/components/popover/scss/popover.scss
- web-components/src/components/popover/scss/settings.scss
- web-components/src/index.ts
- web-components/src/mixins/FocusTrapMixin.ts
- web-components/src/utils/helpers.ts
Update popover to allow append to and use floating ui
**After**:
> Floating UI popover

- web-components/package.json
- web-components/src/[sandbox]/examples/button.ts
- web-components/src/[sandbox]/examples/popover.ts
- web-components/src/components/button/scss/button.scss
- web-components/src/components/popover/Popover.ts
- web-components/src/components/theme/Theme.test.ts
- web-components/src/components/theme/Theme.ts
Tooltip not updating on message change.
Popover delay effecting click and focus as well as mouse hover
**After**:
> chore: tooltip message change and popover delay

- web-components/package.json
- web-components/src/[sandbox]/examples/popover.ts
- web-components/src/components/popover/Popover.constants.ts
- web-components/src/components/popover/Popover.stack.ts
- web-components/src/components/popover/Popover.ts
- web-components/src/components/popover/Popover.types.ts
- web-components/src/index.ts
- web-components/src/utils/helpers.ts
Add window blur hide property
Add controller for popover (useful when append-to used_
Add updates for click outside hiding
**After**:
> chore: popover updates - controller, windowblur click outside

- web-components/src/[sandbox]/examples/floating-button-bar.ts
- web-components/src/components/floating-button-bar/FloatingButtonBar.stories.ts
- web-components/src/components/floating-button-bar/FloatingButtonBar.ts
- web-components/src/components/floating-button-bar/scss/floating-button-bar.styles.scss
Update floating button bar to allow groups of actions
**After**:
> chore: floating button bar updates for groups

- web-components/package.json
- web-components/src/[sandbox]/examples/popover.ts
- web-components/src/components/popover/Popover.ts
- web-components/src/index.ts
- web-components/src/mixins/FocusTrapMixin.ts
Popover focus back to trigger
**After**:
> chore: fix focus back to trigger

- web-components/package.json
- web-components/src/components/popover/Popover.ts
clicking inside popover closed the popover
**After**:
> chore: fix click on outside popover close

- web-components/package.json
- web-components/src/components/popover/Popover.ts
fix issue when shadow doms
**After**:
> chore: update inside check for shadow dom

- .circleci/config.yml
> chore: fix build running out of memeory

- web-components/src/components/tabs/Tab.ts
- web-components/src/components/tabs/Tabs.stories.ts
- web-components/src/components/tabs/Tabs.ts
- web-components/src/components/tabs/scss/settings.scss
- web-components/src/components/tabs/scss/tab.scss
- web-components/src/components/tabs/scss/tabs.scss
> CX-19566: Configurable tab size

- web-components/src/[sandbox]/examples/chip.ts
- web-components/src/components/badge/tokens/lm-badge-tokens.js
- web-components/src/components/badge/tokens/mdv2-badge-tokens.js
- web-components/src/components/chip/Chip.stories.ts
- web-components/src/components/chip/scss/chip.scss
- web-components/src/components/chip/scss/mixins.scss
- web-components/src/templates/component-colors.hbs
- web-components/src/templates/dark-colors.hbs
- web-components/src/templates/light-colors.hbs
Add new Confidence styles to Chip
**After**:
> style: add new Confidence styles to Chip

- web-components/package.json
- web-components/src/[sandbox]/examples/card-v2.ts
- web-components/src/components/card-v2/CardV2.stories.ts
- web-components/src/components/card-v2/CardV2.test.ts
- web-components/src/components/card-v2/CardV2.ts
Add support for live timestamps in the Cards
**After**:
> #CX-19663 Support Live timestamp in Cards

- web-components/package.json
Update web component version
**After**:
> chore: update web component version

- web-components/package.json
- web-components/src/components/icon/Icon.ts
- web-components/src/components/icon/Icon.utils.ts
- web-components/webpack.config.ts
> chore: temp revert icons as peer dep

- web-components/package.json
- web-components/src/components/icon/Icon.utils.ts
> chore: fix if svg fails to parse

- web-components/package.json
- web-components/src/components/tabs/Tab.ts
- web-components/src/components/tabs/scss/tab.scss
apps that use tab-content as class name for the tab slot getting unwanted styles
**After**:
> fix: tab content style

- web-components/src/[sandbox]/examples/avatar.ts
- web-components/src/[sandbox]/examples/chip.ts
- web-components/src/components/avatar/Avatar.constants.ts
- web-components/src/components/avatar/scss/settings.scss
- add size 16 to md-avatar component
**After**:
> feat(avatar): add size 16 avatar for agent chip

- web-components/package.json
- web-components/src/[sandbox]/examples/date-time-picker.ts
- web-components/src/components/date-range-picker/DateRangePicker.ts
- web-components/src/components/datepicker/DatePicker.ts
- web-components/src/components/datepicker/scss/datepicker.scss
- web-components/src/components/input/Input.ts
- web-components/src/components/timepicker/TimePicker.ts
> fix: time picker not setting time to pm

- web-components/package.json
- web-components/src/[sandbox]/examples/combobox.ts
- web-components/src/components/button/Button.ts
- web-components/src/components/combobox/scss/combobox.scss
- web-components/src/components/tabs/Tab.ts
- web-components/src/components/tooltip/Tooltip.ts
- web-components/src/mixins/ResizeMixin.ts
Fix resize observer issue
Fix combobox dropdown button outside container
Fix selected element not getting focus tab
**After**:
> fix: resize observer illegal invocation

- web-components/package.json
- web-components/src/[sandbox]/examples/date-time-picker.ts
- web-components/src/[sandbox]/examples/datepicker.ts
- web-components/src/components/date-range-picker/DateRangePicker.test.ts
- web-components/src/components/date-time-picker/DateTimePicker.stories.ts
- web-components/src/components/date-time-picker/DateTimePicker.test.ts
- web-components/src/components/date-time-picker/DateTimePicker.ts
- web-components/src/components/datepicker/DatePicker.stories.ts
- web-components/src/components/datepicker/DatePicker.test.ts
- web-components/src/components/datepicker/DatePicker.ts
- web-components/src/components/input/Input.ts
- web-components/src/wc_scss/tools/mixins/input.scss
> #CX-20457: Date Time picker: fix localised date format and disable user typing (repro)

- web-components/package.json
- web-components/src/[sandbox]/examples/timepicker.ts
- web-components/src/components/timepicker/TimePicker.stories.ts
- web-components/src/components/timepicker/TimePicker.test.ts
- web-components/src/components/timepicker/TimePicker.ts
#CX-20584 : Add functionality to show placeholder in md-timepicker
**After**:
> #CX-20584 : Add functionality to show placeholder in md-timepicker

- web-components/package.json
- web-components/src/components/chip/Chip.ts
> #CX-20677: add new part name and prop to md-chip

- web-components/package.json
- web-components/src/[sandbox]/examples/chip.ts
- web-components/src/components/badge/tokens/lm-badge-tokens.js
- web-components/src/components/badge/tokens/mdv2-badge-tokens.js
- web-components/src/components/chip/Chip.ts
- web-components/src/components/chip/scss/chip.scss
- web-components/src/components/chip/scss/mixins.scss
- web-components/src/components/editable-textfield/EditableTextfield.ts
- web-components/src/components/editable-textfield/scss/editable-textfield.scss
- yarn.lock
add warning chip
decorative chips remove hover and active background color
expose editable textfield configuration
**After**:
> chore: add warning chip and update editable textfield

- web-components/package.json
- web-components/src/[sandbox]/examples/tabs.ts
- web-components/src/components/tabs/Tabs.ts
- web-components/src/components/timepicker/TimePicker.ts
> fix: cx-20880 md-tabs tab index out of bounds

- web-components/package.json
- web-components/src/[sandbox]/examples/icon.ts
- web-components/src/components/button/Button.stories.ts
- web-components/src/components/icon/Icon.ts
- web-components/src/components/input/Input.stories.ts
- web-components/src/components/input/Input.ts
- web-components/src/components/input/scss/input.scss
- web-components/src/components/input/tokens/mdv2-input-tokens.js
- web-components/src/wc_scss/settings/input.scss
> Input combo box

- web-components/package.json
- web-components/src/components/skeleton/Skeleton.ts
> feat(skeleton): added skeleton to html element tag name map

- web-components/src/[sandbox]/examples/popover.ts
- web-components/src/components/popover/Popover.ts
- web-components/src/components/popover/Popover.utils.ts
> feat: add nested menu support and fix focus handling in appended popovers

- web-components/package.json
- web-components/src/components/combobox/tokens/mdv2-combobox-tokens.js
- web-components/src/components/dropdown/scss/dropdown.scss
- web-components/src/components/dropdown/tokens/mdv2-dropdown-tokens.js
- web-components/src/components/input/scss/input.scss
- web-components/src/components/input/tokens/mdv2-input-tokens.js
> Input readonly bg color

- web-components/src/components/list-v2/list-item-v2.ts
- web-components/src/components/list-v2/list-v2.stories.ts
- web-components/src/components/list-v2/list-v2.test.ts
- web-components/src/components/list-v2/list-v2.ts
- web-components/src/components/list-v2/scss/list-item-v2.scss
> fix(list-v2) Navigation edge cases, fix stories a11y, add events jsdocs, minor style updates

- web-components/package.json
- web-components/src/components/tabs/scss/tabs.scss
> Fix more tab no truncation

- web-components/package.json
> chore: update webcomponents package version

- web-components/package.json
> chore: update webcomponents package version to 2.26.7

- web-components/package.json
- web-components/src/[sandbox]/examples/input.ts
- web-components/src/components/input/Input.test.ts
- web-components/src/components/input/Input.ts
> feat(md-input): another tweak to the character-count label behaviour

- web-components/package.json
- web-components/src/[sandbox]/examples/radio-group.ts
- web-components/src/components/help-text/HelpText.ts
- web-components/src/components/radio/Radio.test.ts
- web-components/src/components/radio/Radio.ts
- web-components/src/components/radio/scss/radio.scss
Support helper text for radio component
**After**:
> chore: add helper text to radio component

- web-components/src/components/combobox/ComboBox.ts
> chore: Fix type error in tests
