- react/src/lib/EditableTextfield/__snapshots__/index.spec.js.snap
- react/src/lib/EditableTextfield/index.js
- react/src/lib/EditableTextfield/index.spec.js
@aimeex3 
Request to allow EditableTextfield to prevent an empty string as a value.
Solves preventing users from entering empty strings.
Added 4 new tests.
**After**:
> feat(EditableTextfield): add prop allowEmpty to prevent empty value

- core/scss/components/input.scss
- react/src/lib/Input/index.js
- react/src/lib/Input/index.spec.js
Resolves #25, #23 
Removed cloning of class in Input as dom structure is unpredictable.
**After**:
> Input icon fix

- core/scss/components/modal.scss
- On horizontally small screens, modals were already going to full screen.
- Updating the existing behavior to also apply to vertically small screens.
- Related to PROVISION-4260
Tested in Atlas/Control Hub
> fix(modal): Modals go full screen on vertically small screens.

- react/src/lib/Icon/index.js
After the latest update, we could not pass `icon-...` to the name prop of Icon, causing some of our icons in the web-client to not render
Allows both `icon-cancel_18` as well as `cancel_18` to be passed as part of the name prop for Icon
Yes in the playground
**After**:
> fix(Icon): allow icon name to be prefixed with icon-

- react/src/lib/Icon/index.spec.js
#87 fix(Icon): allow icon name to be prefixed with icon
Missing tests for the name prop. Functionality was broken when the component was refactored in #82
2 new tests added
> Add missing tests for the Name prop in the react Icon component

- react/src/lib/SpaceListMeeting/__snapshots__/index.spec.js.snap
- react/src/lib/SpaceListMeeting/index.js
- react/src/lib/SpaceListMeeting/index.spec.js
Add props ```isIMOnlyShare``` for SpaceListMeeting.
If ```isIMOnlyShare``` is set to ```true```,
1. Change the button color to ```blue```
2. Change the icon to ```share```
3. Remove the number of participants
https://github.com/collab-ui/collab-ui/issues/117
Support IM only share feature.
Add unit test for new props.
**After**:
> fix(SpaceListMeeting): add isIMOnlyShare prop and blue button

- react/src/lib/AlertCall/__snapshots__/index.spec.js.snap
- react/src/lib/AlertCall/index.js
- react/src/lib/AlertCall/index.spec.js
BREAKING CHANGE
- onAnswerVideo function prop must be included to include video button
Fixes #118 
**After**:
> feat(AlertCall): add onAnswerShare option

- angular/src/lib/alert-meeting/alert-meeting-config.ts
- angular/src/lib/alert-meeting/alert-meeting-container.component.ts
- angular/src/lib/alert-meeting/alert-meeting.component.ts
- angular/src/lib/alert-meeting/alert-meeting.module.ts
- angular/src/lib/alert-meeting/alert-meeting.service.ts
- angular/src/lib/alert-meeting/examples/avatar.component.ts
- angular/src/lib/alert-meeting/examples/default.component.ts
- angular/src/lib/alert-meeting/examples/examples.module.ts
- angular/src/lib/alert-meeting/examples/index.ts
- angular/src/lib/alert-meeting/examples/multiple.component.ts
- angular/src/lib/alert-meeting/index.ts
- angular/src/lib/alert-meeting/tests/__snapshots__/alert-meeting.service.spec.ts.snap
- angular/src/lib/alert-meeting/tests/alert-meeting.service.spec.ts
- angular/src/lib/examples.module.ts
- angular/src/lib/public_api.ts
> feat(AlertMeeting): add Angular Meeting Alert component

- core/scss/components/button/button.scss
- core/scss/components/button/mixins.scss
Resolves #86 
@stanjiawang I've added the ability to pass in the size prop to the button and it not get overwritten.  The style prop on Button can always be used to do any further modification.
**After**:
> fix(button): set static height of buttons

- angular/src/lib/popover/popover.directive.ts
- angular/src/lib/popover/tests/popover.component.spec.ts
adding popoverTrigger which was not there
**After**:
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes.
> fix(popover): add popoverTrigger Input

- angularjs/src/lib/directives/input/input.directive.ts
This PR is a follow up of the previous PR - FYI - I’ve created a PR to fix momentum issue related to UI warning message - https://github.com/momentum-design/momentum-ui/pull/299
This PR fixes some issues introduced in the previous PR.
In AngularJs directives are created using a factory method, hence the state at the directive method is kept for all instances of the same directive. This introduced new issue
where multiple instances of the directive linked to different elements would see the same state for init. I have fixed that by moving the init state to the scope, which is recreated each time directive is bind to an element, thus guaranteeing recreation of the state for each new linking.
Closes #298
Move the init state from the factory method's scope to the directive's scope
Closes #298 …
> fix: move state creation into prelink and put it on scope

- angular/src/docs/styles.scss
- angular/src/lib/select/select.component.ts
- core/scss/components/cdk-overlay/cdk-overlay.scss
- core/scss/components/components.scss
- core/scss/components/select/select.scss
- core/scss/momentum-ui-ng.scss
z-order of the cdk was 1000 which was conflicting with several of our cmponents now it's 1060
fixing for angularjs for now .. will need to fix anguarl
**After**:
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have read the **CONTRIBUTING** document.
> fix(z-order): import cdk overlay.scss so we can update the z-order

- core/scss/components/input/settings.scss
The color for placeholders in various components was not correct, it was too dark and looked too much like regular text. We've had multiple complaints about this from Control Hub users. We got the color that should have been used from Paul Jeter and Kevin Smith.
From discussion in Teams space:
We looked into this based on complaints from Control Hub users who found that it looked there was already a value in an empty input, they were fooled by the dark placeholder color.
No tests for this seem to be present, but I verified that I'm using the color in the same way that other parts of the CSS are.
> Fix placeholder color

- angularjs/src/lib/components/datepicker/datepicker.component.ts
- core/scss/components/date-picker/date-picker.scss
- when using `md-datepicker` (AngularJS), the vertical alignment of the icon and text looks a bit off-centered (see "before" screenshots)
- issue was discussed in "Momentum UI Q&A"
- fixes layout issue happening in the `md-datepicker` widget by default
- manual testing in several instances of the widget used in our app
- use case 1:
- use case 2:
**After**:
- use case 1:
- use case 2:
> fix(datepicker,angularjs): vertical center alignment of calendar icon button + text

- react/src/lib/List/index.js
List is causing a crash when opening the list through a button. If the index of the focus is not found, then it tries to call `attribute` on a null object and crash. 
Tested this with the Teams Web Client.
**After**:
> fix(list): fix focus index out of bounds

- angular/src/lib/tooltip/tooltip.directive.ts
- Enable custom delay for tooltip when allowHover is true
- Fix behavior on destroy
**After**:
> fix(tooltip): enable custom delay for tooltip when allowHover is true

- angular/src/lib/alert-banner/alert-banner.component.ts
- for angular alert-banner hide observers shouldn't be required for non-closable banners 
**After**:
> fix: 🐛 alert-banner hide not required for non-closable banners

- angular/src/lib/radio/radio.component.ts
When the `radioClick` emit the output event, it didn't pass the original event. So it's not possible to get the output event to do something.
**After**:
> fix(radio): emit the click event

- core/scss/ng/breadcrumbs.scss
- core/scss/ng/settings/sidepanel.scss
- core/scss/ng/side-panel.scss
Updating core CSS (without changing the HTML) to the sidepanels to match the latest UI spec I got from Kevin:
This is how it looks in Control Hub, when paired with another similar PR for Control Hub (https://sqbu-github.cisco.com/WebExSquared/wx2-admin-web-client/pull/13577):
> style(side-panel): match latest UI spec

- angular/src/lib/modal/modal-header.component.ts
- angular/src/lib/modal/tests/__snapshots__/modal.component.spec.ts.snap
Add `type=button` to the closing modal button.
https://github.com/momentum-design/momentum-ui/issues/535
Tested in Momentum Angular Playground. This change only affects one test snapshot which has been updated.
> fix(modal): add type to close modal button

- angularjs/src/lib/components/tokenfield/tokenfield.component.ts
- replace preLink/postLink with single link function
- remove `replace` and select correct element for tokenfield jquery
**After**:
> feat(angularjs): allow 'mdTokenField' to work with UpgradeComponent

- angular/src/lib/modal/modal-header.component.ts
- core/scss/components/modal/modal.scss
1. Show the box shadow when the modal close button is focused.
2. Remove keydown event.
Note that, when pressing Enter or Space while the focus is on the button, the browser triggers a click event and the modal will get closed.
https://github.com/momentum-design/momentum-ui/issues/537
> fix(modal): remove keydown event on close button

- angular/src/lib/data-table/index.ts
- angular/src/lib/select/select.component.ts
PROVISION-5931
Filter value clears after close/detach restoring original select options to show
export data table checkbox component  
fix for ChangeDetectionStrategy.OnPush, the setTimeout was creating issues not closing the select overlay after single click when onPush is used, removed closeDuration prop fixing issue 
**After**:
> fix(select): clear out filter value on overlay close and restore options, fix for onPush change detection, add export for table checkbox

- core/scss/components/button/button.scss
- core/scss/components/button/examples/color.html
This adds a blue outline button class to the button.scss
https://github.com/momentum-design/momentum-ui/issues/556
Designs at https://momentum.design/components/button/style have led the designers to believe there is a blue outline button in momentum, but there isn't one.
Example added to playground and inspected visually.
New Feature - added a CSS class for buttons to give us another color option.,
> adds blue outline button to our button scss

- angular/src/lib/modal/modal-header.component.ts
- angular/src/lib/modal/modal.component.ts
- angular/src/lib/modal/tests/__snapshots__/modal.component.spec.ts.snap
replaced cdkTrapFocusFix with cdkTrapFocusAutoCapture so that first focusable element will be focused instead of last when the modal is opened
Fix: Now description input is focused instead of code input when modal is opened
**After**:
> fix(modal) : added cdkTrapFocusAutoCapture 

- angular/src/lib/modal/modal.service.ts
The angular modal overlay config is missing the backdrop class. The consequence is that the overlay backdrop color is inconsistent between the angularjs and angular modals.
Make the angularjs and angular modal backdrop color consistent.
> fix(modal): Set the backdropClass for the angular modals

- .gitignore
- angular/src/lib/select/select.component.ts
- angular/src/lib/select/tests/select.component.spec.ts
default to an empty array in makeSelectOptions if the input options are an empty array
Closes internal jiras
**After**:
> fix(angular-selector): default to an empty array in makeSelectOptions

- react/src/lib/Lightbox/index.js
- react/src/lib/Lightbox/tests/__snapshots__/index.spec.js.snap
- react/src/lib/Lightbox/tests/index.spec.js
This change allows user to pass in a class name to the img tag. For the web client's particular use case, some images that are attached need to be rotated and this classname allows to rotate the image. I believe this component was ported over from our old web-client-components repo, but don't think all the props were ported over in the first pass
see above description
**After**:
> feat(Lightbox): pass img class name to viewport

- react/src/lib/EventOverlay/index.js
SSR applications can not use the latest version of momentum anymore. and the error is caused by [this line](https://github.com/momentum-design/momentum-ui/blob/master/react/src/lib/EventOverlay/index.js#L1038). I figured to use React Element instead of a Browser global.
change Browser defined Element to React Element.
momentum components are not SSR-compatible anymore.
to make momentum SSR compatible agian.
yes
**After**:
- [] I have added tests to cover my changes.
> Change Browser Global Element to React Element to make momentum SSR-compatible again

- react/src/lib/ListItemMeeting/index.js
- react/src/lib/ListItemMeeting/tests/index.spec.js
MeetingListItem shows an empty popover (event overlay) if you don't pass it any content. Some people may not want a popover. Let's support that!
Wrote a new Jest test
> fix: don't show popover content if it's null

- web-components/src/components/tabs/Tabs.test.ts
- web-components/src/components/tabs/Tabs.ts
- web-components/src/components/tabs/scss/tabs.scss
In case when tabs items overfits their container - "more" dropdown menu bounds to right border and fold width
**After**:
> manro/more tab bound to right + no-grow

- web-components/src/[sandbox]/examples/modal.ts
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/menu-overlay/MenuOverlay.test.ts
- web-components/src/components/menu-overlay/MenuOverlay.ts
- web-components/src/components/tabs/Tab.test.ts
- web-components/src/components/tabs/Tab.ts
- web-components/src/components/tabs/tokens/md-tabs-tokens.js
- web-components/src/mixins/FocusMixin.test.ts
- web-components/src/mixins/FocusMixin.ts
- web-components/src/mixins/FocusTrapMixin.test.ts
- web-components/src/mixins/FocusTrapMixin.ts
Fix issue with tabbing in sequentially and click focusable new elements
For controlling the tabbing order for elements that is out of flow with DOM order, focus trap mixin should be cyclical and must be explicitly put non-tabbable elements in tab flow.
**After**:
> fix(mixin): fix issue with tabbing in sequentially and click focusable new elements

- web-components/src/components/menu-overlay/MenuOverlay.ts
- web-components/src/components/modal/Modal.ts
- web-components/src/mixins/FocusTrapMixin.test.ts
- web-components/src/mixins/FocusTrapMixin.ts
Wait until initial provided element receive focus
Element that should receive focus after first browser render cycle now more prioritize 
**After**:
> fix(mixin): wait until initial provided element receive focus

- web-components/src/index.ts
Exporting all existing components.
Any component that is not exported is not accessible for people wanting the use our components.
**After**:
> fix(web-components): add forgotten component exports

- web-components/src/[sandbox]/examples/menu-overlay.ts
- web-components/src/components/menu-overlay/MenuOverlay.ts
- web-components/src/components/tabs/Tabs.ts
> fix(tabs): add event-listener for close overflow (CAX-839)

- web-components/src/components/datepicker/DatePicker.test.ts
This update fixes a brittle DateTime measurement that breaks the tests on end/beginning days of a month. It now uses `ordinal` to compare dates which is not affected by change in months
**After**:
> fix(datepicker): test refactor

- web-components/src/components/avatar/Avatar.ts
This adds a `part` attribute to the rendered Avatar for ease of styling in applied use.
**After**:
> feat(avatar): add part to avatar

- web-components/src/components/radio/Radio.ts
This PR restores class-name edits that caused a styling bug in 2.1.2
https://jira-eng-sjc12.cisco.com/jira/browse/CAX-911
Change Radio Button class names from 
**After**:
> fix(radio): repair style with class name edit

- react/package.json
Changed Node version cap from 14.15.1 to 14 to allow for using node LTS
This is a continuation of issue #745, tidying up a missed consideration
https://github.com/momentum-design/momentum-ui/issues/745 
Allows for using Node 14 LTS in other projects that use momentum-ui/react as a dependency
> build(node): remove node version detail to allow for lts

- web-components/src/components/phone-input/PhoneInput.test.ts
- web-components/src/components/phone-input/PhoneInput.ts
- web-components/src/components/phone-input/scss/phoneInput.scss
In the PhoneInput component there is a combobox that lists country codes. This adds the usa flag when the US country code is selected
https://github.com/momentum-design/momentum-ui/issues/827
New Unit tests Added. Changes tested in Firefox and Chrome browser.
**After**:
> Add usa flag to PhoneInput country code dropdown combobox

- web-components/package.json
in recent times - after "yarn install"
I had types mismatch with webpack-merge
and it is fixed by updating major version of webpack-merge
**After**:
> chore(web-components):bump version for webpack merge

- core/scss/components/alert/alert.scss
Hotfix to fix transparent backgrounds on alerts without theming.
> fix(core/alert): transparent backgrounds

- web-components/src/components/menu-overlay/MenuOverlay.ts
RE: https://jira-eng-sjc12.cisco.com/jira/browse/CAX-944
It is unclear why/how Card uses a persisting menu, and since it causes MenuOverlay to break elsewhere, I suggest keeping the overly behavior to close when another menu is opened.
Remove `event.stopPropogation()` from Menu Overlay's `handleTriggerClick` method.
**After**:
> fix(menu-overlay): restore functionality

- react/src/lib/EventOverlay/index.js
- react/src/lib/Lightbox/index.js
- react/src/lib/Popover/examples/Direction.js
- react/src/lib/Popover/examples/KitchenSink.js
- react/src/lib/Popover/tests/index.cy.js
- react/src/lib/Tooltip/examples/Direction.js
Fix a few issues with the event overlay which are noticeable on the lightbox tooltips
When the isContained flag is true, both bottom and left positioned overlays were broken. The bottom positioning was broken when the element is on the far right of the page. The left positioned overlay would stretch to the far left of the page.
In addition, the props for the tooltips in the lightbox were being specified incorrectly. The Tooltip component does not take a direction property, instead taking a popoverProps object.
In the EventOverlay component, reliance on documentRight for positioning is broken in the presence of a scrollbar. I've removed this problem by no longer relying on documentRight for the bottom or left contained positioning.
#848
Fixes light box tooltips
Checked visually on the …
> fix(tooltips): fix tooltips for lightbox

- react/src/lib/Popover/tests/index.cy.js
The new popover test cases for isContained that I added recently have a case which has an intermittent failure in the percy tests. Until it can be fixed I'm disabling it so it doesn't break the build.
**After**:
> fix(popover): temporarily disable intermittent popover test case

- web-components/src/components/combobox/ComboBox.ts
Updated the search parameter for custom Value  and removed shadow under the empty list box
1. The issue occurs whenever someone used to search for custom values with spaces in it (or say multiple words). So when user enters a values and a space it always used to give no result because what the code was doing, it was replacing the custom value and trimming all the spaces. Thus the entered value suppose "blah test" was being replaced to "blahtest" and that's why the include always failed. IT was like "blahtest".includes("blah t") instead it should have been "blah test".includes("blah t")
2. When entering custom values the user doesn't expect to see the No Result if nothing matched. But what was happening the list box used to become empty but there was a slight shadow left beneath of the …
> fix(combobox): removed unwanted shadow

- web-components/src/wc_scss/themes/global--dark.scss
- web-components/src/wc_scss/themes/global--light.scss
RE: #940 
Add light/dark tokens.
**After**:
> feat(web-components): new slate tokens for conference chat

- web-components/package.json
- web-components/src/components/button/Button.ts
1. Adding check for properties ariaLabel and ariaLabelledBy - if they are not provided or empty it should not render.
2. Updated `momentum-ui/core` version from  `19.15.8` to **`19.15.9`** in web-components.
[CX-7012: momentum web component: Unnecessary aria attributes are added with empty string](https://jira-eng-chn-sjc3.cisco.com/jira/browse/CX-7012)
[CX-7012: momentum web component: Unnecessary aria attributes are added with empty string](https://jira-eng-chn-sjc3.cisco.com/jira/browse/CX-7012)
**After**:
> Remove aria attributes in button and momentum-ui/core upgrade in web-components.

- web-components/src/components/input/Input.test.ts
- web-components/src/components/input/Input.ts
> fix: Remove input clear button, if input is readonly

- web-components/src/components/phone-input/PhoneInput.ts
> #CX-8535 : Add custom event for country code change in phone input component

- web-components/src/components/dropdown/Dropdown.test.ts
- web-components/src/components/dropdown/Dropdown.ts
Dropdown component does not watch for changes in `defaultOption` prop, when this is changed programatically. This results in display of outdated selected option on UI.
This PR fixes this issue by adding a watcher for changes in `defaultOption` prop.
Discovered this issue while implementing user preferences pane in UX refresh
Tested using built bundle in consumer code. And also via unit tests
**After**:
> feat: dropdown to watch for changes in default option prop

- icons-rebrand/package.json
- icons/package.json
- tools/icons/generators.js
- Upgraded node-sass to sass in icons folder to make Icons Font generation work again.
- Tested locally by running `yarn build:icons-rebrand`
> fix: upgraded node-sass to sass

- web-components/package.json
- web-components/src/components/combobox/ComboBox.test.ts
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/mixins/FocusTrapMixin.test.ts
Home Page: Search- All is always present when searching for any specific entity
Searching or typing in input field is restricted in case of allow-select-all is true
**After**:
> fix: Home Page: Search- All is always present when searching for any specific entity

- web-components/package.json
- web-components/src/components/modal/Modal.test.ts
- web-components/src/components/modal/Modal.ts
> #CX-9804 : fix for inactivity popup on inactive screen

- web-components/src/[sandbox]/examples/date-time-picker.ts
- web-components/src/components/audio-player/AudioPlayer.ts
The audio player will now stop audio when the component is destroyed and the audio player will not dispatch an error when the src is an empty string
Error handling for audio src will ignore empty strings to avoid error dispatching when component is mounted but src has  not yet been set. The component will also stop any playing audio when teardown occurs, due to no native way to destroy audio sources in browser.
**After**:
> fix: enhance audio player error dispatching and teardown

- web-components/package.json
- web-components/src/components/audio-player/AudioPlayer.ts
- web-components/src/components/audio-player/scss/audio-player.scss
- web-components/src/components/audio-player/tokens/lm-audio-player-token.js
- web-components/src/components/audio-player/tokens/md-audio-player-token.js
The audio player component now has a timeline indicator to show what range is buffered
A separate gray indicator has been added to the timeline (progress bar) of the audio component to indicate which portion of it has been buffered
https://jira-eng-sjc12.cisco.com/jira/browse/CX-11617
**After**:
https://github.com/momentum-design/momentum-ui/assets/20385642/c142713e-e85b-44b1-9dc8-ac0f411b8ab8
> feat: add buffering state to audio player component

- web-components/package.json
- web-components/src/components/tabs/tokens/lm-tabs-tokens.js
- web-components/src/components/tabs/tokens/md-tabs-tokens.js
Addressed active tab color contrast issue, changed the color code so that color contrast of at least 4:5:1 is maintained.
**After**:
> fix: 🐛 active tab color contrast issue

- web-components/package.json
- web-components/src/components/menu-overlay/MenuOverlay.ts
Accessibility fix for menu-overlay component 
Updated the role type to "menu" from "tooltip" for the menu overlay component
https://jira-eng-sjc12.cisco.com/jira/browse/CX-13319
Referred : https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles
[ARIA: menu role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menu_role)
The menu role is a type of composite widget that offers a list of choices to the user.
Screen Recording of before and after fix:
https://github.com/momentum-design/momentum-ui/assets/41052645/7c7eeec1-aab1-45b0-89df-e71b0bd97ad0
> Accessibility fix: [CX-13319] updated role for menu overlay component 

- web-components/src/components/tabs/Tabs.ts
Updated Tab panel id to be unique and not same as tab id
Story: https://jira-eng-sjc12.cisco.com/jira/browse/CX-10177
**Before** :
**After**:
> fix (accessibility): updated tab panel id to be unique

- web-components/src/components/floating-modal/FloatingModal.ts
Story - CX-10233
Prerequisites:
1. Tab to reach the Webex button and press enter to activate it.
2. Tab to reach the resize modal button and observe the announcement when it is full-screen mode and half-screen mode.
**Expected Result:**
The resize Modal button should be announced with sufficient context i.e. When the model is in halfscreen mode, it should announce as 'Halfscreen Resize Modal' and when the model is in fullscreen mode, it should announce as 'Fullscreen Resize Modal' or similar.
**Actual Result:**
The 'Resize Modal' button is announced without sufficient context. i.e.
- the 'Resize Modal' button announces the same label for both the half-screen and full-screen mode and the screen reader user will not know the state of the control as 'Resize Modal, button'
**Before** (If …
> CX-10233 : Screen Readers: Resize Modal button is announced without sufficient context

- web-components/package.json
- web-components/src/[sandbox]/examples/link.ts
- web-components/src/components/link/Link.stories.ts
- web-components/src/components/link/Link.test.ts
- web-components/src/components/link/Link.ts
Added aria label and role property for md-link component
Story: https://jira-eng-sjc12.cisco.com/jira/browse/CX-10268
1) md-link only reads the text and does not provide any aria label if more description is required
2) Some places the role needs to be button, hence added new property to accept role
1) Tested using Mac VoiceOver
2) Tested using JAWS
3) Added UTs 
4) Tested story book
**After**:
Video
https://app.vidcast.io/share/4bcaef25-8e93-4be7-a252-7b16a9a072c3
Coverage
> #feat: added arai label and role property for link component

- web-components/src/[sandbox]/examples/link.ts
- web-components/src/components/link/Link.stories.ts
- web-components/src/components/link/Link.test.ts
- web-components/src/components/link/Link.ts
Renamed role to ariaRole attribute to avoid conflict of attribute names
https://github.com/momentum-design/momentum-ui/pull/1551
In react based component, the property can not be passed with dot notaion. To avoid the conflict, renamed the role to ariaRole
1. Updated UTs
2. Updated story book
3. JAWs will read out twice if the role is in parent and child both, hence fixed by renaming it to ariaRole.
**After**:
> feat: Renamed role to ariaRole property

- web-components/src/[sandbox]/examples/menu-overlay.ts
- web-components/src/components/menu-overlay/MenuOverlay.stories.ts
- web-components/src/components/menu-overlay/MenuOverlay.test.ts
- web-components/src/components/menu-overlay/MenuOverlay.ts
> #CX-10275: fix(accessibility)Profile: Screen reader: User agent profile dialog is not implemented or announced as such

- web-components/src/components/modal/Modal.ts
Added id for modal header
[CX-10496](https://jira-eng-sjc12.cisco.com/jira/browse/CX-10496): Transfer Request dialog is announced with incorrect label 
By adding id field, the aria-labelledby will be used to announce the dialogue header
1. Tested in Jaws, announcing the header on open
2. Mac Voice Over - known issue of dialogue not announcing the header
**Before**:
Refer the jira for video
**After**:
https://app.vidcast.io/share/e7dd4b3d-4c1b-4a0c-9751-29446cc791e3
> fix: added id for modal header

- web-components/src/components/combobox/ComboBox.ts
> fix(cx 10437) : Outdial Call: Screen Readers: Combobox expand/collapse button focused separately

- web-components/src/components/badge/Badge.ts
> fix(cx-10429) : Meaningful icons focused but not announced 

- web-components/src/components/tabs/Tab.ts
When tabs are initialised, the `aria-selected` attribute is set false even for the selected tab. This causes screen reader to wrongly announce 'select' on the selected tab. This PR corrects the aria-label by using `selected` property
Root cause: On initial mount, `connectedCallback` is called after `set` function for `_selected` property. Hence even if the `_selected` property is set correctly, `aria-selected` gets set to false incorrectly
Fix a11y issues
Ran voiceover on MAC and JAWS on windows
**After**:
> CAUI-8826 - Fix a11y for default tab selection

- web-components/src/components/button/Button.test.ts
- web-components/src/components/button/Button.ts
As buttons, input and anchor already have tabindex of 0 and are by default included in keyboard tab navigation so removing explicit tabindex=0 from them and for buttons we are removing explicit attribute of role=button
**After**:
> fix(cx-10583): remove unwanted attributes from element

- web-components/src/[sandbox]/examples/button.ts
- web-components/src/components/button/Button.test.ts
- web-components/src/components/button/Button.ts
Added new prop ariaLive in button, the prop will be rendered only if passed.
aria-live is used by Assistive technologies to announce dynamic changes in the content.
1) Added UTs
2) Added sandbox example
**After**:
When ariaLive is passed:
When ariaLive is not passed:
> fix(CX-13612) : added ariaLive prop in button

- web-components/src/components/dropdown/Dropdown.ts
- web-components/src/components/input/Input.ts
- web-components/src/components/menu-overlay/MenuOverlay.test.ts
- web-components/src/wc_scss/tools/mixins/input.scss
cx-13374
1. Open the dropdown using space key.
2. When tab key is presses the dropdown closes and focus moves to next focusable element
**After**:
> fix(cx-13374): Global: Keyboard Navigation: Role select menu does not follow the expected kb navigation pattern

- web-components/src/components/editable-textfield/EditableTextfield.test.ts
- web-components/src/components/editable-textfield/EditableTextfield.ts
> CX-14789 : Removed role and aria labels for disabled fields

- web-components/src/components/alert/Alert.ts
Removing aria-label since the content and aria-label is same, when without aria-label content will get announced by SR
**After**:
> #CX-10208 : Global: Chrome + JAWS: Incorrect heading structure in the notifications dialog

- web-components/src/components/input/Input.ts
- web-components/src/mixins/FocusTrapMixin.test.ts
- web-components/src/mixins/FocusTrapMixin.ts
> #CX-10573 : Focus does not move to clear input button properly

- web-components/src/components/datepicker/datepicker-day/DatePickerDay.ts
The tooltips for the days in the `DatePickerDay` were not localised, and were always showing as english, regardless of the specified locale. This change fixes this so that the tooltip always reflects the browser locale.
**After**:
> fix: localise DatePickerDay tooltip

- web-components/src/components/avatar/Presence.test.ts
- web-components/src/components/avatar/Presence.utils.ts
- web-components/src/components/icon/Icon.ts
Icon will show errors when there is an empty var icon name. 
**After**:
> fix(icon): accept empty var

- web-components/src/components/tabs/scss/tab.scss
High Contrast: The selected tab is not visually differentiated from non-selected ones
**After**:
> fix(highcontrast): selected tab in highlight

- web-components/package.json
- web-components/src/[sandbox]/examples/card.ts
- web-components/src/[sandbox]/examples/favorite.ts
- web-components/src/[sandbox]/examples/menu-overlay.ts
- web-components/src/[sandbox]/examples/tabs.ts
- web-components/src/components/button/tokens/mdv2-button-tokens.js
- web-components/src/components/card/Card.ts
- web-components/src/components/favorite/Favorite.test.ts
- web-components/src/components/favorite/Favorite.ts
- web-components/src/components/favorite/scss/favorite.scss
- web-components/src/components/favorite/scss/settings.scss
- web-components/src/components/floating-modal/FloatingModal.test.ts
- web-components/src/components/meeting-alert/MeetingAlert.ts
- web-components/src/components/menu-overlay/MenuOverlay.ts
- web-components/src/components/slider/tokens/mdv2-slider-token.js
* Update momentum-design/icons
* Update momentum-design/tokens
* Fix eslint issue
* Favorite updates
**After**:
> chore: update dependencies, fix eslint issues, update favorite

- web-components/package.json
- web-components/src/components/avatar/tokens/mdv2-avatar-tokens.js
- web-components/src/components/button/tokens/mdv2-button-tokens.js
* Update momentumV2 unavailable and rona colours after design change
**After**:
> chore: update the rona colours

- web-components/src/wc_scss/themes/global--dark.scss
- web-components/src/wc_scss/themes/global--light.scss
- web-components/src/wc_scss/themes/global--mdv2.scss
Add color tokens for wxcc tpw in mdv2d
**After**:
> style(tpw): color tokens for tpw in mdv2

- web-components/src/components/date-range-picker/DateRangePicker.test.ts
- web-components/src/components/date-range-picker/DateRangePicker.ts
Currently there appears to be no easy way for a consumer of the DateRangePicker component to get the startDate and endDate or listen to updates to these. Added a simple CustomEvent that emits both property values when they are set.
Makes using the component as a consumer easier.
Ran all the tests, and added annew one for new event. This change should not at all effect any current behaviour of the component.
**After**:
> add date range change event to DateRangePicker

- web-components/package.json
- web-components/src/components/menu-overlay/MenuOverlay.ts
- web-components/src/mixins/FocusTrapMixin.ts
Fixes an issue: CX-16951
Null check the trigger element in the focus trap mixin
Menu overlay sets focus on the trigger element. If this is null it will cause an exception
**After**:
> chore: add null checks to setFocusOnTrigger

- web-components/package.json
- web-components/src/[sandbox]/sandbox.ts
- web-components/src/components/theme/ThemeManager.ts
- web-components/src/index.ts
Add themeManager for managing global theme state
**After**:
> chore: add themeManager to manager global theme

- web-components/src/components/combobox/ComboBox.test.ts
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/timepicker/TimePicker.ts
fixes an Inconsistancy in timepicker where multiple options cannot be seen by the User.
Allowing the combo-box to turn on/off the filtering option. In the time-picker we use combo box for am/pm. We set the value explicitly, so when the User clicks on the am/pm dropdown, they are auto searching for that and hiding the other value. The use case here is to prevent that functionality when not required.
https://jira-eng-sjc12.cisco.com/jira/browse/CX-17005
Allows the component to be extensible for more use cases.
Manually and in Unit tests.
**After**:
> fix(release): allow combobox the option to turn off filtering

- web-components/src/components/date-range-picker/tokens/md-date-range-picker-tokens.js
- web-components/src/components/datepicker/tokens/md-datepicker-tokens.js
Updating the hover colour for date picker in momentum for visibility.
Updating the hover colour on the months to allow user to see the number while hovering.
Visibility issue on button text.
**After**:
> WC Datepicker -  hover update color for visibility.

- web-components/package.json
- web-components/src/components/button/Button.ts
- web-components/src/components/button/tokens/lm-button-tokens.js
Update button colour for ghost variant in the lumos theme
**After**:
> chore: update lumos ghost button colour

- web-components/src/components/date-time-picker/DateTimePicker.test.ts
- web-components/src/components/date-time-picker/DateTimePicker.ts
- web-components/src/components/datepicker/DatePicker.test.ts
- web-components/src/components/datepicker/DatePicker.ts
Events need to propogate to the UI impl on blank values for dates. So that the UI can respond appropriately.
The if statement would ignore blank values, and the method flow would propogate the previous value, which is then ignored by DateTimePicker.ts in it's updated flow.
Makes sure any UI that implements this can respond if required to a blank value entering the input field for the date picker.
Manually(Sandbox) and in tests.
**After**:
> # CX-17328 - fix(release): update event flow for date picker

- web-components/package.json
- web-components/src/components/coachmark-popover/scss/coachmark-popover.scss
- web-components/src/components/favorite/scss/favorite.scss
- web-components/src/components/icon/scss/icon.scss
- web-components/src/components/menu-overlay/scss/menu-overlay.scss
- web-components/src/components/toggle-switch/scss/toggle-switch.scss
* Fix SVG icon has colour when forced colors active
* Fix menu overlay arrow is a black square when forced colours active
* Fix coachmark popover has an extra border in nits container
**After**:
> chore: fix when forced colors active svg icons still have colours

- web-components/src/[sandbox]/examples/avatar.ts
- web-components/src/[sandbox]/examples/chat-message.ts
- web-components/src/[sandbox]/sandbox.ts
- web-components/src/assets/styles/fonts.css
- web-components/src/components/breadcrumb/Breadcrumb.ts
- web-components/src/components/button/Button.test.ts
- web-components/src/components/combobox/ComboBox.ts
- web-components/src/components/link/Link.test.ts
- web-components/src/components/popover/Popover.ts
- web-components/src/components/tabs/Tabs.ts
- web-components/src/components/tooltip/Tooltip.ts
- web-components/src/mixins/FocusMixin.ts
* When running the sandbox every tabpanel render function is called on startup by changing this so only the selected tab is rendered (which is configurable) it will help with faster load times and debugging of issues in individual tabs
**After**:
> chore: only render selected tab panel

- web-components/package.json
- web-components/src/components/tabs/Tab.test.ts
- web-components/src/components/tabs/Tab.ts
- web-components/src/components/tabs/scss/tab.scss
Add legacy third party test compatibility hidden button
**After**:
> chore: add legacy test compatibility to tab

- web-components/src/[sandbox]/examples/date-range-picker.ts
- web-components/src/components/date-range-picker/DateRangePicker.test.ts
- web-components/src/components/date-range-picker/DateRangePicker.ts
Follow up to https://github.com/momentum-design/momentum-ui/pull/1907/
See title
**After**:
> #CX-18460: Make date range picker startDate/endDate auto-update value

- web-components/src/components/card-v2/CardV2.test.ts
- web-components/src/components/card-v2/CardV2.ts
- web-components/src/components/card-v2/scss/card-v2.scss
Allow the Cardv2 to be clickable from anywhere on the card background (feedback from testing and agreed with the Applause team) - user can also still navigation to the expand/collapse button using the keyboard.
**After**:
> Expand/collapse Cardv2

- web-components/src/[sandbox]/examples/date-range-picker.ts
- web-components/src/[sandbox]/examples/datepicker.ts
- web-components/src/components/date-range-picker/DateRangePicker.test.ts
- web-components/src/components/date-range-picker/DateRangePicker.ts
- web-components/src/components/datepicker/DatePicker.test.ts
- web-components/src/components/datepicker/DatePicker.ts
- web-components/src/components/datepicker/scss/datepicker.scss
- web-components/src/components/presence/scss/presence.scss
fixes date range picker aria-lable, which before was just using what it inherited from its parent. Also added in better handling for invalid dates.
Also fixed a very minor visual bug in date-range-picker end date: 
Before:
After:
(https://jira-eng-sjc12.cisco.com/jira/browse/CX-19529)
**After**:
> #CX-19330: fix date range picker screen reader labels

- web-components/package.json
- web-components/src/[sandbox]/examples/badge.ts
- web-components/src/components/badge/Badge.ts
- web-components/src/components/badge/badge.constant.ts
- web-components/src/components/badge/scss/badge.scss
- web-components/src/components/badge/tokens/mdv2-badge-tokens.js
- web-components/src/components/chip/scss/chip.scss
- web-components/src/components/chip/scss/mixins.scss
Badge size 36 support
Sentiment chip leading icon color
**After**:
> chore: add badge size 36 and sentiment icon
